### ISSUE TITLE
Couple questions

### ISSUE THREAD

**Issue by patrick-bark** [victorcoder/dkron#101]
Hey, I'm sorry about directing these here, but not sure where else to go. My team and I are looking at implementing this, we have a couple questions though:

Can you execute commands on remote servers?

When do you all think this will be stable? Are you still seeing bugs in basic executions?

Thanks

**Comment by victorcoder** [comment]
>Can you execute commands on remote servers?

Dkron is designed for that!

We're currently using it in production with moderate workloads and it's working well so far.

Just expect a new release 0.7 in the following days that will fix major issues, I think that could be considered as stable.

I'll keep the issue open until release

**Comment by patrick-bark** [comment]
Awesome man, we are really looking forward to using this.

**Comment by patrick-bark** [comment]
Ok, I want to make sure I am understanding this correctly. In order to execute remotely, the remote server needs to have dkron installed similar to the `dkron_seed` in docker-compose.yml?

**Comment by victorcoder** [comment]
They need dkron running in client mode, it's lightweight.

dkron_seed is also a server, servers also work as clients.

**Comment by victorcoder** [comment]
@patrick-bark New release is of out the oven. Please try it out.
