### ISSUE TITLE
Leader election issues when upgrading from 0.6.3 to 0.7.0

### ISSUE THREAD

**Issue by whizz** [victorcoder/dkron#104]
Apparently, the leader election process has changed and the backend storage format has too. When upgrading existing cluster, the cluster will not recover from this by itself. The leader key must be deleted manually from backend storage (in my case consul). After that, the leader election happens and all is well. Maybe the cluster could recognize, that the leader data is in old format and delete it by itself?

**Comment by victorcoder** [comment]
@whizz there's a small note in the changelog about this. https://github.com/victorcoder/dkron/blob/master/CHANGELOG.md#upgrade-from-06x

Yes it could be possible but I didn't make the effort.

**Comment by whizz** [comment]
Fair enough. I totally missed that note in changelog.
