### ISSUE TITLE
No documentation on -join option

### ISSUE THREAD

**Issue by patrick-bark** [victorcoder/dkron#106]
Hey, I see the `-join` option used in `docker-compose.yaml`, but I can't find docs on it. What does this do?

**Comment by victorcoder** [comment]
@patrick-bark yep, important info missing, I'll be adding it to docs.

**Comment by patrick-bark** [comment]
Sounds good thanks, could you explain it to me in the meantime so I can get it running?

**Comment by victorcoder** [comment]
https://www.serfdom.io/docs/agent/options.html#_join
