### ISSUE TITLE
Jobs run :05 or :10 after schedule

### ISSUE THREAD

**Issue by greggilbert** [victorcoder/dkron#111]
I'm still in the early stages of investigating this, but I thought I'd open a ticket in case you had some insight.

We're noticing that for most of the time, the jobs run exactly at :00. But once in awhile - particularly if the instance is running at least one other thread - it will run at :05 or :10 after. It's never in between; rather, it's always increments of 5 seconds.

Any idea why this might be, and if there's anything that can be done to alleviate?

(For what it's worth, this is 0.6.3.)

**Comment by victorcoder** [comment]
@greggilbert well, I must warn you to not use anything below 0.7.x

Said that, I've never observed this behaviour, could you please post the job executions result of that? 

You can get that by using the http://dkron.io/docs/api/#execution endpoint

**Comment by greggilbert** [comment]
I'm gonna close this out based on user error. We were seeing a discrepancy in our logging. Thanks for maintaining such an awesome project!
