### ISSUE TITLE
Support for long Job Commands

### ISSUE THREAD

**Issue by seiffert** [victorcoder/dkron#122]
We are still struggling with the length limit for commands which was made explicit in #114. To solve this issue, we'd like to suggest the following change: Instead of [sending the whole execution via serf](https://github.com/victorcoder/dkron/blob/f721d1c784c437d68cda286fe66a70d9ef60bd0e/dkron/agent.go#L702-L715), we could just send the job's name and something identifying (maybe [the `Group`](https://github.com/victorcoder/dkron/blob/f721d1c784c437d68cda286fe66a70d9ef60bd0e/dkron/agent.go#L704)?) via serf and have the client nodes fetch the job via RPC.

From the [code](https://github.com/victorcoder/dkron/blob/f721d1c784c437d68cda286fe66a70d9ef60bd0e/dkron/rpc.go) I can tell that RPC is already used to communicate the results of an execution, so maybe transferring the job payload might be a good solution as well. 

What do you think about this idea? If you like it, we could contribute an implementation.

**Comment by victorcoder** [comment]
I like the approach @seiffert, but it would need some work and planning. 

What do you think about this outline:

1. Send the query to the client signaling the intent to start an execution, passing just the jid (name) and the server RPC addr.
2. Client respond to the query with ACK, and calls the server RPC method that returns the Execution as a reply.
3. When client finished execution proceed as normal calling `executionDone`

Happy that you are willing to implement this, we could go forward and don't hesitate to contact for review any problems.

**Comment by seiffert** [comment]
This plan sounds good to me! About passing the server RPC address: When sending the execution results, clients query the RPC host via serf (if I understand it correctly). Should we adapt that code to use the same RPC host address (by passing it through `AgentCommand.invokeJob`)?
