### ISSUE TITLE
Executions endpoint returns 404 if there are no executions yet

### ISSUE THREAD

**Issue by mlafeldt** [victorcoder/dkron#123]
For example, when creating an "example" cron, the endpoint `/v1/executions/example` will return this in case the cron job wasn't executed yet:

```
< HTTP/1.1 404 Not Found
< Content-Type: application/json; charset=UTF-8
...
< Content-Length: 3
< Connection: keep-alive
<
{}
```

I think the correct behavior is:

* Return 200 and "{}" in body if there are no executions yet
* Return 404 and no body if the cron does not exist

**Comment by victorcoder** [comment]
Fixed in #136
