### ISSUE TITLE
Running a cronjob on a single dkron agent, while staying still fault-tolerant?

### ISSUE THREAD

**Issue by bveliqi** [victorcoder/dkron#124]
I've set up a dkron cluster of 3 nodes and it's all working fine.

Is there a way to run a cronjob (say execute an HTTP request regularly) on exactly one dkron agent only but let it run on another dkron agent if the previous agent is down for some reason?

**Comment by victorcoder** [comment]
This is what tagging is used for, check http://dkron.io/docs/getting-started/#introduction for one example of running a job on a single node tagged `web` while stating fault tolerant.

**Comment by bveliqi** [comment]
I already did that. I gave every instance a unique tag. However, when i start a job with a tag, so it'll run only on a single machine, the job simply stops running as soon as the machine goes down. Where's the fault-tolerance? Where should the job continue running, if the other agents have other tags only?

**Comment by victorcoder** [comment]
@bveliqi This is a topic that clearly need a dedicated section in the docs.

Explanation:

You have to tag all machines (that you want to use to run the job) with the same tag, say `web`, If you have 3 `web` machines and you want to just run the job in a single machine you have to config the job tags with `web:1` where `1` is the number of machines with that tag you want to use to run the job. If you want to use 2 machines you would need to write `web:2`, etc.

Hope it's clear

**Comment by bveliqi** [comment]
Ah, ok, got it. Works perfectly fine. Thanks a lot!

**Comment by curious12coder1** [comment]
I am trying to write a similar job which makes a http call. Could you please provide me a sample job that makes http calls. I don't know how to run non shell commands.

**Comment by victorcoder** [comment]
@curious12coder1 see my response here https://github.com/victorcoder/dkron/issues/396#issuecomment-399647842

**Comment by sanek640** [comment]
Hi @victorcoder . I have recently started using your service as distributed cron, but now i have a case where i should run certain script separately on my two machines and set up parameters with this script that corresponds with a machine, for example ip of it. I am using tag "role: dkron" in my configuration file and start dkron with "server:true" on each machine and put my script on each machine.
So i have command in my job and tags:
```
"command": "./script.sh {{ inventory_hostname }}",
"tags":
   "role": "dkron: {{ id }}"
```
As you understand i am deploying my jobs with ansible and each hostname and id (number of machine) passing to job via ansible.
I am expecting that on each machine (server:true) jobs will work separately with its own parameters (hostname and dkron:1/dkron:2). I actually see that while deploying, job is acquiring correct variables, but regretfully it is not working as expected. I see jobs on each server through api, but it has wrong variables (the same host passed to each job and tag dkron:2 to both) despite what i saw during deploy.  
Also, script actually running only on the second machine, despite the view of it on the first machine (with wrong variables). For your knowledge i am using one zokeeper for them both, maybe this is the reason.
I hope that i well explain to you my case and you could help me with this problem. Maybe i dont understand your previous explanations of single node mode. 
Thanks

**Comment by victorcoder** [comment]
Hi @sanek640, if I understand the problem correctly, your tagging may be wrong.

Using one store for all server nodes is correct.

`"role": "dkron:1"` Your tagging means, run this job in 1 node with the tag "role=dkron" so it will run in just one node and `"role": "dkron:2"` will try to run in in 2 nodes. That's the node count.

What I will do is: create 2 jobs each one with the corresponding parameters and the specific tags (remember to use the shell executor):
```
"executor": "shell"
"executor_config": {
    "command": "./script.sh {{ inventory_hostname }}"
},
"tags":
   "role": "dkron-{{ id }}"
```
