### ISSUE TITLE
Leadership is not reassigned on graceful exit

### ISSUE THREAD

**Issue by iJanki** [victorcoder/dkron#130]
Hi,

I have been testing dkron a bit and stumbled upon this problem. Don't know if it is a feature or a bug or I am just wrong.

I created a cluster of dkron servers. I tried testing it by killing the server currently assigned as leader, using Ctrl-C. Dkron logs on screen that this is a graceful shutdown of the server but then no new leader is assigned. On the Dkron web dashboard I can see that that server is shown as "left". No new leader is assigned automatically and no jobs run.

However if I repeat the same steps and do a kill -9 on the leader's dkron process, then a new leader is automatically assigned and the old leader is now shown as "failed" on the Dkron web dashboard.

I would like a new leader to be elected regardless of the reason the old one stopped working, is this possible?

Thank you.

**Comment by iJanki** [comment]
I just tried the same test with consul instead of etcd, and it works fine. Leader election happens even after graceful exit of the leader. Weird, maybe some mistake on the setup but we followed your docker-compose example.

**Comment by victorcoder** [comment]
@iJanki do the exited node finish it's execution?

**Comment by iJanki** [comment]
Yes, the node exited gracefully, and no new leader was elected. If I killed -9 it the election started.

**Comment by stephenranjit** [comment]
same issue here. leader election does not happen if I hit ctrl-C
^CCaught signal: interrupt
Gracefully shutting down agent...
INFO[2016-11-14T13:44:54Z] agent: Gracefully shutting down agent...      node=host-one
DEBU[2016-11-14T13:44:54Z] Leader election failed, channel is probably closed  error=<nil> node=host-one
DEBU[2016-11-14T13:44:54Z] scheduler: Stopping scheduler                 node=host-one


need to try with consul. wasted a lot of time trying to fix etcd configuration

**Comment by z1q1q7** [comment]
I have the same problem as iJanki

**Comment by victorcoder** [comment]
I observed this issue in my tests, still debugging and trying to fix it.

**Comment by victorcoder** [comment]
I think this is related to https://github.com/docker/libkv/issues/103#issuecomment-284943212 I'm commited to find a fix for this

**Comment by victorcoder** [comment]
Fixed in #243  Thanks to all for reporting
