### ISSUE TITLE
Multiple backend-machine in dkron.json

### ISSUE THREAD

**Issue by deeweey** [victorcoder/dkron#132]
Hi,

Not sure if the documentation needs an update or if it's a "bug" but I experienced the following.

In dkron.json this works (with a space between the remotes):
"backend_machine": "10.8.0.5:2379, 10.8.0.9:2379",

This doesn't (without a space between the remotes):
"backend_machine": "10.8.0.5:2379,10.8.0.9:2379",

**Comment by victorcoder** [comment]
@deeweey well it's probably a bug, didn't noticed that before.

**Comment by victorcoder** [comment]
It's a documentation error it should be an array in the JSON config file
