### ISSUE TITLE
Purpose of 

### ISSUE THREAD

**Issue by aromm** [victorcoder/dkron#140]
In v0.7.2 you added a new job attribute `shell`; however, I can not seem to determine its purpose. 

I have experimented with `"shell": true` and `"shell": false` and it seems like `"shell": false` just means the command won't run. Seems similar to the `disabled` attribute.

I am sure I am missing something so any help would be great.

**Comment by victorcoder** [comment]
@aromm Sure it needs documentation but if you don't mind reading Go code this function is pretty self explanatory https://github.com/victorcoder/dkron/blob/master/dkron/proc.go#L82-L103
