### ISSUE TITLE
Issues compiling from source

### ISSUE THREAD

**Issue by aromm** [victorcoder/dkron#150]
Hello!

I was having issues with leader nodes occasionally failing the basic serf health check, which often lead to a shutdown of the scheduling, so I wanted to add a feature where a node restarts if its serf health is critical. I downloaded the 0.7.2 release source code (tar.gz), built the program before making changes, ran `dkron agent -server`on one of my servers and for some reason the RPC address is now `127.0.0.1:6868` instead of `<private IP>:6868` like it is on all my nodes that were setup using the .deb.  This is weird to me and breaks the system so I was hoping you had a suggestion on how to fix this. 

Here are the log outputs from the source code compiled node:

```
Starting Dkron agent...
INFO[2016-07-07T02:24:42Z] agent: Dkron agent starting                   node=ip-10-64-0-29
INFO[2016-07-07T02:24:42Z] agent: joining: [cron.service.consul] replay: true  node=ip-10-64-0-29
INFO[2016-07-07T02:24:42Z] agent: joined: 1 nodes                        node=ip-10-64-0-29
DEBU[2016-07-07T02:24:42Z] store: Backend config                         backend=consul keyspace=cron machines=[localhost:8500] node=ip-10-64-0-29
INFO[2016-07-07T02:24:44Z] api: Running HTTP server                      address=:8080 node=ip-10-64-0-29
DEBU[2016-07-07T02:24:44Z] rpc: Registering RPC server                   node=ip-10-64-0-29 rpc_addr=127.0.0.1:6868
INFO[2016-07-07T02:24:44Z] agent: Running for election                   node=ip-10-64-0-29
```

Here are the log outputs from the .deb nodes:

```
Starting Dkron agent...
time="2016-07-07T00:52:42Z" level=info msg="agent: Dkron agent starting" node=ip-10-64-0-27
time="2016-07-07T00:52:42Z" level=info msg="agent: joining: [cron.service.consul] replay: true" node=ip-10-64-0-27
time="2016-07-07T00:52:42Z" level=info msg="agent: joined: 2 nodes" node=ip-10-64-0-27
time="2016-07-07T00:52:42Z" level=debug msg="store: Backend config" backend=consul keyspace=cron machines=[localhost:8500] node=ip-10-64-0-27
time="2016-07-07T00:52:43Z" level=info msg="api: Running HTTP server" address=":8080" node=ip-10-64-0-27
time="2016-07-07T00:52:43Z" level=debug msg="rpc: Registering RPC server" node=ip-10-64-0-27 rpc_addr="10.64.0.27:6868"
time="2016-07-07T00:52:43Z" level=info msg="agent: Running for election" node=ip-10-64-0-27
time="2016-07-07T00:52:43Z" level=info msg="agent: Listen for events" node=ip-10-64-0-27
```

I have been looking through a lot of Dkron code and Serf code but still cannot seem to find when the serf Member.Addr value is set so I cannot figure out why it isnt working.  Also since I obviously cannot look at the source code of the .deb executable I dont know what could be different. 

Thanks for any help you can provide and for your time,
Anthony

**Comment by victorcoder** [comment]
@aromm there should be no difference between the compiled version and the source version. There should be some config difference going on. Could you paste the contents of `/etc/dkron/dkron.json` in both machines?

**Comment by aromm** [comment]
@victorcoder Thanks for the response, especially since this will be helpful in testing #152 . I looked in my config files located in `/etc/dkron/dkron.json` and they are both the same (set by my install script):

```
{
    "backend": "consul",
    "backend_machine": "localhost:8500",
    "server": true,
    "log-level": "debug",
    "tags": {
        "role": "server",
        "datacenter": "us-west-2",
        "os": "ubuntu"
    },
    "keyspace": "cron",
    "encrypt": "<Same encrypt Key on all nodes>",
    "http_addr": ":8080",
    "join": "cron.service.consul"
}
```

Is there a way for me to change this so that all nodes will have the same RPC address?

Also I think I should add that I am not using docker and just realized that there could be an issue with my go package setup, which I am looking into.

Thanks a lot for your help.
