### ISSUE TITLE
Leadership lost and not reassigned if consul fails

### ISSUE THREAD

**Issue by alekitto** [victorcoder/dkron#152]
Hi,

While testing dkron on multiple servers and i've noticed that if consul leader fails and the consul cluster has no leader for a bunch of seconds, the dkron leader immediately lose its leadership (although is still flagged as the leader in the kv store) and jobs do not run.

The log reports:

Server 1 (was leader):
```
time="2016-07-07T11:16:43Z" level=info msg="agent: Cluster leadership lost" node=ip-12-0-1-130
```

Server 2:
```
time="2016-07-07T11:16:54Z" level=info msg="agent: Running for election" node=ip-12-0-1-129
time="2016-07-07T11:16:54Z" level=info msg="agent: Cluster leadership lost" node=ip-12-0-1-129
```

Then no leader is elected until the server 1 is restarted, causing jobs to be lost

I'm using consul v0.6.4 and dkron v0.7.2

Can you help me?

PS: Thanks for your work on this project

**Comment by aromm** [comment]
Same issue here with the same versions. I also found it happens when a node's Serf Health Check fails.

In a hacky attempt to mitigate the loss of jobs, I made a script that restarts the service if the logs arent written for a certain amount of time, which could be useful to you @alekitto.

Thank you for any help!!

**Comment by victorcoder** [comment]
@aromm and @alekitto I noticed a lot of strange behaviour similar o this specially to what @aromm reports, and made some fixes that are not released yet.

https://github.com/victorcoder/dkron/compare/v0.7.2...master

Could you try to use master version and see what happens?

**Comment by alekitto** [comment]
Master version seems fixed: consul lost leadership due to a fail in communication between nodes and leadership of dkron is not lost.

Thanks @victorcoder

**Comment by aromm** [comment]
@victorcoder I can also confirm that now when my serf health check is critical leadership is maintained and there are no outages!

Thank you tons, this was a great improvement too!!

**Comment by victorcoder** [comment]
Basically this was the fix https://github.com/victorcoder/dkron/commit/8c7146fcadd93f48630cbd0de63971d57f263fb6

**Comment by victorcoder** [comment]
https://github.com/victorcoder/dkron/releases/tag/v0.7.3
