### ISSUE TITLE
Serf Health Check issue with v0.7.3

### ISSUE THREAD

**Issue by aromm** [victorcoder/dkron#153]
Hello @victorcoder ,

I have been testing v0.7.3 more and I did experience another problem similar to #152 . The timeline is as follows for a 5 node cluster (all servers with the same configurations and Dkron/consul versions) :

4:10:52 am : Server 1 is leader. Server 1's serf health check becomes critical status according to consul logs. According to Dkron logs at that same moment Server 1 loses cluster leadership. 10 seconds later Server 1 runs for election but loses since Server 2 already acquired leadership 3 seconds earlier. Then jobs are only run on Server 2. None of the other 4 servers log/run anything.

10:36 am : Server 2 gets a 500 response error and restarts. All servers run for election but Server 2 acquires leadership again . This time it schedules to all other machines. and it works fine until the current time. 

This could be a problem with Server 2 having low aws cpu credits (a steady value of 8 about) but I feel like there still should have been communication between all the nodes. Do you have any suggestions on what could be the issue? Is it just an aws credits issue? Im not sure why the other nodes didn't run for election when Server 1 died as well. 

Thank you for all your help with this!

**Comment by victorcoder** [comment]
First: 

> This time it schedules to all other machines. and it works fine until the current time.

What do you mean?

> Im not sure why the other nodes didn't run for election when Server 1 died as well.

I'm pretty sure that the other servers where running for election but Server 2 won the election.

**Comment by aromm** [comment]
Sorry for the late response. On a side note I have not noticed this issue occur again so I am going to close this. Just to clear things up:

> This time it schedules to all other machines. and it works fine until the current time.
Here I meant that after the restart all nodes were running jobs fine even as I was writing the github issue. 

> Im not sure why the other nodes didn't run for election when Server 1 died as well.
Here I meant that none of the other nodes wrote any logs about an election, they just stopped logging or running any jobs. I assumed that since there was no log about an election on the other nodes that they didn't run for election but that might not be correct. 

Either way everything seems great!
Thank you for your time.
