### ISSUE TITLE
JS error when no jobs are registered

### ISSUE THREAD

**Issue by kevana** [victorcoder/dkron#167]
Small error, looks like the dashboard expects an array but the Jobs API endpoint returns null. Before I change anything, which is more idiomatic Go: null or an empty array? 

<img width="366" alt="screen shot 2016-07-29 at 11 51 45 pm" src="https://cloud.githubusercontent.com/assets/981551/17268166/845b703a-55e7-11e6-8cd6-3dd04adea44d.png">

**Comment by victorcoder** [comment]
Thanks for spotting this @kevana, well it's not Go related, it's related to RESTful API design. We have two options:

1. Return a 200 and an empty array
2. Return a 204 NO CONTENT and an empty body

I'll go for 1 at this point, being 2 more appealing to me though, It'll depend on how angular is able to handle a 204.

Let's go for 1.

**Comment by richard-julien** [comment]
+1 for solution one

**Comment by victorcoder** [comment]
Fixed in https://github.com/victorcoder/dkron/issues/217
