### ISSUE TITLE
How to get status of execution

### ISSUE THREAD

**Issue by threestarsgenius** [victorcoder/dkron#171]
Hello, is it possible to know somehow from this request `GET /v1/executions/{execution_job_name}` execution status (success, failed, running etc.)?

Because currently there is only `success: true` or `success: false`

Dkron v0.7.3

**Comment by victorcoder** [comment]
At the moment there's no way to get the status from the API, it will be in the near future though.

You  can read the job status method code to see how you can do that calculation by yourself.

https://github.com/victorcoder/dkron/blob/master/dkron/job.go#L109

**Comment by victorcoder** [comment]
Done in v0.10.0
