### ISSUE TITLE
dkron as a Mesos framework

### ISSUE THREAD

**Issue by janisz** [victorcoder/dkron#174]
Add support for running dkron as a Mesos framework and run scheduled jobs on Mesos Agents.

**Comment by victorcoder** [comment]
Short answer, no. 

Why do you want Dkron run on Mesos if you could use Chronos?

**Comment by janisz** [comment]
Chronos looks like no longer developed. Metronome is going to be it's
successor but it's still pretty new.

pt., 12.08.2016, 16:39 użytkownik Victor Castell <notifications@github.com>
napisał:

**Comment by victorcoder** [comment]
Didn't know Chronos was no longer in develpment, could you please link some reference here?

I don't have plans to make Dkron Mesos compatible, anyway thanks for asking and the info.

**Comment by janisz** [comment]
Thanks for response, please reach me out if Mesos support appear on the road map,  so I can help with implementation. 

According to Chronos End of Life. Take a look at [this thread](https://groups.google.com/a/dcos.io/forum/m/#!msg/users/s4289dyamVw/IvEpROYeCgAJ), [comment](https://github.com/dcos/metronome/issues/90#issuecomment-239430675) and [Chronos repo activity](https://github.com/mesos/chronos/graphs/commit-activity). I think this comment tells everything 

> This is somewhat indelicate, but almost accurate. Chronos was initially developed at AirBnB by Flo (Mesosphere's CEO) and friends (http://nerds.airbnb.com/introducing-chronos/). Unlike Mesos and Spark, Chronos never became an official Apache project (http://www.apache.org/index.html#projects-list). Chronos was migrated to the Mesos github community organization shortly before Mesosphere Inc was founded in 2013. While there's no one official owner, Mesosphere definitely helped improve and maintain Chronos, including it in the "Mesosphere stack" that eventually evolved into DC/OS. That said, there hasn't been much in the way of active Chronos development since about Aug 2015.
> There is an interesting question of "who gets to call an open source project EOL?" Open source projects tend to live for as long as they have committers willing to accept PRs and make releases. As a Mesos community project, I imagine if someone really wanted to keep Chronos on life support they could probably petition for commit access, but Mesosphere wrote Metronome as a replacement, partly to take advantage of lessons learned from Marathon and several of our data service frameworks and partly to integrate into DC/OS, which is itself fully open source. 
> As with all open source, you don't have to buy it outright, but you still need to pay for it with engineering investment or support contracts if you want it to be mission critical to your business.

**Comment by victorcoder** [comment]
@janisz could we get un touch about this topic by email? Cheers!

**Comment by janisz** [comment]
@victorcoder Sure, reach me out at janiszt@gmail.com
