### ISSUE TITLE
How does dkron provide the user impersonation ? 

### ISSUE THREAD

**Issue by gautam20feb** [victorcoder/dkron#177]
I have tried run_as_user configuration parameter in the dkron installation in my cluster but the jobs are always executed as the user who is running the service.

**Comment by victorcoder** [comment]
@gautam20feb this parameter is not documented because it's not implemented. It should be removed. Sorry about the confusion.

**Comment by gautam20feb** [comment]
@victorcoder - Thanks a lot for the information!
