### ISSUE TITLE
database support

### ISSUE THREAD

**Issue by koolay** [victorcoder/dkron#179]
The KV store is  weak for query, would it be possible to support storing data in database, for example mysql, postgres ?

**Comment by victorcoder** [comment]
KV stores are the building blocks for providing HA and leader election capabilities for Dkron, that is not possible using traditional relational Db engines.

**Comment by victorcoder** [comment]
Boltdb is a local KV store and it's not fault tolerant. There's no point in using a non fault tolerant RDBMS as storage engine.
