### ISSUE TITLE
delete localhost/8081/jobs/corn_job error

### ISSUE THREAD

**Issue by twkun** [victorcoder/dkron#18]
I see that file "api.go"
Method: jobDeleteHandler -> a.etcd.Client.Delete(job,false)    no a.etcd.keyspace , so can't delete

i modify this method like this:
a.etcd.Client.Delete(a.etcd.keyspace+"/jobs/"+job,false)

then delete return ok

but my process "dkron2" terminated.

the console show "Key not found /dcron/jobs/corn_job" and "Terminating dkron2

**Comment by victorcoder** [comment]
Thanks, good catch, I'll craft the fix also adding tests
