### ISSUE TITLE
Success and error count and timestamp not recorded

### ISSUE THREAD

**Issue by whizz** [victorcoder/dkron#180]
I upgraded to 0.9.0 and it seems the job statistics are no longer updated. If you create a new job, even when the job runs, the /v1/jobs/JOBNAME endpoint returns this:

...,
"success_count": 0,
"error_count": 0,
"last_success": "0001-01-01T00:00:00Z",
"last_error": "0001-01-01T00:00:00Z",
...

The executions endpoint returns a list of executions fine.

**Comment by whizz** [comment]
After a bit of investigation, the trouble seems to be at https://github.com/victorcoder/dkron/blob/master/dkron/store.go#L72

I'll try to take a stab at fixing it.

**Comment by victorcoder** [comment]
Fixed in #181
