### ISSUE TITLE
Crash when deleting a job

### ISSUE THREAD

**Issue by SamuelHassine** [victorcoder/dkron#182]
Hello,

I just installed the last version of dkron (0.9.0) with the etcd backend. I used the default configuration.

`INFO[2016-09-13T00:16:35+02:00] agent: Dkron agent starting                   node=oxid-master
INFO[2016-09-13T00:16:35+02:00] agent: joining: [] replay: true               node=oxid-master
INFO[2016-09-13T00:16:35+02:00] api: Running HTTP server                      address=:8080 node=oxid-master
INFO[2016-09-13T00:16:35+02:00] agent: Running for election                   node=oxid-master
INFO[2016-09-13T00:16:35+02:00] agent: Listen for events                      node=oxid-master
INFO[2016-09-13T00:16:35+02:00] agent: Cluster leadership lost                node=oxid-master
INFO[2016-09-13T00:16:35+02:00] agent: Cluster leadership acquired            node=oxid-master
`

I created the same job as in the unit tests:

POST /v1/jobs
`{"name": "test_job", "schedule": "@every 2s", "command": "date", "disabled": false}`

The job is working but when I want to delete it:
DELETE /v1/jobs/test_job

The Dkron agent crashed with the following stacktrace:

`panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xa0 pc=0x4893b5]

goroutine 4262 [running]:
panic(0xbb9dc0, 0xc820010110)
    /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/runtime/panic.go:481 +0x3e6
github.com/victorcoder/dkron/dkron.(_AgentCommand).processFilteredNodes(0xc8201501e0, 0x0, 0x0, 0x0, 0x0, 0xc820010f80, 0x0, 0x0)
    /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/agent.go:561 +0xa5
github.com/victorcoder/dkron/dkron.(_AgentCommand).RunQuery(0xc8201501e0, 0xc8202f5b00)
    /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/queries.go:31 +0xd1
github.com/victorcoder/dkron/dkron.(_Job).Run(0xc820166300)
    /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/job.go:98 +0x3c0
created by github.com/victorcoder/dkron/cron.(_Cron).run
    /Users/victorcoder/src/github.com/victorcoder/dkron/cron/cron.go:159 +0x58a
`

I am under Ubuntu 16.04.

Hope it will help you.

Best regards,
Sam

**Comment by richard-julien** [comment]
Same on master branch
