### ISSUE TITLE
Add more information in Job and Execution

### ISSUE THREAD

**Issue by richard-julien** [victorcoder/dkron#189]
# Add scheduled_at field in GET /executions/<job>

When asking for executions info : http://127.0.0.1:8080/v1/executions/test_job
I receive the execution with info

> {
>     "job_name": "test_job",
>     "started_at": "2016-09-15T13:13:02.0030772+02:00",
>     ...
> }

It could be interesting for me to have the original schedule time in order to evaluate the "lag". (

> {
>     "job_name": "test_job",
>     **"scheduled_at": "2016-09-15T13:13:00+02:00",**
>     "started_at": "2016-09-15T13:13:02.0030772+02:00",
>     ...
> }
# Add next_fire_at field in GET /jobs/<job>

It could be interesting to have an evaluation of the next fire schedule date when asking for information about a job

> {
>   "name": "test_job",
>   "schedule": "@every 2m",
>   ...
>   "last_success": "2016-09-15T13:10:52.0625385+02:00",
>   ...
>   "next_fire_time": "2016-09-15T13:12:00+02:00"
> }

If you think it could be interesting, i can try to add it.

**Comment by victorcoder** [comment]
Implemented in #502
