### ISSUE TITLE
Question - Dkron doesn't listen on 8080?

### ISSUE THREAD

**Issue by bdparrish** [victorcoder/dkron#192]
Not sure where to get the log files for Dkron - not in the normal place for `/var/log/`

Where are the logs?  Also, any reason that the tar.gz release would not automatically listen on the default 8080 for the web UI?

**Comment by victorcoder** [comment]
What do you mean, if using the provided debian package to setup dkron the upstart init script place the logs in `/var/log/dkron.log` as specified in the init script https://github.com/victorcoder/dkron/blob/master/debian/etc/init/dkron.conf#L8

 If you use the tar.gz release logs are written to stdout as standard and you are responsible of redirecting the output wherever you need.

The default port for the UI is indeed 8080 https://github.com/victorcoder/dkron/blob/master/dkron/config.go#L79
