### ISSUE TITLE
How to handle multi-environment?

### ISSUE THREAD

**Issue by ssenaria** [victorcoder/dkron#199]
I apologize if this is the wrong forum but I wasn't sure where else to go.

So, we have 2 environments - prod and staging. We trigger deploy commands from a centralize server. I would like to know what best practices are for dealing with multi environment clusters. I want to make sure my prod servers won't accidentally run commands when it shouldn't if someone makes a change to a staging cronjob.

With that said, is there a way to implement some sort of namespace and have all the nodes within the same cluster? What is the "keyspace" option used for? 

Should I have separate "servers" for each cluster; I would need to have HA set up for each cluster? I want to avoid having to create a bunch of servers for HA purposes. In addition, I wouldn't be able to make API calls from my deploy server when I want to interact with the API (unless I open the port). My thought was to throw the deploy servers into the cluster as a dkron server but I wouldn't be able to do this properly if I have multiple clusters.

**Comment by whizz** [comment]
Hi there. I think there are at least two ways to do this. 

a) Separate clusters
We are using dkron together with consul. We have a separate consul cluster for each environment and also a separate dkron cluster. You can quite happily put consul and dkron on the same servers. Dkron and consul will run with just one master node. I wouldn't do that in production, but maybe for staging you'd be OK with that, if you are resource constrained. Make sure you have different encrypt keys for both clusters, so you do not accidentally join them. That way you have the two environments safely isolated.

b) Environment tag
Have just one cluster, but tag the worker servers with an environment tag. Then setup separate jobs for each environment and make them require the correct environment tag. It's more prone to accidentally running the staging job in production though. This is sort of the namespace you are talking about.

The keyspace configuration variable is used to specify a folder name within the underlying key/value store. By changing it you can have multiple dkron clusters being backed by a single k/v store.

**Comment by ssenaria** [comment]
Thanks for the response. Due to resource constraints we can't afford to have a bunch of master nodes (more on that later) for each cluster. Our main stumbling block is how to make the calls to the API from a single node. However, once I started thinking about it, I'm going to have the deploy server submit event handlers to the cluster via Serf's API. Each node has Serf installed and we tag them accordingly. I think we can get away with this without having to expose the HTTP port "publicly" within our LAN.

Quick question, in each environment, our batch servers consist of four servers (I consider this a cluster). What's stopping me from having all four act as servers and not agents? We're doing green/blue deployments and each group consist of two servers. I plan on enabling the cronjobs to run against a particular group (eg. "cluster_id": "green:1") using tags. The cron can only run against two of the four servers at any given time. Is there a reason why I would want one master node?

**Comment by whizz** [comment]
Dkron servers act as agents too, so there is no problem with having all the members of your cluster be servers. One of them gets elected as a leader and does all the scheduling. The others are on "standby" but can run the jobs.
