### ISSUE TITLE
How to run cronjob as a different user?

### ISSUE THREAD

**Issue by ssenaria** [victorcoder/dkron#203]
We have some jobs that needs to run as a non-root user, specially our application user. I found an old ticket, which referenced `run_as_user` and it doesn't appear to be working. Is there another way for me to do this?

**Comment by victorcoder** [comment]
I've never tried It TBH but as dkron runs as root you can use `su -l user -c` in a shell job.

**Comment by ssenaria** [comment]
Interesting, that does seem to work. I'm still having issues with the environment files as mentioned in my other ticket.

**Comment by victorcoder** [comment]
I just checked it and this is working well for me. What dkron version are you using?

**Comment by ssenaria** [comment]
0.9.0

**Comment by victorcoder** [comment]
please, could you paste the command you're using?
