### ISSUE TITLE
Leader lockup with Consul backing?

### ISSUE THREAD

**Issue by greggilbert** [victorcoder/dkron#204]
We've been seeing an issue in our dkron setup the last few days where jobs stop running. As best as I can tell from the logs, the leader loses its leadership but the leader key remains in Consul. After that, none of the nodes running dkron write any further logs, and everything just locks. The situation is solved by restarting dkron on the node that has the lock.

Unfortunately I don't have much more information than that, but I was wondering if anyone has seen this issue before, and if there are any fixes for it. For reference this was in 0.7.1; I've tried updating one of my nodes to 0.9.1 but hit the issue in #202.

**Comment by victorcoder** [comment]
Fixed in recent versions
