### ISSUE TITLE
Run agent in background

### ISSUE THREAD

**Issue by ProPheT777** [victorcoder/dkron#206]
There is no way to pass an argument (like -d for example) to dkron agent in order to run as daemon instead of foreground? 

It's convenient than using '&'

**Comment by victorcoder** [comment]
Hi @ProPheT777 there's no support for running in background aside from using `&` dkron is intended to be executed as a system service, using a daemon supervisor like upstart, systemd, etc.

Could you explain a bit more your use case?

**Comment by ProPheT777** [comment]
There is no specific use case, I mean, it's just more frendly to use an option to run it in background because it's a daemon by fact. So I was surprised to not see a built in option to do that. Moreover the agent is run inside docker container (for my use case) and I dont need supervisord, systemctl or upstart because it's supposed to be fault tolerant. 

Currently i'm doing via '&' and it's fine, but provide a built in option is better I think (More ready to use).

**Comment by victorcoder** [comment]
@ProPheT777 running in background nowadays, specially with docker, it's not a good practice. You should consider that it's easier for service development and for production usage. 

I recommend you a very interesting blog post on this topic http://www.mikeperham.com/2014/09/22/dont-daemonize-your-daemons/ for the advantages of not doing that.

Anyway, this is just opinion, any modern system supervisor will allow you to run in background, so I choose not to implement that.
