### ISSUE TITLE
leader does not re-elect

### ISSUE THREAD

**Issue by z1q1q7** [victorcoder/dkron#208]
I'm confused about the leader in a cluster.
I have 3 nodes, one run as server, other two as agents.
When server goes down(I kill it by myself), there is no election between left two.
Should the other two started as servers? When I do this, cannot start.

**Comment by victorcoder** [comment]
Yes @z1q1q7, the leader election only happens between those that are started as servers. 

You say cannot start, could you paste the relevant log output?

**Comment by z1q1q7** [comment]
@victorcoder so sorry for late.
Should I start all agents as servers ? 
I can't start others as servers if one started as server.
fatal error like this:
FATA[2016-11-29T20:14:08+08:00] store: Store backend not reachable            error=client: etcd cluster is unavailable or misconfigured
As a matter of fact, I can telnet the backend machine.

**Comment by z1q1q7** [comment]
I find the source code, it's keyspace error.
I have another problem. If leader leaves, I cannot get leader from restapi of old leader ?
When leader machine recovers, I get different leader from different restapi.

**Comment by victorcoder** [comment]
@z1q1q7 no you can not or if you can you shouldn't trust the old leader. It's normal that you get a different leader as a new one has been elected after the old one left.
