### ISSUE TITLE
Use DELETE or POST http verb for /leave API endpoint

### ISSUE THREAD

**Issue by kevana** [victorcoder/dkron#210]
`GET` requests shouldn't cause side effects such as modifying cluster membership. I suggest using `DELETE` or `POST` to make clear that the leave endpoint is not a [safe operation](https://tools.ietf.org/html/rfc7231#section-4.2.1). I believe this change would require a version bump for the API.

[Source to change](https://github.com/victorcoder/dkron/blob/master/dkron/api.go#L55)

Thoughts?

**Comment by victorcoder** [comment]
Good catch @kevana, it should be changed. As we're in pre final release here, the best option I see is to maintain the old method giving a deprecation message as WARNING in log output and add the new verb.
