### ISSUE TITLE
Docker version tag

### ISSUE THREAD

**Issue by FallenRiteMonk** [victorcoder/dkron#211]
would it be possible to have docker versions tag same as tags on repository?
as far as i can see it should be as simple as to add a build to the build settings in docker hub. just add a new one, set type to tag and leave the rest as it is.

I know the project is still in some kind of beta and it would be best to keep everything up to date, but i personally prefer to have fixed version on all my docker containers in my production environment.

**Comment by victorcoder** [comment]
Sure! done, thanks @FallenRiteMonk

**Comment by FallenRiteMonk** [comment]
Thanks
