### ISSUE TITLE
no new leader election after LEAVE from REST Api

### ISSUE THREAD

**Issue by stephenranjit** [victorcoder/dkron#213]
host07 and host08 are running with -server switch.
this is my config:

`{
  "debug": true,
  "backend": "zk",
  "backend_machine": [
    "host07:2181",
    "host08:2181",
    "host09:2181"
  ],
  "tags": {
    "datacenter": "SVL",
    "type": "cron"
  },
  "join": [
    "host07",
    "host08",
    "host09"
  ],
  "keyspace": "dkron",
  "mail_host": "",
  "mail_port": 25,
  "mail_from": ""

}
`

I'm simply calling /LEAVE on the leader like this:
`/usr/software/bin/curl -m 2 -s -XGET http://host07:8080/v1/leave`

serf recognizes the leave event. but re-election does not happen after that.

`DEBU[2016-11-30T00:36:00-08:00] agent: Received event                         event=member-leave node=host07
DEBU[2016-11-30T00:36:00-08:00] agent: Member event                           event=member-leave member=host07 node=host07

DEBU[2016-11-30T00:36:14-08:00] store: Retrieved leader from datastore        node=host07
DEBU[2016-11-30T00:36:15-08:00] store: Retrieved leader from datastore        node=host07
DEBU[2016-11-30T00:36:16-08:00] store: Retrieved leader from datastore        node=host07
`
`rest_cmd: /usr/software/bin/curl -m 2 -s -XGET http://host07:8080/v1/leader?pretty
rest_cmd_response: {
        "Name": "host07",
        "Addr": "1.1.1.1",
        "Port": 8946,
        "Tags": {
                "datacenter": "SVL",
                "dkron_server": "true",
                "dkron_version": "0.9.1",
                "type": "cron"
        },
        "Status": 3,
        "ProtocolMin": 1,
        "ProtocolMax": 2,
        "ProtocolCur": 2,
        "DelegateMin": 2,
        "DelegateMax": 4,
        "DelegateCur": 4
}
`
also http://host07:8080/dashboard/jobs does not show created jobs after leader leave. throws this error:

`2016/11/30 00:45:42 http: panic serving 2.2.2.2:51234: runtime error: index out of range
goroutine 114 [running]:
net/http.(*conn).serve.func1(0xc820184100)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/net/http/server.go:1389 +0xc1
panic(0xbb9dc0, 0xc8200100b0)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/runtime/panic.go:443 +0x4e9
text/template.errRecover(0xc8207bb6d0)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/text/template/exec.go:133 +0xee
panic(0xbb9dc0, 0xc8200100b0)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/runtime/panic.go:443 +0x4e9
github.com/victorcoder/dkron/dkron.(*Store).GetLastExecutionGroup(0xc820226140, 0xc820228040, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/store.go:276 +0x3c6
github.com/victorcoder/dkron/dkron.(*Job).Status(0xc8201a4000, 0x0)
        /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/job.go:115 +0x5f
github.com/victorcoder/dkron/dkron.(*AgentCommand).dashboardJobsHandler.func1(0xc8201a4000, 0x0, 0x0)
        /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/dashboard.go:91 +0x31
reflect.Value.call(0xa69ca0, 0xe74450, 0x13, 0xce4de8, 0x4, 0xc820854800, 0x1, 0x1, 0x0, 0x0, ...)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0xa69ca0, 0xe74450, 0x13, 0xc820854800, 0x1, 0x1, 0x0, 0x0, 0x0)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/reflect/value.go:303 +0xb1
text/template.(*state).evalCall(0xc8207bb290, 0xc29d60, 0xc8202de020, 0x196, 0xa69ca0, 0xe74450, 0x13, 0x7f51c0a97870, 0xc820a22270, 0xc82015aaaa, ...)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/text/template/exec.go:641 +0xb39
text/template.(*state).evalFunction(0xc8207bb290, 0xc29d60, 0xc8202de020, 0x196, 0xc820a222a0, 0x7f51c0a97870, 0xc820a22270, 0xc82019c880, 0x2, 0x2, ...)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/text/template/exec.go:515 +0x336
text/template.(*state).evalCommand(0xc8207bb290, 0xc29d60, 0xc8202de020, 0x196, 0xc820a22270, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/text/template/exec.go:412 +0x1e9
text/template.(*state).evalPipeline(0xc8207bb290, 0xc29d60, 0xc8202de020, 0x196, 0xc820182f00, 0x0, 0x0, 0x0)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/text/template/exec.go:385 +0x180
text/template.(*state).walk(0xc8207bb290, 0xc29d60, 0xc8202de020, 0x196, 0x7f51c0b14870, 0xc820a22300)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/text/template/exec.go:215 +0x135
text/template.(*state).walk(0xc8207bb290, 0xc29d60, 0xc8202de020, 0x196, 0x7f51c0a97798, 0xc820a221e0)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/text/template/exec.go:223 +0x6a1
text/template.(*state).walkIfOrWith(0xc8207bb290, 0xa, 0xc29d60, 0xc8202de020, 0x196, 0xc820182eb0, 0xc820a22180, 0xc820a221e0)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/text/template/exec.go:256 +0x3ff
text/template.(*state).walk(0xc8207bb290, 0xc29d60, 0xc8202de020, 0x196, 0x7f51c0a97948, 0xc8201a1280)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/text/template/exec.go:220 +0x4d9
text/template.(*state).walk(0xc8207bb290, 0xc29d60, 0xc8202de020, 0x196, 0x7f51c0a97798, 0xc82029dc50)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/text/template/exec.go:223 +0x6a1
text/template.(*state).walkRange.func1(0xa3ca20, 0xc820229b40, 0x82, 0xc29d60, 0xc8202de020, 0x196)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/text/template/exec.go:310 +0x202
text/template.(*state).walkRange(0xc8207bb290, 0xb926c0, 0xc82019ca60, 0x99, 0xc820122000)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/text/template/exec.go:319 +0x465
text/template.(*state).walk(0xc8207bb290, 0xb926c0, 0xc82019ca60, 0x99, 0x7f51c0b14900, 0xc820122000)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/text/template/exec.go:226 +0x264
text/template.(*state).walk(0xc8207bb290, 0xb926c0, 0xc82019ca60, 0x99, 0x7f51c0a97798, 0xc82029db00)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/text/template/exec.go:223 +0x6a1
text/template.(*state).walkTemplate(0xc8207bb660, 0xb926c0, 0xc82019ca60, 0x99, 0xc8201a0e40)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/text/template/exec.go:368 +0x410
text/template.(*state).walk(0xc8207bb660, 0xb926c0, 0xc82019ca60, 0x99, 0x7f51c0a97750, 0xc8201a0e40)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/text/template/exec.go:228 +0x5b7
text/template.(*state).walk(0xc8207bb660, 0xb926c0, 0xc82019ca60, 0x99, 0x7f51c0a97798, 0xc82029c240)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/text/template/exec.go:223 +0x6a1
text/template.(*Template).Execute(0xc8201a0c00, 0x7f51c0a963f8, 0xc82017eb60, 0xb926c0, 0xc82019ca60, 0x0, 0x0)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/text/template/exec.go:178 +0x2a7
html/template.(*Template).Execute(0xc82029c1b0, 0x7f51c0a963f8, 0xc82017eb60, 0xb926c0, 0xc82019ca60, 0x0, 0x0)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/html/template/template.go:104 +0x9a
github.com/victorcoder/dkron/dkron.(*AgentCommand).dashboardJobsHandler(0xc82009c420, 0x7f51c0ad69f8, 0xc82017eb60, 0xc8203469a0)
        /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/dashboard.go:122 +0x72e
github.com/victorcoder/dkron/dkron.(*AgentCommand).(github.com/victorcoder/dkron/dkron.dashboardJobsHandler)-fm(0x7f51c0ad69f8, 0xc82017eb60, 0xc8203469a0)
        /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/dashboard.go:50 +0x3e
net/http.HandlerFunc.ServeHTTP(0xc82068fcd0, 0x7f51c0ad69f8, 0xc82017eb60, 0xc8203469a0)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/net/http/server.go:1618 +0x3a
github.com/victorcoder/dkron/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc8201822d0, 0x7f51c0ad69f8, 0xc82017eb60, 0xc8203469a0)
        /Users/victorcoder/src/github.com/victorcoder/dkron/vendor/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/victorcoder/dkron/vendor/github.com/carbocation/interpose.(*Middleware).UseHandler.func1.1(0x7f51c0ad69f8, 0xc82017eb60, 0xc8203469a0)
        /Users/victorcoder/src/github.com/victorcoder/dkron/vendor/github.com/carbocation/interpose/interpose.go:55 +0x69
net/http.HandlerFunc.ServeHTTP(0xc8202c5a40, 0x7f51c0ad69f8, 0xc82017eb60, 0xc8203469a0)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/net/http/server.go:1618 +0x3a
github.com/victorcoder/dkron/dkron.metaMiddleware.func1.1(0x7f51c0ad69f8, 0xc82017eb60, 0xc8203469a0)
        /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/api.go:78 +0x1ac
net/http.HandlerFunc.ServeHTTP(0xc8202c5a70, 0x7f51c0ad69f8, 0xc82017eb60, 0xc8203469a0)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/net/http/server.go:1618 +0x3a
github.com/victorcoder/dkron/vendor/github.com/carbocation/interpose.(*Middleware).ServeHTTP(0xc82016bc20, 0x7f51c0ad69f8, 0xc82017eb60, 0xc8203469a0)
        /Users/victorcoder/src/github.com/victorcoder/dkron/vendor/github.com/carbocation/interpose/interpose.go:85 +0x6c
net/http.serverHandler.ServeHTTP(0xc820302a00, 0x7f51c0ad69f8, 0xc82017eb60, 0xc8203469a0)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820184100)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/net/http/server.go:2137 +0x44e
`

Any help would be appreciated

**Comment by victorcoder** [comment]
The `/leave` method it's not what you think it is, probably bad documented and confusing name. 

The `/leave` method just forces the node to leave the serf cluster but not to step down in the leader election.

For what do you want to use the leave method?

**Comment by stephenranjit** [comment]
ok. so the leader re-election will not happen. thanks for clarifying. What about the leader dashboard? will that stop working too? is that intentional?

**Comment by victorcoder** [comment]
Probably the leave method is confusing at this point and needs more work.

The dashboard it's not affected but the node won't be eligible to run jobs in it.
