### ISSUE TITLE
Cluster missing executions - "dial tcp: missing address"

### ISSUE THREAD

**Issue by alexef** [victorcoder/dkron#237]
# My Setup

5 dkron servers, 2 dkron runners. 

Using Consul as the data store.

# Problem

From time to time, randomly, I see in the runners log:

> time="2017-02-01T11:39:30+01:00" level=info msg="agent: Starting job" job="cjms_fetch" node=watcher11 
> time="2017-02-01T11:39:34+01:00" level=error msg="rpc: error dialing." err="dial tcp: missing address" node=watcher11 server_addr= 
> time="2017-02-01T11:39:34+01:00" level=error msg="agent: Error invoking job command" error="dial tcp: missing address" node=watcher11 
> time="2017-02-01T11:40:30+01:00" level=info msg="agent: Starting job" job="cjms_check" node=watcher11 

In the execution history, we just see the started and no output:

<img width="1169" alt="screen shot 2017-02-01 at 12 58 23" src="https://cloud.githubusercontent.com/assets/346576/22505963/353a9592-e87e-11e6-8df3-861c20229a30.png">

**Comment by victorcoder** [comment]
Hi @alexef thanks for reporting, I haven't seen this error before, I'm guessing that some of the servers could be out of the serf cluster.

Could you paste here the output of `/v1/members` of the node?

**Comment by alexef** [comment]
```[
	{
		"Name": "watcher10",
		"Addr": "x.x.x.x",
		"Port": 8946,
		"Tags": {
			"dkron_version": "0.9.3-b1",
			"environment": "production",
			"role": "watcher"
		},
		"Status": 1,
		"ProtocolMin": 1,
		"ProtocolMax": 2,
		"ProtocolCur": 2,
		"DelegateMin": 2,
		"DelegateMax": 4,
		"DelegateCur": 4
	},
	{
		"Name": "worker11",
		"Addr": "x.x.x.x",
		"Port": 8946,
		"Tags": {
			"dkron_version": "0.9.3-b1",
			"environment": "production",
			"role": "worker"
		},
		"Status": 1,
		"ProtocolMin": 1,
		"ProtocolMax": 2,
		"ProtocolCur": 2,
		"DelegateMin": 2,
		"DelegateMax": 4,
		"DelegateCur": 4
	},
	{
		"Name": "pillar14",
		"Addr": "x.x.x.x",
		"Port": 8946,
		"Tags": {
			"dkron_server": "true",
			"dkron_version": "0.9.3-b1",
			"environment": "production",
			"role": "pillar"
		},
		"Status": 1,
		"ProtocolMin": 1,
		"ProtocolMax": 2,
		"ProtocolCur": 2,
		"DelegateMin": 2,
		"DelegateMax": 4,
		"DelegateCur": 4
	},
	{
		"Name": "watcher11",
		"Addr": "x.x.x.x",
		"Port": 8946,
		"Tags": {
			"dkron_version": "0.9.3-b1",
			"environment": "production",
			"role": "watcher"
		},
		"Status": 1,
		"ProtocolMin": 1,
		"ProtocolMax": 2,
		"ProtocolCur": 2,
		"DelegateMin": 2,
		"DelegateMax": 4,
		"DelegateCur": 4
	},
	{
		"Name": "pillar18",
		"Addr": "x.x.x.x",
		"Port": 8946,
		"Tags": {
			"dkron_server": "true",
			"dkron_version": "0.9.3-b1",
			"environment": "production",
			"role": "pillar"
		},
		"Status": 1,
		"ProtocolMin": 1,
		"ProtocolMax": 2,
		"ProtocolCur": 2,
		"DelegateMin": 2,
		"DelegateMax": 4,
		"DelegateCur": 4
	},
	{
		"Name": "worker10",
		"Addr": "x.x.x.x",
		"Port": 8946,
		"Tags": {
			"dkron_version": "0.9.3-b1",
			"environment": "production",
			"role": "worker"
		},
		"Status": 1,
		"ProtocolMin": 1,
		"ProtocolMax": 2,
		"ProtocolCur": 2,
		"DelegateMin": 2,
		"DelegateMax": 4,
		"DelegateCur": 4
	},
	{
		"Name": "pillar17",
		"Addr": "x.x.x.x",
		"Port": 8946,
		"Tags": {
			"dkron_server": "true",
			"dkron_version": "0.9.3-b1",
			"environment": "production",
			"role": "pillar"
		},
		"Status": 1,
		"ProtocolMin": 1,
		"ProtocolMax": 2,
		"ProtocolCur": 2,
		"DelegateMin": 2,
		"DelegateMax": 4,
		"DelegateCur": 4
	}
]```

**Comment by alexef** [comment]
Hi,

This happened again today, and the job was left in executing state. No other job started, since the concurrency was set to forbid.

Output of members:
```
[
	{
		"Name": "worker11",
		"Addr": "10.81.25.63",
		"Port": 8946,
		"Tags": {
			"dkron_version": "0.9.3-b1",
			"environment": "production",
			"role": "worker"
		},
		"Status": 1,
		"ProtocolMin": 1,
		"ProtocolMax": 2,
		"ProtocolCur": 2,
		"DelegateMin": 2,
		"DelegateMax": 4,
		"DelegateCur": 4
	},
	{
		"Name": "pillar17",
		"Addr": "10.81.13.176",
		"Port": 8946,
		"Tags": {
			"dkron_server": "true",
			"dkron_version": "0.9.3-b1",
			"environment": "production",
			"role": "pillar"
		},
		"Status": 1,
		"ProtocolMin": 1,
		"ProtocolMax": 2,
		"ProtocolCur": 2,
		"DelegateMin": 2,
		"DelegateMax": 4,
		"DelegateCur": 4
	},
	{
		"Name": "pillar14",
		"Addr": "10.81.10.40",
		"Port": 8946,
		"Tags": {
			"dkron_server": "true",
			"dkron_version": "0.9.3-b1",
			"environment": "production",
			"role": "pillar"
		},
		"Status": 1,
		"ProtocolMin": 1,
		"ProtocolMax": 2,
		"ProtocolCur": 2,
		"DelegateMin": 2,
		"DelegateMax": 4,
		"DelegateCur": 4
	},
	{
		"Name": "watcher11",
		"Addr": "10.81.23.33",
		"Port": 8946,
		"Tags": {
			"dkron_version": "0.9.3-b1",
			"environment": "production",
			"role": "watcher"
		},
		"Status": 1,
		"ProtocolMin": 1,
		"ProtocolMax": 2,
		"ProtocolCur": 2,
		"DelegateMin": 2,
		"DelegateMax": 4,
		"DelegateCur": 4
	},
	{
		"Name": "pillar15",
		"Addr": "10.81.24.227",
		"Port": 8946,
		"Tags": {
			"dkron_server": "true",
			"dkron_version": "0.9.3-b1",
			"environment": "production",
			"role": "pillar"
		},
		"Status": 1,
		"ProtocolMin": 1,
		"ProtocolMax": 2,
		"ProtocolCur": 2,
		"DelegateMin": 2,
		"DelegateMax": 4,
		"DelegateCur": 4
	},
	{
		"Name": "pillar18",
		"Addr": "10.81.19.9",
		"Port": 8946,
		"Tags": {
			"dkron_server": "true",
			"dkron_version": "0.9.3-b1",
			"environment": "production",
			"role": "pillar"
		},
		"Status": 1,
		"ProtocolMin": 1,
		"ProtocolMax": 2,
		"ProtocolCur": 2,
		"DelegateMin": 2,
		"DelegateMax": 4,
		"DelegateCur": 4
	},
	{
		"Name": "worker10",
		"Addr": "10.81.9.199",
		"Port": 8946,
		"Tags": {
			"dkron_version": "0.9.3-b1",
			"environment": "production",
			"role": "worker"
		},
		"Status": 1,
		"ProtocolMin": 1,
		"ProtocolMax": 2,
		"ProtocolCur": 2,
		"DelegateMin": 2,
		"DelegateMax": 4,
		"DelegateCur": 4
	},
	{
		"Name": "watcher10",
		"Addr": "10.81.9.103",
		"Port": 8946,
		"Tags": {
			"dkron_version": "0.9.3-b1",
			"environment": "production",
			"role": "watcher"
		},
		"Status": 1,
		"ProtocolMin": 1,
		"ProtocolMax": 2,
		"ProtocolCur": 2,
		"DelegateMin": 2,
		"DelegateMax": 4,
		"DelegateCur": 4
	}
]```

**Comment by victorcoder** [comment]
Thanks for the good reporting @alexef.

I see the error it's clearly in the call to https://github.com/victorcoder/dkron/blob/v0.9.3/dkron/agent.go#L647

RPC port seems that is totally blank and at least it should be the default one.

I see that your're running the beta version, I'll add some tracing info to the `getRPCAddr` method and an error control code there.

I'll compile a new beta version for you to try, let's see if that help us to spot the error.

The weird thing is that the leader member of the cluster seems to not have any address at all from the serf point of view.

Which is the current leader?

**Comment by alexef** [comment]
The current leader is `pillar17`, and it did not lose leadership lately.

If this helps debugging, I've only seen the error while using the `forbid` concurrency policy (now I've changed to `allow`, but I would like to be able to switch back to forbid). Also, it may be that with `allow`, the error are just hidden.

**Comment by damagedcode** [comment]
I get the same problem, when dkron agent(server) run some time, queryRPCConfig and RunQuery, give a server address without rpc port. And i saw a HUP SIG in a agent. I post a #262 try to fix lost configurtion, when get HUP SIG

**Comment by stephenranjit** [comment]
Any workaround to this? I think its the same problem here:

`time="2017-05-24T16:00:00-07:00" level=debug msg="scheduler: Run job" job=<job_name> node=<machine_name> schedule="00 00 16 * * *"
time="2017-05-24T16:00:00-07:00" level=debug msg="store: Retrieved job from datastore" job=<job_name> node=<machine_name>
time="2017-05-24T16:00:00-07:00" level=debug msg="agent: Filtered nodes to run: [<machine_name>]" node=<machine_name>
time="2017-05-24T16:00:00-07:00" level=debug msg="agent: Filtered tags to run: map[type:cron:1]" node=<machine_name>
time="2017-05-24T16:00:00-07:00" level=debug msg="agent: Sending query" job_name=<job_name> json="{\"execution\":{\"job_name\":\"<job_name>\",\"started_at\":\"0001-01-01T00:00:00Z\",\"finished_at\":\"0001-01-01T00:00:00Z\",\"group\":1495666800000560623,\"attempt\":1},\"rpc_addr\":\"<ip_address>:0\"}" node=<machine_name> query="run:job"
time="2017-05-24T16:00:00-07:00" level=debug msg="agent: Received event" event="query: run:job" node=<machine_name>
time="2017-05-24T16:00:00-07:00" level=debug msg="agent: Received ack" from=<machine_name> node=<machine_name> query="run:job"
time="2017-05-24T16:00:00-07:00" level=debug msg="agent: Running job" at=81 node=<machine_name> payload="{\"execution\":{\"job_name\":\"<job_name>\",\"started_at\":\"0001-01-01T00:00:00Z\",\"finished_at\":\"0001-01-01T00:00:00Z\",\"group\":1495666800000560623,\"attempt\":1},\"rpc_addr\":\"<ip_address>:0\"}" query="run:job"
time="2017-05-24T16:00:00-07:00" level=info msg="agent: Starting job" job=<job_name> node=<machine_name>
time="2017-05-24T16:00:00-07:00" level=error msg="rpc: error dialing." err="dial tcp <ip_address>:0: getsockopt: connection refused" node=<machine_name>server_addr="<ip_address>:0"
time="2017-05-24T16:00:00-07:00" level=error msg="agent: Error on rpc.GetJob call" error="dial tcp <ip_address>:0: getsockopt: connection refused" node=<machine_name>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x960739]

goroutine 163 [running]:
github.com/victorcoder/dkron/dkron.(*AgentCommand).eventLoop(0xc420346770)
    /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/agent.go:525 +0x1419
created by github.com/victorcoder/dkron/dkron.(*AgentCommand).Run
    /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/agent.go:320 +0x15b`

**Comment by victorcoder** [comment]
@damagedcode Thanks for making the point in SIGHUP.

@alexef @stephenranjit Could it be that you are sending SIGHUP to reload config before the error appeared?

**Comment by alexef** [comment]
@victorcoder I've checked, I'm not sending SIGHUP to dkron neither directly or indirectly.

**Comment by stephenranjit** [comment]
UPDATE: I've moved my setup to different hosts and dkron has been running without issues for 15 days. Previously something or someone was killing the processes or rebooting the servers without warning. These new servers are isolated. I will report back if I hit this issue again. Thanks.

**Comment by johnnyjian** [comment]
We have the same issue:

> time="2017-07-13T18:06:31+08:00" level=error msg="rpc: error dialing." err="dial tcp: missing address" node=xxx server_addr=

My guess is AgentCommand.queryRPCConfig() does not handle errors correctly and return an empty rpcAddr. IMO, it should retry if rpcAddr is empty.

**Comment by Zophren** [comment]
Hello,

> We have also the issue:14/03/2018 17:43:16ERRO[2018-03-14T17:43:16+01:00] agent: Error invoking job command             error="dial tcp: missing address" node=2fbae74ff1bf

Is it possible to check #336 ?
