### ISSUE TITLE
Real-world availability and general concerns

### ISSUE THREAD

**Issue by 0xABAB** [victorcoder/dkron#242]
> You can use Dkron to run the most important part of your company, scheduled jobs.

Given the six open issues marked as bugs (some of which seem catastrophic at first sight), how valid is this assertion? How many 9s of availability do you actually reach in practice (please provide number of the number of nodes and what type of network there is (e.g. dedicated/cloud environment/....))? 

Single machine solutions have some inherent stability issues, but it appears that the complexity introduced by using fancy distributed systems is not worth it, *unless* the quality of the implementation is high. 

The architecture of dkron seems sound, but how should the world regard dkron? Is this something for which you would want to be contractually bound to meet certain availability numbers like 99.99% (not counting external factors like power outages, etc.)?

How many "real" users does it have? (I.e., users for which downtime is actually going to cost a lot of money. )

How much time do you need to babysit the system? (In the reported issues I see people talking about "restarting the service" (which counts as babysitting).)

I am considering dkron for a serious application, but the open issues seem pretty grave. 

Another relevant question is why you specifically would be the right person to implement a tool like dkron. Do you have any credentials or experience which make you specifically suited to implement this particular program?

Finally, what testing has been done with the explicit goal of trying to destroy all the properties you think it has (cf. https://aphyr.com/tags/jepsen)? It's quite likely that the "happy path" works fine, but the value from a tool like dkron comes from what happens under weird conditions. For example, I read somewhere that if there is a zookeeper cluster with N nodes and only one node (the one that dkron was connected to) disconnects, that's considered a complete failure by dkron. I am not sure how such behaviour can be consistent with the quote above.

**Comment by victorcoder** [comment]
Refer to https://github.com/victorcoder/dkron#status

Use it under your own discretion
