### ISSUE TITLE
Admin Tasks

### ISSUE THREAD

**Issue by caiovmv** [victorcoder/dkron#245]
I have tried running jobs every 30 seconds, but found that the scheduler minimum time is ticking in 1 minute, this behavior is true ?, if so how can I change that ?

The second ask is about a way to remove jobs by rest api or somehow. I guess by passing a list with job_names to a endpoint or even a endpoint with filter like "errors_count < 10". I ask it because I'm talking about a lot of jobs that I need to remove like 1.000 periodically or adhoc. 

There is any way to make a clean reset ? I thing it is a good thing to be in mind.

**Comment by victorcoder** [comment]
Hi @caiovmv, the minimum granularity of a job in dkron is 1s. I think it's mentioned somewhere in the docs, but sorry I can't find it now. Check the cron spec format http://dkron.io/docs/guides/#cron-expression-format it's a bit different from standard cron.

Sure, you have the `DELETE /jobs/{job_name}` method it's in the API docs, http://dkron.io/docs/api/#paths (no very useful doc I must say), no filters, you need to remove the jobs one by one given the name. But you can automate it.

At the moment the only way to do a clean reset I can think of, is by removing the storage data.
