### ISSUE TITLE
Support shell syntax and expressions in command execution

### ISSUE THREAD

**Issue by sokoow** [victorcoder/dkron#246]
I'm trying to do the following:

```
curl -XPOST -d'{"name":"desktop_backup","command":"borg create --stats --progress --compression lz4 /home/sokoow/Documents/repo::backup$(date +%s) ~/Desktop", "schedule":"@every 15s"}' localhost:8080/v1/jobs
```

but dkron doesn't seem to evaluate the bash dollar expression ```$(date +%s)``` correctly. I get two executions out of it:
```
Archive backup$(date alre... and 
+%s): [Errno 2] No such f...
```

Help please ? :)

**Comment by m1r4ge** [comment]
Have you tried to specify "shell": true, when you create a job?

**Comment by sokoow** [comment]
I can try that in a moment. Right now my workaround is to pack my command in a shell script, that works fine.

**Comment by sokoow** [comment]
Ok, adding shell:true works, thanks :)

**Comment by m1r4ge** [comment]
You are welcome ;)
