### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by kiterminal** [victorcoder/dkron#250]
Hi all,

I am in the middle of prove of concept for high availability job scheduling, which dkron has come across, initially I did try to setup dkron with etcd backend on 2 vms machine,dkron-node-01 and dkron-node-02, detailed here:-
- 2 vms (each has 1 VCPU, 4GB RAM, Oracle Linux 7) 
- deployed with dkron 0.9.3 on both machines
- deployed with etcd cluster 3.1.4 on both machines
- has 1 job which will basically execute the jar file within every minute interval

The job looks well and execution has been scheduled and properly run for a while. Unfortunately, there is an abrupt termination of dkron process, and raised panic level log as **panic: runtime error: invalid memory address or nil pointer dereference** The detailed log could be found here:-

```
time="2017-04-03T05:38:13Z" level=warning msg="rpc: Error calling GetJob" error="client: etcd cluster is unavailable or misconfigured" node=dkron-node-01
time="2017-04-03T05:38:13Z" level=error msg="agent: Error on rpc.GetJob call" error="client: etcd cluster is unavailable or misconfigured" node=dkron-node-01
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x960739]

goroutine 357963 [running]:
github.com/victorcoder/dkron/dkron.(*AgentCommand).processFilteredNodes(0xc4201a6a80, 0x0, 0x18, 0x0, 0xe2b2a0, 0xc422dc0740, 0x2, 0x5)
	/Users/victorcoder/src/github.com/victorcoder/dkron/dkron/agent.go:591 +0x72
github.com/victorcoder/dkron/dkron.(*AgentCommand).RunQuery(0xc4201a6a80, 0xc42004ed00)
	/Users/victorcoder/src/github.com/victorcoder/dkron/dkron/queries.go:39 +0xe9
github.com/victorcoder/dkron/dkron.(*Job).Run(0xc423469200)
	/Users/victorcoder/src/github.com/victorcoder/dkron/dkron/job.go:110 +0x344
created by github.com/victorcoder/dkron/cron.(*Cron).run
	/Users/victorcoder/src/github.com/victorcoder/dkron/cron/cron.go:159 +0x451
```

dkron configuration on dkron-node-01 has been configured via config file as detailed-
```json
{
  "backend": "etcd",
  "backend_machine": "127.0.0.1:2379",
  "server": true,
  "tags": {
    "role": "myproject"
  },
  "keyspace": "dkron",
  "encrypt": "[generated_secret_key]",
  "join":[
    "dkron-node-02"
  ]
}
```

Job configuration
```json
{
  "name": "myproject",
  "schedule": "@every 1m",
  "shell": true,
  "command": "java -jar /home/user/myproject-0.1.0.jar",
  "disabled": false,
  "tags": {
    "role": "myproject:1"
  },
  "retries": 0,
  "dependent_jobs": null,
  "parent_job": "",
  "processors": null,
  "concurrency": "allow"
}
```

Is there any suggestion or any other more information on the error message that cause dkron process to be terminated? The termination of the process could be found after a couple of hours execution and was occurred on both machines almost simultaneously. 

Thanks in advance,

**Comment by ZhangYet** [comment]
The same error occurs to me while I was using a processors `processors: { 'file': {}}`

**Comment by victorcoder** [comment]
Hi @kiterminal, the important part here is `client: etcd cluster is unavailable or misconfigured` dkron is unable to talk to the etcd server.

My recommendation, etcd is a HA system based on quorum to elect a leader node, the recommended minimum cluster size is 3. Read https://coreos.com/etcd/docs/latest/v2/admin_guide.html "Optimal cluster size" section.

I'm closing the issue but feel free to reopen it in case it still fails with a 3 node setup.

**Comment by ArminNrz** [comment]
Hi I have the same problem
The job is: 
![Screenshot from 2020-12-29 18-01-11](https://user-images.githubusercontent.com/63095090/103290922-e016a280-49ff-11eb-9f72-619a6676a9d1.png)
send 100 request to one dkron server
After 1 min I see this message in dkron
![Uploading Screenshot from 2020-12-29 18-03-51.png…]()

**Comment by yvanoers** [comment]
@ArminNrz 
> Hi I have the same problem
This is not the same issue. The issue you have is reported under number 828.
Could you post your message in that issue?
