### ISSUE TITLE
improvement : support list in tag key

### ISSUE THREAD

**Issue by genepix** [victorcoder/dkron#253]
Hello,

I'm currently trying to deploy dkron to centralize our cron. It's working pretty well at the moment, so good job!

Is it possible though to add the possibility to provide a list value, given a key, for the "tags" key, in the job definition part ?

example : "tags" : { "app": ["myapp1","myapp2"] }

Many thanks !

**Comment by victorcoder** [comment]
I guess that you're trying to target both nodes (`myapp1`, `myapp2`) individually but why don't you tag your nodes with a more general tag `myapp` or `app-special-group`, does this works for you?

**Comment by genepix** [comment]
Hello, sorry for the delay. Yeah that's what i did (it doesn't fit super well in my case but "it works"). Thanks
