### ISSUE TITLE
Job : owner field

### ISSUE THREAD

**Issue by genepix** [victorcoder/dkron#254]
Hello,

I've got a question about the owner field : As I understand it, it should act as the user you launch the desired command. But it doesn't and the user you run the agent with seems to be always picked up. So my question is, is it a bug, or is it the desired behaviour and the field is just a description (but it looks confusing in my way)

Thanks again !

**Comment by victorcoder** [comment]
It's indeed just description. Currently there's no way of launching jobs with non root user unless your command specify that.
