### ISSUE TITLE
Wonder if this is a bug for processor plugins?

### ISSUE THREAD

**Issue by tonicbupt** [victorcoder/dkron#255]
[here](https://github.com/victorcoder/dkron/blob/master/dkron/rpc.go#L70)

```
origExec := execution
for k, v := range job.Processors {
	log.WithField("plugin", k).Debug("rpc: Processing execution with plugin")
	processor := rpcs.agent.ProcessorPlugins[k]
	e := processor.Process(&ExecutionProcessorArgs{Execution: origExec, Config: v})
	execution = e
}
```

I was wondering if this `Execution: origExec` should be `Execution: execution` ?
Otherwise `origExec` never changes...

**Comment by victorcoder** [comment]
Basically the intention here is to pass the same execution to the processors. Ensuring all processors have them passed the execution intact.

 I'm not sure at this point how to implement processor chaining in a satisfying way. Suggestions​ are welcome.

**Comment by tonicbupt** [comment]
Okay I got this. I thought the intention here was to make a processor chain and apply execution to each processor in the list...
