### ISSUE TITLE
Dkron - Anacron or cron-like functionality?

### ISSUE THREAD

**Issue by tejasmanohar** [victorcoder/dkron#256]
Does dkron work like anacron? What happens if all nodes go down (e.g. due to scheduled maintenance)? Should the service managing the jobs in Dkron's schedule handle this or will Dkron run missed jobs when it's back up? My understanding is the run will be missed but wanted to clarify.

**Comment by victorcoder** [comment]
What anacron feature are you talking about? The executions if all nodes goes down are missed.

**Comment by tejasmanohar** [comment]
>With cron, tasks are commonly scheduled to be executed when the system is expected to be idle. If the system is off at the moment a task should be run, it will not be executed. **Anacron is different and moves tasks to different moments so they are run when the system is on and utilising cron.**
from [here](https://en.wikipedia.org/wiki/Anacron)

This is what I was referring to ^. Sorry, I should have been more clear.

Anyways, cool, this makes sense! Is there a way to keep track of missed executions?

**Comment by victorcoder** [comment]
There's no track of missed executions if the systems is down. If dkron is up and correctly configured it should not miss executions :)
