### ISSUE TITLE
Executing deleted jobs

### ISSUE THREAD

**Issue by tejasmanohar** [victorcoder/dkron#258]
We're still getting
```
time="2017-04-18T21:37:48Z" level=error msg="agent: Error invoking job command" error="rpc: Received execution done for a deleted job." node=3ecc35ae7657
```
on v0.9.3 when changing / deleting jobs. Is this problematic?

I saw an issue about this before https://github.com/victorcoder/dkron/issues/85 but it was resolved.

**Comment by victorcoder** [comment]
@tejasmanohar as I said in #85 This should happen only if the job was running while you deleted it.

Could it be the case? Could you explain how to reproduce it?

Thanks!

**Comment by tejasmanohar** [comment]
Sorry, but we decided to go with a simpler adhoc solution instead of dkron for now (not that it's necessarily bad, just that we could get away with a lot less complexity / robustness for a long while)... and I don't have all my tests handy :\
