### ISSUE TITLE
dkron exit when a new node is started. 

### ISSUE THREAD

**Issue by zozo6015** [victorcoder/dkron#259]
Hello, 

I am running dkron with etcd2 on 5 different nodes. The first node starts correctly, when I start the second node the dkron process will exit on the node it is executed. The errors I have are the following:

    time="2017-04-23T03:04:24Z" level=debug msg="store: Setting key" execution=1492916661474639450-client-cluster-1 job="db_bkp" node=client-cluster-4 
    time="2017-04-23T03:04:25Z" level=debug msg="store: Retrieved job from datastore" job="db_bkp" node=client-cluster-4 
    time="2017-04-23T03:04:25Z" level=debug msg="store: Setting job" job="db_bkp" json="{\"name\":\"db_bkp\",\"schedule\":\"0, 0, 1, *, *, *\",\"shell\":false,\"command\":\"cd /opt/sources/wpCloud/node-sql-service/bin ; ./make-all-snapshots.sh\",\"owner\":\"root\",\"owner_email\":\"\",\"success_count\":0,\"error_count\":8,\"last_success\":\"0001-01-01T00:00:00Z\",\"last_error\":\"2017-04-23T03:04:21.477366354Z\",\"disabled\":false,\"tags\":{\"role\":\"cron\"},\"retries\":0,\"dependent_jobs\":null,\"parent_job\":\"\",\"processors\":null,\"concurrency\":\"forbid\"}" node=client-cluster-4 
    time="2017-04-23T03:04:25Z" level=warning msg="rpc: Error calling ExecutionDone" error="unexpected EOF" node=client-cluster-4 
    time="2017-04-23T03:04:25Z" level=error msg="agent: Error invoking job command" error="unexpected EOF" node=client-cluster-4 
    time="2017-04-23T03:04:26Z" level=fatal msg="rpc:101: Compare failed ([9657 != 9658]) [9664]" node=client-cluster-4 

Any idea why the job is not executed and why is giving an execution error? Also why the process is getting killed if a job erroring out.

**Comment by victorcoder** [comment]
You should use a recent version of etcd, > 3

Feel free to reopen if it still happens.
