### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by RWOverdijk** [victorcoder/dkron#263]
Hello, noob here.

This project seems cool, but I'm having some trouble getting started. I find the docs to not be helpful enough to get me started. I'm referring to the getting started guide, which seems a bit short of info.

I'm sure there's more, as people are working with it already. But where? :)

**Comment by victorcoder** [comment]
Hi @RWOverdijk, sorry about that, I'm working on improving the docs, meanwhile you can ask me questions directly: victor at victorcastell.com
