### ISSUE TITLE
Minor mistakes in API Documentation

### ISSUE THREAD

**Issue by RushinthJohn** [victorcoder/dkron#264]
# In Paths section:
The description of GET /leader states "List members." when it's actually "List leader of cluster"

# In Definitions section:
The description of 'member-ProtocolMax' states "Serf protocol minimum version this node can understand or speak" when it's actually "Serf protocol maximum version this node can understand or speak"

The description of 'member-DelegateMax' states "Serf delegate protocol minimum version this node can understand or speak" when it's actually "Serf delegate protocol maximum version this node can understand or speak"

The description of 'member-DelegateCur' states "Serf delegate protocol minimum version this node can understand or speak" when it's actually "Serf delegate protocol current version this node can understand or speak"

**Comment by victorcoder** [comment]
Thanks @RushinthJohn!
