### ISSUE TITLE
Configurable logging outputs for dkron agent

### ISSUE THREAD

**Issue by walrusVision** [victorcoder/dkron#270]
Is it possible to change where the agent itself logs to? It looks like it just logs to stdout as far as I can tell, but it would be useful to have it log to something like syslog instead.

**Comment by victorcoder** [comment]
Hi @walrusVision the recommended way to deal with this is to use your supervisor of choice to redirect the output to whatever you need.

It's best practice to do it in your init system.

Don't take my word for it, refer to http://0pointer.de/public/systemd-man/daemon.html#New-Style%20Daemons

**Comment by walrusVision** [comment]
Hi @victorcoder 

I'd like to be able to capture the logging from all the agents in one central location which would be particularity useful for me since a lot of our jobs would run on only one dkron instance in the cluster at any given execution point.

Ideally I'd like to not have to worry about what details of the init system and have dkron take care of itself.

**Comment by victorcoder** [comment]
@walrusVision That's perfectly possible using a post processor plugin, currently there is 3 processors available http://dkron.io/internal/plugins/#built-in-logging-processors

Choose what fit your needs and forward it to your central location.

If you still hace special needs, I offer custom development of logging processors for you.
