### ISSUE TITLE
dkron can not work well with api /v1/jobs while adding of 100 jobs 

### ISSUE THREAD

**Issue by Steven086** [victorcoder/dkron#276]
while adding jobs with the following shell, dkron will stop creating all new execution. in other word, it is out of work.

== SHELL BEGIN  ======================
#!/bin/sh
for ((i=1;i<=100;i++)); do
dpre='{
    "name": "test_job_'
dfix='",
    "command": "ls -al /bin",
    "schedule": "@every 1s",
    "tags": {
        "role": "web"
    }
}'

curl 127.0.0.1:8080/v1/jobs -d "${dpre}${i}${dfix}"

done
=== SHELL END ===

we can find thousands of tcpTIME_WAIT on port  6868

tcp        0      0 192.168.1.117:59292     192.168.1.117:6868      TIME_WAIT   -
tcp        0      0 192.168.1.117:59610     192.168.1.117:6868      TIME_WAIT   -
tcp        0      0 192.168.1.117:36698     192.168.1.117:6868      TIME_WAIT   -
tcp        0      0 192.168.1.117:37194     192.168.1.117:6868      TIME_WAIT   -
tcp        0      0 192.168.1.117:39348     192.168.1.117:6868      TIME_WAIT   -
tcp        0      0 192.168.1.117:38730     192.168.1.117:6868      TIME_WAIT   -
tcp        0      0 192.168.1.117:38838     192.168.1.117:6868      TIME_WAIT   -
tcp        0      0 192.168.1.117:34886     192.168.1.117:6868      TIME_WAIT   -
tcp        0      0 192.168.1.117:60270     192.168.1.117:6868      TIME_WAIT   -
tcp        0      0 192.168.1.117:36816     192.168.1.117:6868      TIME_WAIT   -
tcp        0      0 192.168.1.117:39606     192.168.1.117:6868      TIME_WAIT   -
tcp        0      0 192.168.1.117:36764     192.168.1.117:6868      TIME_WAIT   -
tcp        0      0 192.168.1.117:33614     192.168.1.117:6868      TIME_WAIT   -
tcp        0      0 192.168.1.117:34564     192.168.1.117:6868      TIME_WAIT   -
tcp        0      0 192.168.1.117:40206     192.168.1.117:6868      TIME_WAIT   -
tcp        0      0 192.168.1.117:38086     192.168.1.117:6868      TIME_WAIT   -
tcp        0      0 192.168.1.117:58620     192.168.1.117:6868      TIME_WAIT   -
tcp        0      0 192.168.1.117:34284     192.168.1.117:6868      TIME_WAIT   -
tcp        0      0 192.168.1.117:37480     192.168.1.117:6868      TIME_WAIT   -
tcp        0      0 192.168.1.117:58414     192.168.1.117:6868      TIME_WAIT   -
tcp        0      0 192.168.1.117:39590     192.168.1.117:6868      TIME_WAIT   -
tcp        0      0 192.168.1.117:56988     192.168.1.117:6868      TIME_WAIT   -
tcp        0      0 192.168.1.117:34924     192.168.1.117:6868      TIME_WAIT   -
tcp        0      0 192.168.1.117:60174     192.168.1.117:6868      TIME_WAIT   -
tcp        0      0 192.168.1.117:59620     192.168.1.117:6868      TIME_WAIT   -
tcp        0      0 192.168.1.117:33656     192.168.1.117:6868      TIME_WAIT   -
tcp        0      0 192.168.1.117:39572     192.168.1.117:6868      TIME_WAIT   -
tcp        0      0 192.168.1.117:36692     192.168.1.117:6868      TIME_WAIT   -

**Comment by victorcoder** [comment]
Probably fixed in #350
