### ISSUE TITLE
Panic if get job from store failed

### ISSUE THREAD

**Issue by johnnyjian** [victorcoder/dkron#289]
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x9ccfb2]
> 
> goroutine 72934 [running]:
> github.com/victorcoder/dkron/dkron.(*AgentCommand).processFilteredNodes(0xc4201b67e0, 0x0, 0xef9180, 0xc4200156a0, 0xef9100, 0xc42018ff00, 0xc420281220, 0x403b2d)
>         /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/agent.go:590 +0x72
> github.com/victorcoder/dkron/dkron.(*AgentCommand).RunQuery(0xc4201b67e0, 0xc42009a000)
>         /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/queries.go:39 +0xe9
> github.com/victorcoder/dkron/dkron.(*Job).Run(0xc420130fc0)
>         /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/job.go:110 +0x344
> created by github.com/victorcoder/dkron/cron.(*Cron).run
>         /Users/victorcoder/src/github.com/victorcoder/dkron/cron/cron.go:159 +0x451

It is caused by ignoring error returning by a.store.GetJob in AgentCommand.RunQuery.

**Comment by victorcoder** [comment]
Why `GetJob` is not working in this case?

**Comment by johnnyjian** [comment]
because the store is temporarily down.
