### ISSUE TITLE
Add virtual environments to jobs

### ISSUE THREAD

**Issue by didiercrunch** [victorcoder/dkron#292]
Hi there,

I would like to add the possibility to set virtual environments in jobs.  The use case is to pass arguments to the croned executable by virtual environment instead of by command line.

I suggest to add an `environment_variables` field in the job definition.  The `environment_variables` would be a list of strings formatted in the usual `environment_variable_name=environment_variable_value` format.

would a pull request be welcome?

cheers,

**Comment by victorcoder** [comment]
Merged
