### ISSUE TITLE
Features missing for production use

### ISSUE THREAD

**Issue by mambistats** [victorcoder/dkron#302]
Hi we are currently evaluating dkron and see the following issues for use in production:

- Unexpected evaluation order of the configuration
- No authentication and authorization ... this is a no go for us ... anybody who can reach the dashboard can delete our tasks and/or create new ones
- No way to configure the log style and output of gin ... the worst thing is the colored access log ... may look good in console ... but is horrible in the log files ...

What do I mean by unexpected evaluation order of the configuration?

The expected evaluation order for configuration under unix is:

- Configfile in this order: /etc - $HOME - commandline option
- Environment Variable
- Command line options
- And especially a command line option for a different configuration file ... it seems strange to me, that such an option is missing ... 

with increasing priority from top to down ... meaning that command line options have the highest priority and override all other sources of configuration.

That is a well known best practice and dkron is the first tool i found that breaks these rules ...

I looked into the GO code (never before done anything with go) but to me it looks like the configuration management sets the command line options as default values and than reads the configfile which overrides the defaults set ... so the command line options are lost ... but may be I am wrong ... 

Why does this matter?

We have a config for dkron in an etc directory mounted on all nodes. This contains the common configuration for all dkron nodes.

When dkron finds the server option in the config file it does no longer respect any options and commands given on the command line ... so it is not possible to say server=false in the config file and only on one node to start dkron with the option -server=true ... this is very unlucky.

Next we want to setup a few node special labels. But since some labels are already defined in the config file, you no longer can setup additional labels on the command line ... also very unlucky.

It is hard for me to believe that anybody is using this in a production critical environment ... especially without any means for authentication and authorization ... or am I missing something here?

I like the ideas of dkron but it needs still some improvements before we can use it in production. Keep up the good work ... may be in the future you can integrate the above mentioned features.

**Comment by mgancarzdsi** [comment]
Just adding my two cents that I'm keeping an eye on dkron but also would never do a production deployment without the above, particularly authentication/authorization.

**Comment by mambistats** [comment]
Currently we are diving deeper into another problem ... we are trying to get the status of job via the REST API as it is shown in the dashboard ... guess what ... you cannot get the status via REST.

This shows a bad design approach regarding the architectural principle of separation of concerns. 

We are trying to build a better dashboard that also allows the creation of jobs via a standard web form ... something I would expect for production use ... but may be I am having to high standards ... ;)

The dashboard should be a stand alone web application only using the REST API of dkron. But instead it uses templates and inner server state ... see https://camunda.com/de/bpm/features/ for example ... this is a really good architecture. 

I really love the concepts of dkron and the google white paper ... and standard cron really needs to be replaced by a tool like this ... but if dkron wants to be the taker ... it should consider these ideas and concepts ...

**Comment by kevana** [comment]
>may be I am expecting too much having too high standards

Maybe, but you have the power to help 😉 . No one is being paid for their work here, if you need new features or improvements for your company to use dkron then your company should invest the dev time, PRs are always welcome.

**Comment by mambistats** [comment]
I surely have the power to help at the level of an requirements engineer ... that is the reason I am explaining the deficits here. But I am a proven Java EE Developer and the things I have seen here ... do not really convince me that GO is the right language to do it ... If I would do such a project ... I would do it in Java ... and we are thinking about that! ... using Quartz ... Quartz is really in production use and reliable ... and I know it! ... dkron has problems keeping its inner Data Model consistent on 
ZooKeeper, fights with empty collections, has out of bounds errors ... and that after 3 years ... for me this shows problems in QA and Testing ... and from that I cannot judge if it is possible to raise the quality of dkron or if I just would waste my time ... and as you for sure know ... leisure time for development is precious ... and if you decide for a project ... it should be a good one of high quality with the chance to become a viable solution ...

I tested dkron because I read the docs first ... and it costed me already two weeks to get it up running ... and it still fails in executing some jobs without giving any hints ... even nothing in the logs ... 

So I have made my decision and we will evaluate the next tool ... I will further observe dkron but not spent any more time on it ... sorry guys.

I must say ... its brave to state in doc that dkron is used in production ... if I would be you I would change that to we are in pre-Beta stage ... not usable for production ... but that is only my 2c

 that does not increase my trust in such a solution ... 

We invest some time into development of a cron like tool ... but we would also do it it for no mone

**Comment by saitolabs** [comment]
> If I would do such a project ... I would do it in Java

So you was cryogenically frozen for 15 years and someone just brought you back to life?

**Comment by victorcoder** [comment]
I appreciate all the feedback here, I'll try to respond to some of the questions in the following days.

**Comment by victorcoder** [comment]
I'll try to clarify some of the main message points:

> No authentication and authorization ... this is a no go for us ... anybody who can reach the dashboard can delete our tasks and/or create new ones

Well, authentication and authorization is out of the scope of Dkron, the focus is in making the software to work well and confidently, currently I'm the single developer of the project and I don't want/can afford to focus on non essential things. This is similar to other software like etcd < 2.1, consul in previous versions, elasticsearch in previous versions, memcached, redis, etc.

I understand that not having security could be a problem for some organizations, but the software is intended to be used in a closed and trusted network.

If you only need the webinterface to be read-only, it could be achieved in two ways, being the first option the most straightforward:

1. Put it behind a reverse proxy and allow only GET verbs on `/dashboard` and `/assets`
2. Build a custom UI

> No way to configure the log style and output of gin ... the worst thing is the colored access log ... may look good in console ... but is horrible in the log files ...

Gin was introduced in the last release, thanks for bringing up the log coloring and formatting problem, this is something that could be easily fixed and I will address it in the next release.

> Unexpected evaluation order of the configuration

Thanks again for bringing this issue to the table, this needs to be fixed also.

> it costed me already two weeks to get it up running

It's easy using docker, I see that the docs needs more work but this should work straightforward https://github.com/victorcoder/dkron#quick-start

>  I must say ... its brave to state in doc that dkron is used in production ... if I would be you I would change that to we are in pre-Beta stage ... not usable for production ... but that is only my 2c

I can understand your frustration but bear with me, there is still a lot of work to do but its considered to be beta version because we are using it in production (and other several companies are) and it works, and works stable, for our use case.

I will extract the necessary issues from this thread.

**Comment by victorcoder** [comment]
https://github.com/victorcoder/dkron/pull/307
