### ISSUE TITLE
glide / dependencies not working

### ISSUE THREAD

**Issue by halorium** [victorcoder/dkron#303]
I am new to this repo and following the instruction on the README doesn't work. "glide install" fails due to invalid repo links or package conflicts, etc.

**Comment by headingy** [comment]
same error:
[INFO]	--> Fetching golang.org/x/sys
[INFO]	--> Fetching golang.org/x/net
[INFO]	--> Fetching golang.org/x/crypto
[WARN]	Unable to checkout golang.org/x/net
[ERROR]	Update failed for golang.org/x/net: Cannot detect VCS
[WARN]	Unable to checkout golang.org/x/crypto
[ERROR]	Update failed for golang.org/x/crypto: Cannot detect VCS
[WARN]	Unable to checkout golang.org/x/sys
[ERROR]	Update failed for golang.org/x/sys: Cannot detect VCS
[ERROR]	Failed to install: Cannot detect VCS
Cannot detect VCS
Cannot detect VCS

Can anyone help? Thanks

**Comment by victorcoder** [comment]
@halorium @headingy If you do a `docker build .` from the root directory, does it work?

**Comment by victorcoder** [comment]
Will be superseded by #308
