### ISSUE TITLE
Migrate from Glide to Dep

### ISSUE THREAD

**Issue by victorcoder** [victorcoder/dkron#308]
FWIW, the glide documentation says that -

The Go community now has the dep project to manage dependencies. Please consider trying to migrate from Glide to dep. If there is an issue preventing you from migrating please file an issue with dep so the problem can be corrected. Glide will continue to be supported for some time but is considered to be in a state of support rather than active feature development.

This is a good first issue

**Comment by PrincipalsOffice** [comment]
Hey i can grab this task if its available.

**Comment by victorcoder** [comment]
Thanks @PrincipalsOffice but it was easier than I expected, I will point you to something else.

**Comment by victorcoder** [comment]
@PrincipalsOffice if you want more frontend work https://github.com/victorcoder/dkron/issues/310

**Comment by victorcoder** [comment]
Done
