### ISSUE TITLE
Create a new processor for mailing notifications

### ISSUE THREAD

**Issue by victorcoder** [victorcoder/dkron#311]
Create a new processor plugin that sends mail notifications.

Ideally it should implement options to send notifications only on failures.

http://dkron.io/internal/plugins/

Related to #219

**Comment by yebo29** [comment]
Is there any current way to email only on failure?

**Comment by yebo29** [comment]
I see something has been put in place for the Pro version, are there any plans to also implement in the open source version? Also the docs @ https://dkron.io/pro/email/ don't mention being able to put in a rule for notifying only on failure. This would be such an awesome (and essential?) thing to have. Thanks.
