### ISSUE TITLE
tag filtering is working like wildcard on tag's value

### ISSUE THREAD

**Issue by genepix** [victorcoder/dkron#312]
Hello,

I'm facing a funny scenario here, a job with tag condition {"app": "myapp"} actually match nodes with {"app": "myapp"}, but also nodes with {"app": "myappxxxxxxxxxxxxx"}.

I don't know golang but nothing seems odd to me at the "if" statement in the processFilteredNodes function (where i guess it's the filter part) : https://github.com/victorcoder/dkron/blob/master/dkron/agent.go#L610

tested with 0.9.4 and 0.9.5 release

**Comment by genepix** [comment]
Hello,
I've investigated a bit more about this issue : 

This function returns an empty list of nodes, so serf's query behaviour is based on tag's filter (due to empty nodes list). But Serf acts like a wildcard regexp for tag filtering : 

https://github.com/hashicorp/serf/blob/master/serf/query.go#L227

A dirty workaround is to set the wished wildcard in the job (like {"app":"^mystrictapp$"}), but the count filter won't work.

**Comment by victorcoder** [comment]
Good catch @genepix, thanks for the investigation, I'll fix this

**Comment by genepix** [comment]
De nada :) !
