### ISSUE TITLE
error running job - rpc error dailing

### ISSUE THREAD

**Issue by sonam1318** [victorcoder/dkron#333]
dkron     | time="2018-02-14T23:59:00Z" level=debug msg="agent: Sending query" job_name=inzen-app-group-lookup-producer2 json="{\"execution\":{\"job_name\":\"inzen-app-group-lookup-producer2\",\"started_at\":\"0001-01-01T00:00:00Z\",\"finished_at\":\"0001-01-01T00:00:00Z\",\"group\":1518652740001045685,\"attempt\":1},\"rpc_addr\":\"10.204.74.220:6868\"}" node=dd9c6127bd11 query="run:job"
dkron     | time="2018-02-14T23:59:00Z" level=debug msg="agent: Received event" event="query: run:job" node=dd9c6127bd11
dkron     | time="2018-02-14T23:59:00Z" level=debug msg="agent: Running job" at=4 node=dd9c6127bd11 payload="{\"execution\":{\"job_name\":\"inzen-app-group-lookup-producer2\",\"started_at\":\"0001-01-01T00:00:00Z\",\"finished_at\":\"0001-01-01T00:00:00Z\",\"group\":1518652740001045685,\"attempt\":1},\"rpc_addr\":\"10.204.74.220:6868\"}" query="run:job"
dkron     | time="2018-02-14T23:59:00Z" level=info msg="agent: Starting job" job=inzen-app-group-lookup-producer2 node=dd9c6127bd11
dkron     | time="2018-02-14T23:59:00Z" level=error msg="rpc: error dialing." err="dial tcp 10.204.74.220:6868: getsockopt: connection refused" node=dd9c6127bd11 server_addr="10.204.74.220:6868"
dkron     | time="2018-02-14T23:59:00Z" level=error msg="agent: Error on rpc.GetJob call" error="dial tcp 10.204.74.220:6868: getsockopt: connection refused" node=dd9c6127bd11
dkron     | panic: runtime error: invalid memory address or nil pointer dereference
dkron     | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbd73e2]

**Comment by victorcoder** [comment]
@sonam1318 maybe obvious question but does the agent have access to `10.204.74.220:6868`?

**Comment by victorcoder** [comment]
Closing because of no feedback, feel free to reopen.
