### ISSUE TITLE
0.9.7 .deb?

### ISSUE THREAD

**Issue by geoffjukes** [victorcoder/dkron#337]
Hi,

I've installed via `deb [trusted=yes] https://apt.fury.io/victorcoder/ /` but I'm only getting `0.9.6`. Is `0.9.7` released there?

Many thanks,

Geoff

**Comment by victorcoder** [comment]
Hi @geoffjukes, I just uploaded the `0.9.7` version to the APT repository.

**Comment by geoffjukes** [comment]
Thanks @victorcoder
