### ISSUE TITLE
0.9.6 -> 0.9.7 upgrade Ubuntu 16.04LTS

### ISSUE THREAD

**Issue by geoffjukes** [victorcoder/dkron#351]
Hi,

I attempted to install 0.9.7, but the service fails to start:

```
Apr 24 12:06:02 nexus-01-v dkron[28253]: panic: runtime error: index out of range
Apr 24 12:06:02 nexus-01-v dkron[28253]: goroutine 1 [running]:
Apr 24 12:06:02 nexus-01-v dkron[28253]: github.com/victorcoder/dkron/dkron.NewConfig(0xc42008e010, 0x0, 0x0, 0xc420186780, 0xc420199dd8)
Apr 24 12:06:02 nexus-01-v dkron[28253]: #011/Users/victorcoder/src/github.com/victorcoder/dkron/dkron/config.go:81 +0x23f
Apr 24 12:06:02 nexus-01-v dkron[28253]: github.com/victorcoder/dkron/dkron.(*AgentCommand).Run(0xc420186780, 0xc42008e010, 0x0, 0x0, 0xc420173300)
Apr 24 12:06:02 nexus-01-v dkron[28253]: #011/Users/victorcoder/src/github.com/victorcoder/dkron/dkron/agent.go:303 +0x50
Apr 24 12:06:02 nexus-01-v dkron[28253]: github.com/victorcoder/dkron/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc42024cf00, 0xc420182de0, 0xe36f1a, 0x7)
Apr 24 12:06:02 nexus-01-v dkron[28253]: #011/Users/victorcoder/src/github.com/victorcoder/dkron/vendor/github.com/mitchellh/cli/cli.go:255 +0x1eb
Apr 24 12:06:02 nexus-01-v dkron[28253]: main.main()
Apr 24 12:06:02 nexus-01-v dkron[28253]: #011/Users/victorcoder/src/github.com/victorcoder/dkron/main.go:50 +0x37d
Apr 24 12:06:02 nexus-01-v systemd[1]: dkron.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 24 12:06:02 nexus-01-v systemd[1]: dkron.service: Unit entered failed state.
Apr 24 12:06:02 nexus-01-v systemd[1]: dkron.service: Failed with result 'exit-code'.
Apr 24 12:06:02 nexus-01-v systemd[1]: dkron.service: Start request repeated too quickly.
Apr 24 12:06:02 nexus-01-v systemd[1]: Failed to start Dkron Agent.
```

My Config:

```
{
	"backend": "consul",
	"backend_machine": "127.0.0.1:8500",
	"encrypt": "XxxI5WWexOXGfyuf56zPhg==",
	"join": ["172.16.1.101", "172.16.1.102", "172.16.1.103"],
	"keyspace": "dkron",
	"log-level": "error",
	"mail_from": "cron@domain.local",
	"mail_host": "smtp.domain.local",
	"mail_port": 25,
	"mail_subject_prefix": "[Dkron]",
	"server": true,
	"tags": {
		"datacenter": "ash",
		"role": "io.schedule"
	}
}
```

I'm probably missing some new required config value, I just can't see what.

Thanks in advance,

Geoff

**Comment by geoffjukes** [comment]
Forget me..... The Keyspace config vale got moved over erroneously.

I only spotted it after I pasted it here :)

**Comment by geoffjukes** [comment]
I should add, the config above works just fine in 0.9.6.

`apt install dkron=0.9.6` and the problem goes away 😃

**Comment by sysadmind** [comment]
Did the copy/paste also remove quotes from the `mail_subject_prefix`? The `[` and `]` will likely cause the config to be read an an array instead of a string.

**Comment by geoffjukes** [comment]
I was so hopeful, @sysadmind

I use Salt for deployment, and the config is YAML wrapped in a Jinja2 `raw` block - but the resulting JSON does indeed end up as ` "mail_subject_prefix": ["Dkron"]` - I've fixed that now (thanks!) but it still doesn't load.

I'll update the config above with the JSON version (not my Salt YAML)

**Comment by geoffjukes** [comment]
I'm going to hazard a guess - I have something wonky in one (or more) of my Job configs, and the `Switch from libkv to valkeyrie` in 0.9.7 is catching/hitting it. Just wish I knew where...

**Comment by victorcoder** [comment]
But it doesn't load jobs when loading config, and it's crashing there

**Comment by victorcoder** [comment]
@geoffjukes I know what's going on, what command line args are you using in that instance?

**Comment by geoffjukes** [comment]
@victorcoder I’m installing with the GemFury .deb via apt. I haven’t customized it al all

**Comment by victorcoder** [comment]
@geoffjukes as a workaround you can pass a `-dummy` argument to the agent, this will be fixed in the next release.

**Comment by geoffjukes** [comment]
thanks @victorcoder, that did the trick. 0.9.7 is running now. Thanks!

**Comment by victorcoder** [comment]
@geoffjukes just uploaded v0.9.8 fixed

**Comment by geoffjukes** [comment]
Thanks @victorcoder - works as expected.
