### ISSUE TITLE
[bug]"concurrency==forbid" not work

### ISSUE THREAD

**Issue by koolay** [victorcoder/dkron#353]
### drone version: 0.10

The  `concurrency`  of  the job  should be expected executed only once, but actually not.

**job**

```
{
  "name": "every5s",
  "schedule": "0/5 * * * * ",
  "command": "date && echo 'hello' ",
	"shell": true,
  "disabled": false,
  "retries": 0,
  "concurrency": "forbid"
}
```

**cluster**

`./dkron-linux agent -node-name=01 -backend=consul -backend-machine=127.0.0.1:8500 -http-addr=:8080 -rpc-port=6863 -bind-addr=127.0.0.1:8946 -join=127.0.0.1:8946 -server`

`./dkron-linux agent -node-name=02 -backend=consul -backend-machine=127.0.0.1:8500 -http-addr=:8082 -rpc-port=6867 -bind-addr=127.0.0.1:8947 -join=127.0.0.1:8946 -server`

`./dkron-linux agent -node-name=03 -backend=consul -backend-machine=127.0.0.1:8500 -http-addr=:8083 -rpc-port=6866 -bind-addr=127.0.0.1:8948 -join=127.0.0.1:8946 -server`

`./dkron-linux agent -node-name=04 -backend=consul -backend-machine=127.0.0.1:8500 -http-addr=:8084 -rpc-port=6865 -bind-addr=127.0.0.1:8949 -join=127.0.0.1:8946 -server`

`./dkron-linux agent -node-name=05 -backend=consul -backend-machine=127.0.0.1:8500 -http-addr=:8085 -rpc-port=6864 -bind-addr=127.0.0.1:8950 -join=127.0.0.1:8946 -server`

**job logs**

Job | Started At | Finished At | Node | Output | Success
-- | -- | -- | -- | -- | --
every1m | 2018-04-27 10:55:25.047569991 +0800 CST | 2018-04-27 10:55:25.053710616 +0800 CST | 01 | 2018年 04月 27日 星期五 10:55:2... | true
every1m | 2018-04-27 10:55:25.067864191 +0800 CST | 2018-04-27 10:55:25.069557168 +0800 CST | 02 | 2018年 04月 27日 星期五 10:55:2... | true
every1m | 2018-04-27 10:55:25.069187086 +0800 CST | 2018-04-27 10:55:25.071151158 +0800 CST | 04 | 2018年 04月 27日 星期五 10:55:2... | true
every1m | 2018-04-27 10:55:25.070272591 +0800 CST | 2018-04-27 10:55:25.07164034 +0800 CST | 03 | 2018年 04月 27日 星期五 10:55:2... | true
every1m | 2018-04-27 10:55:25.146350595 +0800 CST | 2018-04-27 10:55:25.150188645 +0800 CST | 05 | 2018年 04月 27日 星期五 10:55:2... | true

-----------

**job.go**

```
func (j *Job) isRunnable() bool {
	status := j.Status() // this row has a concurrency  problem?

	if status == Running {
		if j.Concurrency == ConcurrencyAllow {
			return true
		} else if j.Concurrency == ConcurrencyForbid {
			log.WithFields(logrus.Fields{
				"job":         j.Name,
				"concurrency": j.Concurrency,
				"job_status":  status,
			}).Debug("scheduler: Skipping execution")
			return false
		}
	}

	return true
}

```

**Comment by sysadmind** [comment]
I believe that this actually works as expected. The idea of the concurrency option is to say that a single group of executions will not start if a previous group of executions are still running. Jobs will, by default, run on EVERY agent in the cluster. To limit a job to only run a single time, you need to use a tag selector with a size of 1. See here: https://dkron.io/usage/target-nodes-spec/

So you might have on a job configuration `"tags":{"mytag": "myvalue:1"}` which would mean only run the job on nodes where mytag is myvalue and only on one of those nodes. 

I think this could be more clear in the docs and this use case is probably common enough that a job option would make sense. Maybe a job type of run_once vs run_everywhere or something along those lines.

**Comment by victorcoder** [comment]
As @sysadmind said works as expected. Work in the docs upcoming

**Comment by kamly** [comment]
node info:
![image](https://user-images.githubusercontent.com/15706085/105627795-e91a5880-5e73-11eb-9d82-8f5a18dba552.png)

job info:
![image](https://user-images.githubusercontent.com/15706085/105627779-d3a52e80-5e73-11eb-8937-b95e0dcfde2a.png)

why not work ?

**Comment by victorcoder** [comment]
What do you mean it is not working? If you want to make that command work, you need to specify that the command will run as a shell command, using the:

```
{
  "command": "shell && command",
  "shell": "true"
}
```

**Comment by victorcoder** [comment]
@kamly take a look now to the example

**Comment by kamly** [comment]
o!! why should add   "shell": "true"?

Where is the doc mentioned it?
