### ISSUE TITLE
Writing new executor

### ISSUE THREAD

**Issue by yosiat** [victorcoder/dkron#364]
Hi!

I want to write new executor plugin and I am a little bit confused.
I want Dkron to publish messages to RabbitMQ instead of running processes.

As far as I see the executors' plugin are called only after the command is run (as `ExecutionDone`)
should I base my current work on #344 ?

**Comment by victorcoder** [comment]
@yosiat yes, you should base your work on #344.

Dkron default executor is shell, a RabbitMQ executor would publish messages to RabbitMQ on the scheduled time.

Executor is called passing it's corresponding params https://github.com/victorcoder/dkron/pull/344/files#diff-16070499d68044489e25eddd1308c2f2R47

Feel free to reopen if you have more doubts.
