### ISSUE TITLE
How can I use dkron to schedule millions of jobs?

### ISSUE THREAD

**Issue by arpit728** [victorcoder/dkron#369]
I want to use dkron for scheduling http requests, I want to schedule around 1 million jobs where each job would be a http request to be executed on the same time.

Ex: 1 Million http calls scheduled to run at 10 A.M 

Can dkron be used for such a huge scheduling, if yes how can I configure dkron for this requirement.

**Comment by victorcoder** [comment]
Dkron can handle bigs amount of jobs, I tested it with high volumes of scheduled jobs around 500 at the same instant but it is not specifically optimized for such use case.

Dkron is optimized for a good balance between reliability and performance trying to cover the most common usage pattern, scheduling jobs in a datacenter.

Said that, if you are willing to make some changes in your approach and tune dkron a lot, you can probably achieve your goal.

You can run dkron in several hundreds of nodes, schedule a job targeting them, with the command you need. This will fire up any number of jobs you need, using an HTTP executor like https://github.com/victorcoder/dkron/pull/358 is a good idea. And use Redis as a backend will be probably a good idea too.

Feel free to reopen in case you have doubts.

**Comment by arpit728** [comment]
You mean 500 Million?

Can you please tell me how can I use redis and HTTP executor with Dkron as nothing about this is mentioned in Dkron docs.

What configuration of server I will need to run dkron in several hundreds of nodes, please provide some configuration details about this.

**Comment by victorcoder** [comment]
@arpit728 I mean "five hundred" 500

I pointed you to the relevant code that you could use to approach your problem but I can't go deeper as they are still a WIP in the PR.

The current leader is the server that order the execution, the actual execution will be performed by one of the nodes the job targets.
