### ISSUE TITLE
Better documentation on install

### ISSUE THREAD

**Issue by victorcoder** [victorcoder/dkron#37]
It's not clear that a backend storage system is needed

**Comment by kbcaulder** [comment]
The getting started guide states 'backend-machines' (note the 's' ) can be configured in dkron.json but it does not appear to be working.  Specifying the '-backend-machine' flag always works.

"backend": "etcd",
"backend-machine": "192.168.122.10:2379",
"join": ["192.168.122.10:8946", "192.168.122.11:8946", "192.168.122.12:8946"]

$ ./dkron agent -debug=true -server
Starting Serf agent...
INFO[2015-11-28T11:51:55-05:00] agent: Serf agent starting
INFO[2015-11-28T11:51:55-05:00] agent: joining: [192.168.122.10:8946 192.168.122.11:8946 192.168.122.12:8946] replay: true
INFO[2015-11-28T11:51:55-05:00] agent: joined: 3 nodes
ERRO[2015-11-28T11:51:55-05:00] client: etcd cluster is unavailable or misconfigured 

$ ./dkron agent -debug=true -server -backend-machine 192.168.122.10:2379
Starting Serf agent...
INFO[2015-11-28T11:57:10-05:00] agent: Serf agent starting
INFO[2015-11-28T11:57:10-05:00] agent: joining: [192.168.122.10:8946 192.168.122.11:8946 192.168.122.12:8946] replay: true
INFO[2015-11-28T11:57:10-05:00] agent: joined: 3 nodes
INFO[2015-11-28T11:57:10-05:00] Running HTTP server on :8080

**Comment by victorcoder** [comment]
Thanks you @kbcaulder it's fixed in https://github.com/victorcoder/dkron/pull/42
