### ISSUE TITLE
shell / shell.exe executor

### ISSUE THREAD

**Issue by sbtkei** [victorcoder/dkron#370]
1. "shell" executor
{
  "name": "ifconfig",
  "schedule": "30 * * * * *",
  "shell": true,
  "command": "ifconfig",
  "executor": "**shell**"
}
   - Linux / Mac
   invoke: command error output
   - Windows
   **invoke: Specified executor is not present**

2. "shell.exe" executor
{
  "name": "ipconfig",
  "schedule": "0 * * * * *",
  "shell": true,
  "command": "ipconfig",
  "executor": "**shell.exe**"
}
   - Linux / Mac
   **invoke: Specified executor is not present**
   - Windows
   invoke: command error output

**Comment by victorcoder** [comment]
The executor should be "shell" not "shell.exe"

**Comment by sbtkei** [comment]
## Windows (dkron 0.10.1)

-  Success
{
  "name": "ipconfig",
  "schedule": "0 * * * * *",
  "executor": "**shell.exe**",
  "executor_config": {
    "command": "ipconfig",
    "shell": "true"
  }
}

- Failed
{
  "name": "ipconfig",
  "schedule": "0 * * * * *",
  "tags": {
  	"os": "windows"
  },
  "executor": "**shell**",
  "executor_config": {
    "command": "ipconfig",
    "shell": "true"
  }
}
```
INFO[2018-05-22T23:12:07+09:00] agent: Starting job                           job=ipconfig node=Windows
ERRO[2018-05-22T23:12:07+09:00] invoke: Specified executor is not present     executor="<nil>" node=Windows
```
