### ISSUE TITLE
success_count mismatch in executed jobs

### ISSUE THREAD

**Issue by arpit728** [victorcoder/dkron#372]
I scheduled 300 jobs in dkron to be executed at the same time, when I was verifying the execution I was assuming that success_count of each job executed successfully should be one but there were also some jobs whose success_count was 2. I was running dkron with two nodes.
And many jobs didn't run, what could be the reason behind this.
Please explain what does success_count really imply and what is the  reason behind this inconsistency.

**Comment by victorcoder** [comment]
`success_count` is incremented on each successful execution result received by a job execution.

Could you describe or paste your job definition?

**Comment by arpit728** [comment]
job definition `curl 127.0.0.1:3000`

**Comment by victorcoder** [comment]
Closing because lack of info. If you can please explain steps to reproduce and feel free to reopen
