### ISSUE TITLE
Appropriate endpoint for checking dkron's readiness?

### ISSUE THREAD

**Issue by seongju** [victorcoder/dkron#373]
I wanted to use `GET /`, `GET /leader`, or if need be `GET /jobs` as a readiness endpoint to know when I can start serving traffic to dkron. I chose these endpoints because I expected these endpoints to require a healthy distributed store to return 2xx.

For example, it seems that when the store is down (in this case it's consul) the logs say that dkron can't elect a leader.
![screen shot 2018-05-21 at 12 14 55 pm](https://user-images.githubusercontent.com/5506190/40317832-a9af78d8-5cf0-11e8-9078-95af95d79337.png)

When we test locally, all three of the above endpoints return 2xx even when the configured distributed store is down. Is there an endpoint I can use where upon a successful response I know that dkron is able to function properly/receive traffic?

**Comment by victorcoder** [comment]
Not right now but this makes sense to me as an enhancement.
