### ISSUE TITLE
Cross-Region (Cross-Data-Center) Resilience Issues - Proposal for a Fix

### ISSUE THREAD

**Issue by inadarei** [victorcoder/dkron#390]
Current implementation of DKron is only as resilient as the setup of the backend databases it uses. DKron documentation states: "it has no single points of failure due to the use of the fault tolerant distributed databases", but the problem is - these backends (zookeeper, etcd, consul) are only resilient within a single data-center (or a single region, in case of AWS). 

Bottomline: if you set up DKron on AWS and East region has an outage (which happens at least once a year) - you lose DKron.

You are assuming that this issue should be fixed on zookeeper, etcd and consul side and it's not really DKron's problem. Well, that assumption is problematic because as it happens – most large installations of these back-ends solve cross-data-center replication on the client side. You can see Kishore Gopalakrishna, Architect at LinkedIn commenting about it at Quora: https://www.quora.com/Has-anyone-deployed-a-ZooKeeper-ensemble-across-data-centers/answer/Kishore-Gopalakrishna The question/answer is several years old, but I believe the solution is still the same. AFAIK only Consul has automatic cross-region replication, but I believe it is only available in their enterprise version.

The actual common solution to the problem is: client should read only from one region/data-center at any given time but should write to all regions (at least 2) so that if any region/data-center is lost, data is available in other regions and those regions can now become active. 

Here's the proposal for a fix that would allow DKron to support this pattern and dramatically improve resilience of its installations, while introducing a backwards-compatible support:

1. You already have the `-backend-machine` configuration property. Let this be the list of servers that are used for both reading and writing

2. Add new options `-backed-machine-replica` in configuration. DKron would write everything it writes to `-backend-machine` to this server(s) as well, but will not use these servers for reading. 

This very small change will make DKron act in a way compatible with the pattern that is used for deploying cross-region, cross-data-center zookeeper/etcd/consul and will make a lot of people's lives easier.

Thoughts?

**Comment by victorcoder** [comment]
Thanks for the proposal @inadarei, you are right, Dkron is only resilient as it's backend database.

There are several missconceptions in your assumtions. AWS regions are not a single datacenter, Availability Zones are. I've been working several years within a single region using 3 AZs and didn't suffered from and outage in all 3 AZs. This is why for example RDS has the concept of MultiAZ, to ensure resiliency.

I don't know if you can point to some resource that indicates numbers on AWS full regions with all AZs failing. I think that AWS has gone down crossregions globally more than all AZs in one region.

It's recommended that you setup at least 3 servers of the backend store in 3 AZs in dkron, and this works as expected regarding replication.

Said that, your proposal is interesting and makes sense but there could be a potential performance impact that should be properly handled.

If you are using etcd (which is the recommended backend for Dkron) `etcdctl` command have the `make-mirror` tool that allows to mirror an etcd cluster from another etcd cluster https://github.com/coreos/etcd/blob/master/etcdctl/doc/mirror_maker.md, this could provide a way to have a very resilient installation.

**Comment by inadarei** [comment]
Thank you for a quick response, Victor.

I should have been more clear. I didn't mean that AWS regions are just separate data-centers, rather that "multi-region" is the unit of resilience people typically care for a geo-redundancy in AWS, and in non-AWS setups we'd just talk about data-centers. Either way, this is for use-cases where geographic redundancy specifically is important and AZ-level is not sufficient (which is even required in certain industries).

Regarding your question about how often have all AZs gone down in a region - something to keep in mind here is that most companies have policies stating that if any service (e.g. RDS, S3 etc.) goes down in a region - you should fail over to the backup region entirely. Otherwise you could be making cross-region calls in your application e.g. your application in East region trying to use RDS databse from West region and that can create way more problems than if you just started serving all traffic from West.

You are correct that the proposed solution can degrade performance in certain use-cases (e.g. when ratio of writes over reads are high). Main thing to consider: this change is backwards-compatible so in use-cases where it doesn't make sense, you would simply not indicate any `-backed-machine-replica` and DKron would operate as before.

Thank you

**Comment by victorcoder** [comment]
Awesome topic and discussion here but I think there is not much to do at this point, valkeyrie will get a DynamoDB backend at some point and this could cover the region availability issue.
