### ISSUE TITLE
How do I remove a node from the cluster?

### ISSUE THREAD

**Issue by yebo29** [victorcoder/dkron#392]
I spun up a test instance. After shutting it down, the state remains as "left". How do I remove entirely? Running version 0.10.2 and consul backend. Thanks

**Comment by victorcoder** [comment]
https://dkron.io/usage/api/#get-leave

**Comment by yebo29** [comment]
I understand that I have that API option, but I don't understand how to use it. 
The node in question is configured not as a server so I can't hit port 8080 on it. 
I configured it to be a server but when I hit http://127.0.0.1:8080/v1/leave it returns a 400 error. 
Do I need to specify which node I want to leave the cluster on the one server node and if so what parameter do I pass to it? The docs are not too clear on that

**Comment by prem2204** [comment]
@yebo29 Install docker Kitematic, you can use the GUI and lookup the docker container in which dkron is running. And verify the port is assigned to each node (under settings tab). Probably that way, you might we able to hit the /leave API on the agent node (not the server) specifying the appropriate port.
Though I am yet to use the /remove API myself to explore the option available.

**Comment by yebo29** [comment]
Thank you, but I am not running in a docker container. I just kept the node
as a 3rd member of the cluster.

**Comment by yebo29** [comment]
I was about to venture into manipulating the storage backend (consul) but
decided against it.

**Comment by victorcoder** [comment]
@yebo29 The cluster membership is not stored in the backend, it's managed by the Serf engine.

Your are right this is a Dkron limitation, there's no way to force a non server node to leave the cluster, but given that they don't have any other purpose than running jobs, why not simply stop the process?

**Comment by yebo29** [comment]
@victorcoder I wanted to replace the server and not have a no-longer-active entry on the list. But I just rebuilt the server so all is well :). You can close or I can close this issue if you want.

**Comment by victorcoder** [comment]
I must say, they disappear with time.

**Comment by EmilioMoreno** [comment]
@vcastellm Quick question, what is the amount of time it takes for any agent node to disappear after failed?

**Comment by vcastellm** [comment]
@EmilioMoreno https://github.com/distribworks/dkron/blob/master/dkron/config.go#L161

**Comment by netik** [comment]
This is the first hit for this on Google and all of the answers are incorrect.

1. Log into any node, issue: `dkron raft list-peers`
2. figure out which one is the leader.
3. log into the leader
4. issue `dkron raft remove-peer --peer-id <id goes here>` to remove the peer from raft.
