### ISSUE TITLE
Shell Command Execution

### ISSUE THREAD

**Issue by jvonkluck** [victorcoder/dkron#394]
I'm currently evaluating / testing dkron in our environment and have been really impressed with the overall design and ease of use thus far.

This may not be an "issue" per se, but I'm having trouble getting anything other than very trivial shell commands to execute via the remote agent.

For example, trying to execute commands of the format:
```sh
cd /some/app/dir && bundle exec rake task_namespace:task
```
or a very straightforward example:
```sh
hostname && pwd && whoami
# or
hostname; pwd; whoami
```

With a job definition that looks like:
```json
{
  "name": "test-targeted-job01",
  "timezone": "",
  "schedule": "0 0,30 * * * *",
  "shell": true,
  "command": "",
  "environment_variables": null,
  "owner": "",
  "owner_email": "",
  "success_count": 1,
  "error_count": 10,
  "last_success": "2018-06-21T15:42:04.535505877Z",
  "last_error": "2018-06-21T18:00:00.142453073Z",
  "disabled": false,
  "tags": {
    "service": "service-name-api:1"
  },
  "retries": 0,
  "dependent_jobs": [
    "test-targeted-dependent-job01"
  ],
  "parent_job": "",
  "processors": null,
  "concurrency": "allow",
  "executor": "shell",
  "executor_config": {
    "command": "'hostname && whoami'"
  },
  "status": "failed"
}
```

I'm seeing errors like `rpc error: code = Unknown desc = exec: "hostname && whoami": executable file not found in $PATH` in the console and 

```log
Jun 21 18:30:00 ubuntu-1604-base dkron[27550]: time="2018-06-21T18:30:00Z" level=info msg="agent: Starting job" job=test-generic-job01 node=staging-margin-rates-api02.tastyworks.com
Jun 21 18:30:00 ubuntu-1604-base dkron[27550]: 2018-06-21T18:30:00.134Z [DEBUG] plugin.dkron-executor-shell: shell: going to run 'hostname && whoami'
Jun 21 18:30:00 ubuntu-1604-base dkron[27550]: time="2018-06-21T18:30:00Z" level=error msg="invoke: command error output" error="rpc error: code = Unknown desc = exec: \"hostname && whoami\": executable file not found in $PATH" job=test-targeted-job01 node=staging-margin-rates-api02.tastyworks.com plugin="&{0xc420190538}"
```
in the syslog output for dkron. I've tried leaving the command unescaped `hostname && whoami`, escaping with single quotes `'hostname && whoami'` and escaping with escaped double quotes `\"hostname && whoami\"` in the job definition but it doesn't seem to have affected the outcome when the agent attempts to run the command.

Is there a way to do this that I'm either not configuring correctly or a way to properly format a shell command to ensure it works?

Thank you in advance

**Comment by victorcoder** [comment]
Thanks @jvonkluck, you should set `"shell": "true"` in the `executor_config` for shell based commands to work as expected.

Cpuld you try it?

**Comment by jvonkluck** [comment]
@victorcoder - that absolutely did the trick. The outer level `shell` attribute on the job was throwing me off as I'd set that instead. I must have completely missed that in the documentation. Upon closer inspection this morning it looks like you've already added deprecation warnings about the `shell` attribute on the job.

Thanks for the help. I'll close this one out.
