### ISSUE TITLE
where is the dkron log?

### ISSUE THREAD

**Issue by curious12coder1** [victorcoder/dkron#395]
Where can I see the default log of dkron? 

I learnt that we can setup processor_files for each job, but that for job.

But I am trying to find the log from dkron.

**Comment by victorcoder** [comment]
@curious12coder1 it depends on how do you install dkron, but the log output is stdout, if you use the linux packages the stdout is redirected to https://github.com/victorcoder/dkron/blob/master/builder/files/dkron.conf#L8 or in a systemd based linux it's searchable in the journal `sudo journalctl -u dkron.service`

**Comment by Michael62501** [comment]
How to mount logs from dkron to the host machine and set the size and quantity of log files in Docker

**Comment by Michael62501** [comment]
@vcastellm 

How to mount logs from dkron to the host machine and set the size and quantity of log files in Docker

**Comment by vcastellm** [comment]
There are no log files @Michael62501 as I mentioned, all logs goes to stdout/stderr, in Docker you don't need to mount logs, just observe the stdout.
