### ISSUE TITLE
help - how to schedule http calls

### ISSUE THREAD

**Issue by curious12coder1** [victorcoder/dkron#396]
I am able to run simple shell command through the jobs. 

Now, I am trying to understand what do I have to write to make a https calls. 

Do I have to write a processor plugin? If yes, could you please provide a sample one. I am not finding much info about this in your documentation and taking lot of time to figure out.

**Comment by victorcoder** [comment]
You have several options here, you can just call `curl` from a shell based job or there is an http executor in progress https://github.com/victorcoder/dkron/pull/358 you can try to use it.
