### ISSUE TITLE
If jobs are distributed on clusters

### ISSUE THREAD

**Issue by maz030** [victorcoder/dkron#397]
Hi, I just want to make sure that if multiple jobs are distributed on cluster. For example, if there are 60 jobs scheduled at same time and there are 3 nodes in cluster. So are those 60 jobs running on 3 nodes? (optimally it can be 20-20-20). Can we configure that in the request?

**Comment by victorcoder** [comment]
I letely uploaded great improvements to the docs, you can do that by using the correct tag definitions for your jobs and nodes. https://dkron.io/usage/target-nodes-spec/
