### ISSUE TITLE
Use the new etcd client

### ISSUE THREAD

**Issue by victorcoder** [victorcoder/dkron#4]
The current etcd client is being deprecated, the new client https://godoc.org/github.com/coreos/etcd/client will have all the focus in the future.

**Comment by samgaw** [comment]
Would you consider Docker's libkv instead of the etcd client?

github.com/docker/libkv

**Comment by victorcoder** [comment]
I thought this should be abstracted to allow several storage backends! thanks @samgaw I wanted this to exists.

Definitely worth considering.

From what I see in the docs the transition should be straightforward.

**Comment by samgaw** [comment]
We moved to Consul so the etcd code was the first thing I skimmed through to see how baked in it was but it's pretty minimal.

If I get a chance over the next couple of days I'll RTFM libkv but I wanted to check first that there wasn't a specific reason for updating the etcd client.

**Comment by victorcoder** [comment]
@samgaw Look at #21
