### ISSUE TITLE
Unable to build and setup the dkron project 

### ISSUE THREAD

**Issue by prem2204** [victorcoder/dkron#402]
I keep getting the below error when i try **_docker -compose up_**:

ERROR: for dkron  Cannot start service dkron: b'OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \\"scripts/entrypoint.sh\\": stat scripts/entrypoint.sh: no such file or directory": unknown'

I dont actually find any file v.i.z. entrypoint.sh in /scripts folder
Could you please help out in clarifying how to proceed?

**Comment by kevynhale** [comment]
Looks like the entrypoint got renamed to `run` in the PR https://github.com/victorcoder/dkron/commit/d62d0a08681ec7a5c2667b5a9e24cebe22adae6a but it didn't get updated in docker-compose.

**Comment by kevynhale** [comment]
@victorcoder I created a PR to fix this, https://github.com/victorcoder/dkron/pull/403.

**Comment by prem2204** [comment]
Thanks a lot for the info. I still see the same error now. ANything I should configure (as in add to my PATH variable , etc) before I run the docker-compose up command?
i even added the location of /scripts to the PATH variable :  
$GOPATH/src/dkron
Still the error.
Error:
ERROR: for 7550fceab492_dkron_dkron_1  Cannot start service dkron: b'OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \\"scripts/run.sh\\": stat scripts/run.sh: no such file or directory": unknown'

ERROR: for dkron  Cannot start service dkron: b'OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \\"scripts/run.sh\\": stat scripts/run.sh: no such file or directory": unknown'
ERROR: Encountered errors while bringing up the project.

**Comment by prem2204** [comment]
Found the solution. updated the docker-compose.yml file's command as below:
command: ./entrypoint.sh agent -server -backend=etcd -backend-machine=etcd:2379 -join=dkron:8946 -log-level=debug

this made the engine search for the file from current folder location.

**Comment by prem2204** [comment]
Closing this as its resolved now.
