### ISSUE TITLE
Unable to run job on a dkron agent server

### ISSUE THREAD

**Issue by sonam1318** [victorcoder/dkron#405]
We have a cluster of 3 dkron servers configured as:

- SERVER1 (running as a dkron server) 
- SERVER2 (running as a dkron server)
- AGENT1 (running as a dkron agent)

The agent server is marked with the "tags": {  "role":"agent" } to execute the job specifically on this.

Below is the output of "http://abc:8080/v1/members":

[{
  "Name": "SERVER1",
  "Addr": "IPADDRESS",
  "Port": 8946,
  "Tags": {
    "dkron_rpc_addr": "IPADDRESS:6868",
    "dkron_server": "true",
    "dkron_version": "0.10.3"
  },
  "Status": 1,
  "ProtocolMin": 1,
  "ProtocolMax": 5,
  "ProtocolCur": 2,
  "DelegateMin": 2,
  "DelegateMax": 5,
  "DelegateCur": 4
}, 
{
  "Name": "SERVER2",
  "Addr": "IPADDRESS",
  "Port": 8946,
  "Tags": {
    "dkron_rpc_addr": "IPADDRESS:6868",
    "dkron_server": "true",
    "dkron_version": "0.10.3"
  },
  "Status": 1,
  "ProtocolMin": 1,
  "ProtocolMax": 5,
  "ProtocolCur": 2,
  "DelegateMin": 2,
  "DelegateMax": 5,
  "DelegateCur": 4
}
{
  "Name": "AGENT1",
  "Addr": "IPADDRESS",
  "Port": 8946,
  "Tags": {
    "dkron_version": "0.10.3",
    "role": "agent"
  },
  "Status": 1,
  "ProtocolMin": 1,
  "ProtocolMax": 5,
  "ProtocolCur": 2,
  "DelegateMin": 2,
  "DelegateMax": 5,
  "DelegateCur": 4
}]

Below is a simple job we are trying to run on AGENT1:

{
  "name": "executor",
  "timezone": "America/Chicago",
  "schedule": "0 * * * * *",
  "shell": true,
  "command": "",
  "environment_variables": null,
  "owner": "test",
  "owner_email": "test@gmail.com",
  "success_count": 0,
  "error_count": 0,
  "disabled": false,
  "tags": {  "role":"agent" },
  "retries": 0,
  "dependent_jobs": null,
  "parent_job": "",
  "processors": null,
  "concurrency": "forbid",
  "executor": "shell",
  "executor_config": {
    "command": "echo 'hi'",
    "shell": "true"
  },
  "status": "success"
}

It does not get executed on AGENT1.
We see no errors when we try to execute this job - but there are no executions shown, also the "Success" and "Error" values remain 0.

However if I set the tags as null in the job and then execute the job, it executes on the SERVER1 and SERVER2 but not on AGENT1.

Below are the docker compose files for the dkron containers:
SERVER1:
-----------
version: '2'
services:
  dkron:
      restart: always
      container_name: dkron
      build:
        context: ./
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
        - "8946:8946"
        - "6868:6868"
      command: >
        agent
          --server
          --log-level=debug
          --node-name=SERVER1
          --advertise-addr=IP ADDRESS of SERVER1
          --bind-addr=0.0.0.0:8946
          --join=IP ADDRESS of SERVER2
          --backend=consul
          --backend-machine=IPADDRESS:8500
          --backend-machine=IPADDRESS:8500
          --backend-machine=IPADDRESS:8500
          --keyspace=mykey_dkron

SERVER2
-----------
version: '2'
services:
  dkron:
      restart: always
      container_name: dkron
      build:
        context: ./
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
        - "8946:8946"
        - "6868:6868"
      command: >
        agent
          --server
          --log-level=debug
          --node-name=SERVER2
          --advertise-addr=IP ADDRESS of SERVER2
          --join=IP ADDRESS of SERVER1
          --backend=consul
          --backend-machine=IPADDRESS:8500
          --backend-machine=IPADDRESS:8500
          --backend-machine=IPADDRESS:8500
          --keyspace=mykey_dkron

AGENT1
----------
version: '2'
services:    
  dkron:
      restart: always
      container_name: dkron
      build:
        context: ./
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
        - "8946:8946"
        - "6868:6868"
      command: >
        agent
          --log-level=debug
          --node-name=AGENT1
          --advertise-addr=IP ADDRESS of AGENT1         
          --join=IP ADDRESS of SERVER1
          --join=IP ADDRESS of SERVER2
          --backend=consul
          --backend-machine=IPADDRESS:8500
          --backend-machine=IPADDRESS:8500
          --backend-machine=IPADDRESS:8500
          --keyspace=mykey_dkron
          --tag role=agent

So not sure how can we make our job to execute on a dkron agent. Please suggest.

**Comment by victorcoder** [comment]
Sorry I totally missed this issue, going to look at it. Thanks for reporting

**Comment by victorcoder** [comment]
Checked agains latest version and it works as expected.

Could you check if it works well for you?

Closing the issue in the meantime as it is quite old.
