### ISSUE TITLE
rpc error: code = Unknown desc = exec: "testEcho.sh": executable file not found in $PATH

### ISSUE THREAD

**Issue by prem2204** [victorcoder/dkron#413]
Hi,
I am unable to execute any of the shell commands other than the 'echo' command.
This issue seems similar to an old one :
https://github.com/victorcoder/dkron/issues/394
Job definition:

{
    "name": "invokeexecutable",
    "timezone": "",
    "schedule": "*/30 * * * * *",
    "shell": false,
    "command": "",
    "environment_variables": null,
    "owner": "",
    "owner_email": "",
    "success_count": 0,
    "error_count": 0,
    "last_success": "0001-01-01T00:00:00Z",
    "last_error": "0001-01-01T00:00:00Z",
    "disabled": false,
    "tags": null,
    "retries": 0,
    "dependent_jobs": null,
    "parent_job": "",
    "processors": null,
    "concurrency": "forbid",
    "executor": "shell",
    "executor_config": {
        "command": "testEcho.sh"
    },
    "status": ""
}
I placed a copy of the testEcho.sh in the $GOPATH, set the path in $PATH too
Especially when i run the file in shell, I see the output :  
_INMAC42MNG:~ oh08$ testEcho.sh 
/Users/oh08/go
INMAC42MNG:~ oh08$_ 
I tried providing - "shell" : "true" inside "executor_config", still found no success. Error thrown was:
**_rpc error: code = Unknown desc = exit status 127_**

Please Help!!

**Comment by prem2204** [comment]
I went through other similar issues raised and have come up with the below findings:
I can see the below in startup logs. Which means shell executor is running:
_[DEBUG] plugin.dkron-executor-shell: plugin address: timestamp=2018-08-03T07:22:17.643Z address=/tmp/plugin198770853 network=unix_

**Comment by prem2204** [comment]
Go the solution. the executable file is supposed to be in the docker container path.:  
_**/go/src/github.com/victorcoder/dkron**_

with "shell":"true" parameter inside 'executor_config', I am able to run testEcho.sh

**Comment by prem2204** [comment]
Can close this. Its not an issue now.

**Comment by mathesh43** [comment]
facing the same issue on local dkron setup. 
rpc error: code = Unknown desc = exit status 127

any solution for this?

**Comment by prem2204** [comment]
What are you trying to execute? Is it a command or a file?
If its a file, ensure the file has execute permission. Also ensure the file is present in the docker container location. (/go/src/github.com/victorcoder/dkron)

**Comment by prem2204** [comment]
you may use docker copy command to copy your file:
e.g.
docker cp <source> dkron_dkron_1:/go/src/github.com/victorcoder/dkron

**Comment by prem2204** [comment]
certain texts got omitted in the above comment:

docker cp <source> dkron_dkron_1:/go/src/github.com/victorcoder/dkron
