### ISSUE TITLE
Concurrency = forbid not working for me! docker-compose up --scale dkron=2

### ISSUE THREAD

**Issue by prem2204** [victorcoder/dkron#415]
Hi, 
I am stuck with a latest issue which has got me thinking again whether can I use dkron for my project  requirements or not. The most important feature I'm looking for is concurrency = forbid ( in a distributed system). 
However, even though in the issue : https://github.com/victorcoder/dkron/issues/349, its told that the issue is fixed, I can still see each node triggering the job at the scheduled time. Attaching logs below. 
-----------
dkron_1  | time="2018-08-11T16:56:03Z" level=debug msg="agent: GetJob by RPC" command= node=484e202cdc16

dkron_1  | time="2018-08-11T16:56:03Z" level=debug msg="agent: Received event" event="query: run:job" node=484e202cdc16

dkron_1  | time="2018-08-11T16:56:03Z" level=debug msg="agent: Running job" at=182 node=484e202cdc16 payload="{\"execution\":{\"job_name\":\"testppeapirun\",\"started_at\":\"0001-01-01T00:00:00Z\",\"finished_at\":\"0001-01-01T00:00:00Z\",\"group\":1534006563219264700,\"attempt\":1},\"rpc_addr\":\"172.18.0.4:6868\"}" query="run:job"

dkron_1  | time="2018-08-11T16:56:03Z" level=info msg="agent: Starting job" job=testppeapirun node=484e202cdc16

dkron_1  | time="2018-08-11T16:56:03Z" level=debug msg="invoke: calling executor plugin" node=484e202cdc16 plugin=shell

dkron_2  | time="2018-08-11T16:56:03Z" level=debug msg="grpc: Received GetJob" job=testppeapirun node=f58399c7a58a

dkron_2  | time="2018-08-11T16:56:03Z" level=debug msg="store: Retrieved job from datastore" job=testppeapirun node=f58399c7a58a

dkron_2  | time="2018-08-11T16:56:03Z" level=debug msg="agent: Received response" from=484e202cdc16 node=f58399c7a58a query="run:job" response="{\"job_name\":\"testppeapirun\",\"started_at\":\"2018-08-11T16:56:03.3080162Z\",\"finished_at\":\"0001-01-01T00:00:00Z\",\"node_name\":\"484e202cdc16\",\"group\":1534006563219264700,\"attempt\":1}"

dkron_2  | time="2018-08-11T16:56:03Z" level=debug msg="store: Setting key" execution=1534006563308016200-484e202cdc16 job=testppeapirun node=f58399c7a58a

dkron_1  | 2018-08-11T16:56:03.310Z [DEBUG] plugin.dkron-executor-shell: shell: going to run /go/src/github.com/victorcoder/dkron/DkronJobChainingTest.sh

dkron_1  | time="2018-08-11T16:56:03Z" level=debug msg="store: Setting key" execution=1534006563300253900-484e202cdc16 job=testprintrun node=484e202cdc16

dkron_2  | time="2018-08-11T16:56:03Z" level=debug msg="store: to detele key" execution=1534005003302939600-f58399c7a58a job=testprintrun node=f58399c7a58a

dkron_2  | time="2018-08-11T16:56:03Z" level=debug msg="store: to detele key" execution=1534005003891871600-484e202cdc16 job=testppeapirun node=f58399c7a58

job details in GUI
====

Job | Started At | Finished At | Node | Output | Success
-- | -- | -- | -- | -- | --
testppeapirun | 2018-08-11 16:56:03.2268878 +0000 UTC | 2018-08-11 16:56:03.7138286 +0000 UTC | f58399c7a58a | Running AM scheduled task... | true
testppeapirun | 2018-08-11 16:56:03.3080162 +0000 UTC | 2018-08-11 16:56:03.6734327 +0000 UTC | 484e202cdc16 | Running AM scheduled task... | true

My Job response:
{
    "name": "testppeapirun",
    "timezone": "",
    "schedule": "*/30 * * * * * ",
    "shell": false,
    "command": "",
    "environment_variables": null,
    "owner": "",
    "owner_email": "",
    "success_count": 4132,
    "error_count": 24,
    "last_success": "2018-08-11T16:35:33.6470289Z",
    "last_error": "2018-08-11T16:05:28.7471037Z",
    "disabled": false,
    "tags": null,
    "retries": 0,
    "dependent_jobs": null,
    "parent_job": "",
    "processors": null,
    "concurrency": "forbid",
    "executor": "shell",
    "executor_config": {
        "command": "/go/src/github.com/victorcoder/dkron/DkronJobChainingTest.sh",
        "shell": "true"
    },
    "status": ""
}
I ran the server with the command : _**docker-compose up --scale dkron=2**_

Please let me know if I have done anything wrong.

**Comment by victorcoder** [comment]
@prem2204 What do you expect to see in this job definition? It seems to me that the execution of `DkronJobChainingTest.sh` is quite fast, so it runs on both nodes correctly then it waits until the next execution. It seems to work correctly.

In case the `DkronJobChainingTest.sh` execution lasts for more than 30s, the next executions should skip the execution.

**Comment by prem2204** [comment]
I wish to see that job execution is performed only in one of the nodes. not both. In real-time DkronJobChainingTest.sh needs to have the code to invoke an API once everyday at a scheduled time say 12 midnight. Its supposed to be invoked just once.
But it seems now that If I have multiple nodes in the cluster, each node will invoke the API at the 12, which will be a concern. For just testing purposes, I had set 30 secs interval for job run. I will increase the time gap and note the behaviour.

**Comment by prem2204** [comment]
Even With "schedule": "@every 20m",
I see multiple invocations of the job (from each node at the same time)
Am I looking at the feature "concurrency":"forbid" correctly?

**Comment by sysadmind** [comment]
@prem2204 The concurrency: forbid option is for controlling if another invocation (i.e. the next interval) will start if a previous invocation is still running. That does not prevent the job from starting on all nodes that the job targets. I believe what you want is a tag filter like `{"tags": {"mytag": "myvalue:1"}}`

Take a look at the spec here: https://dkron.io/usage/target-nodes-spec/

I had trouble with this myself when I first deployed dkron. I think it's something that could use more highlighting.

**Comment by ProPheT777** [comment]
If want limit the number of node will execute the job, simply with tags on job specification like : 

```json
{
   name: "test",
   tags: {
     role: 'worker:1'
   }
}
```

Where 1 is the number of scheduled node like described in https://dkron.io/usage/target-nodes-spec/ as @sysadmind mentioned

**Comment by prem2204** [comment]
@ProPheT777  @sysadmind : Thanks a lot! The tag configuration worked. I am able to invoke the job only from one of the nodes out of the 2 (having same tag -- role)

**Comment by prem2204** [comment]
On a different note, 1 last clarification, I need to configure dkron cluster in production without docker. Even though I see some of the guys achieved this, but all the steps arent explicitly shared. Could you share some more info?

**Comment by ProPheT777** [comment]
simply with the go executable, with the same command run in docker, there are nothing related specifically to docker in fact.

executable package can be found here : https://github.com/victorcoder/dkron/releases

and command to run dkron are in the docs (nothing complicated) - https://dkron.io/basics/configuration/
