### ISSUE TITLE
Documentation on tags and roles is unclear

### ISSUE THREAD

**Issue by greggilbert** [victorcoder/dkron#418]
Hey. I'm a few versions behind, but this used to be a valid way of defining how a job gets run (in this case, on one `worker_server` node):

`{"role":"worker_server:1"}`

Is that still the case? If so, the documentation at https://dkron.io/usage/api/#job is really unclear on that:

```
Target nodes tags of this job  Example : {<br>  "string" : "string"<br>} | < string, string > map
```

Can that part of the documentation be clarified? 

Side question, is there a way to run a job on _every_ node? Is it `"worker_server:"all"` or something?

**Comment by victorcoder** [comment]
Sorry for the late reply @greggilbert, too busy.

Sure, api docs needs an improvement, I'll work on this in the following days.

Yes, to run on all nodes don't specify the count ex. `worker_server`

**Comment by victorcoder** [comment]
Updated API docs and examples
