### ISSUE TITLE
i suggest dkron support ISO8601 repeating  interval format  to schedule jobs refer to mesos/chronos

### ISSUE THREAD

**Issue by junneyang** [victorcoder/dkron#422]
the ISO8601 repeating  interval enables more flexibility in job scheduling
refer to mesos/chronos: https://mesos.github.io/chronos/docs/
refer to ISO8601: https://en.wikipedia.org/wiki/ISO_8601

thanks!

**Comment by victorcoder** [comment]
I evaluated this possibility during the initial design of Dkron and there is some things that I disliked in ISO8601 that I can't remember now.

Said that, it's a possible improvement I need to review it sometime in the future.
