### ISSUE TITLE
SetJob bug?

### ISSUE THREAD

**Issue by tengattack** [victorcoder/dkron#425]
As we can see the variable `ej` unlock immediately:
https://github.com/victorcoder/dkron/blob/6a254fcf9d5afb3fe25635fb908d3bececb1b723/dkron/store.go#L101-L106

**Comment by victorcoder** [comment]
This is probably a bug yup.

**Comment by victorcoder** [comment]
Fixed in https://github.com/victorcoder/dkron/commit/712be353a2d133f0bcf0c28b0852d27a395c4274
