### ISSUE TITLE
Issues leaving dkron cluster

### ISSUE THREAD

**Issue by kevynhale** [victorcoder/dkron#439]
1) Documentation shows `leave` is a `GET` request, which is wrong - it should be a `POST` request.

2) When I call the `leave` api I see the following in the logs:

> time="2018-09-13T18:36:55Z" level=info msg="[GIN] 2018/09/13 - 18:36:55 | 200 \x1b[0m|       92.97µs |             ::1 |  POST \x1b[0m    /v1/leave" node=c3r.scheduler.6-b5k7k
> time="2018-09-13T18:36:56Z" level=debug msg="agent: Received event" event=member-leave node=c3r.scheduler.6-b5k7k
> time="2018-09-13T18:36:56Z" level=debug msg="agent: Member event" event=member-leave member=c3r.scheduler.6-b5k7k node=c3r.scheduler.6-b5k7k

However, if I call the `members` api on the servers in the cluster they still show that that member is present in the cluster with a status 4... from what I can tell from serf that means `failed`.

Is there a way we can clean out old cluster members from the list?

**Comment by yebo29** [comment]
This may be the same as an issue I opened some time ago? See https://github.com/victorcoder/dkron/issues/392
