### ISSUE TITLE
how to check if job is executed 

### ISSUE THREAD

**Issue by rampredd** [victorcoder/dkron#442]
I started using dkron since a week.
Plese see the steps below what am running.
docker-compose up with only dkron and consul
docker-compose ps printing:
 Name                   Command               State                                               Ports  
dkron_consul_1   docker-entrypoint.sh agent ...   Up      0.0.0.0:32771->8300/tcp, 8301/tcp, 8301/udp, 8302/tcp, 8302/udp, 0.0.0.0:8500->8500/tcp,   8600/tcp, 8600/udp                                                                           
dkron_dkron_1    scripts/run agent --server ...   Up      0.0.0.0:32773->8080/tcp, 0.0.0.0:32772->8946/tcp

post job to dkron using curl:
curl --request POST localhost:32773/v1/jobs \
  -H "Content-Type: application/json" \
 \
  -d '{
  "name": "echojob",
  "schedule": "@every 4s",
  "shell": true,
  "command": "curl --request DELETE localhost:32773/v1/jobs/xyz",
  "owner": "ramprasad",
  "owner_email": "rpredd@gmail.com",
  "run_as_user": "ramprasad",
  "disabled": false,
  "tags": {
    "role": "my-role:1"
  }
}'

It shows following log
dkron_1   | time="2018-09-17T13:30:28Z" level=debug msg="agent: Done receiving acks and responses" node=08bb8c704093 query="run:job"
dkron_1   | time="2018-09-17T13:30:29Z" level=debug msg="scheduler: Run job" job=echojob node=08bb8c704093 schedule="@every 4s"
dkron_1   | time="2018-09-17T13:30:29Z" level=debug msg="store: Retrieved job from datastore" job=echojob node=08bb8c704093
dkron_1   | time="2018-09-17T13:30:29Z" level=debug msg="agent: Filtered nodes to run: []" node=08bb8c704093
dkron_1   | time="2018-09-17T13:30:29Z" level=debug msg="agent: Filtered tags to run: map[role:my-role:1]" node=08bb8c704093
dkron_1   | time="2018-09-17T13:30:29Z" level=debug msg="agent: Sending query" job_name=echojob json="{\"execution\":{\"job_name\":\"echojob\",\"started_at\":\"0001-01-01T00:00:00Z\",\"finished_at\":\"0001-01-01T00:00:00Z\",\"group\":1537191029000971074,\"attempt\":1},\"rpc_addr\":\"172.19.0.3:6868\"}" node=08bb8c704093 query="run:job"

expected log:
xyz job is not found

Please help

**Comment by yebo29** [comment]
I believe you are looking for https://dkron.io/usage/api/#get-jobs-job-name 
Simple REST API call

**Comment by victorcoder** [comment]
@rampredd you are trying to delete a non existent job?

**Comment by rampredd** [comment]
Thank you for the reply. 
Actually, I didn't understand working with docker images.
I can see this myself.

Please answer another query as follows:
I built both executor&processor plugins using golang and placed under the dkron folder that I expected to be called by the dkron scheduler.
I see in dkron logs that "cannot invoke plugin".

Please write steps how to do this.
OR
Let me know if need more logs.

**Comment by victorcoder** [comment]
@rampredd The best way you can learn to build your plugins is by looking at the current plugin code in https://github.com/victorcoder/dkron/tree/master/builtin/bins

Let me know if you need more help.
