### ISSUE TITLE
where i check my logs in dkron

### ISSUE THREAD

**Issue by Naresh314** [victorcoder/dkron#444]
hey, i create 1 sample job in cluster, but i am unable to see my logs in the server machine. How to see that logs.

**Comment by Naresh314** [comment]
Guys - Logs are keep updating on screen , Can any one let me know which option can be used to route logs specific file or location .

I am bit new to Linux any help will be appreciated.

**Comment by victorcoder** [comment]
Hi @Naresh314, yes logs are going to STDOUT, depending on your linux system you will have the logs in the systemd logging service `journald` you can view them using `journalctl` tool.

If you use a init v or an upstart based system you can redirect the command output to a file with the common linux shell idioms https://askubuntu.com/questions/420981/how-do-i-save-terminal-output-to-a-file/420983
