### ISSUE TITLE
Cannot unmarshal array

### ISSUE THREAD

**Issue by metanovii** [victorcoder/dkron#454]
**Hi, i try this job :**
{
	"name": "test_job",
	"command": "echo \"azaza\"",
	"schedule": "@every 2s",
	"tags": {
		"servername": ["node1", "node2", "node3"]
	}

**In log i have message :** 
`json: cannot unmarshal array into Go struct field Job.tags of type string  node=dkron-server`

**Comment by metanovii** [comment]
Sorry, this my mistake .

**Comment by victorcoder** [comment]
Tags are expected to be string: string

**Comment by victorcoder** [comment]
Closing it, feel free to reopen in case it doesn't work.
