### ISSUE TITLE
Node execution tasks are uneven

### ISSUE THREAD

**Issue by sanhuanshisanshao** [victorcoder/dkron#455]
hi, my job is this:

{
  "name": "job2",
  "schedule": "@every 3s",
  "tags": {
    "role": "web:1"
  },
  "concurrency": "allow",
  "executor": "shell",
  "executor_config": {
    "command": "echo \"Hello from parent\""
  },
}

 I have four node that tag is "web" but at most of time that my job alway run in a same node. 

<img width="1241" alt="wx20181108-105235 2x" src="https://user-images.githubusercontent.com/22467635/48174868-a298bc00-e344-11e8-90ac-9fab9e27de5e.png">

 I want to ask the reason，thanks.

**Comment by sysadmind** [comment]
I believe it's a side effect of how querries are built with tags. It's going to always pick the first N nodes that match the tag based on the ordering of `serf.Members()`. I think a better strategy might be to filter the members and then reduce the array in a random fashion. I don't know of a great way to pick a random assortment of size N from the array though. 

Here's where the nodes are filtered: https://github.com/victorcoder/dkron/blob/046b1a8d5cb6bb65aa3565a156e33110386d613f/dkron/agent.go#L553

**Comment by victorcoder** [comment]
I was about to point you to that code, I never had a preference for making it random but it could be a great improvement

**Comment by sanhuanshisanshao** [comment]
@sysadmind @victorcoder  thanks ,it's very helpful for me.
