### ISSUE TITLE
Why jobs running twice on cluster

### ISSUE THREAD

**Issue by duythien** [victorcoder/dkron#456]
Hello
When I setup a cron on cluster with data below
```
{
  "name": "job",
  "schedule": "@every 10s",
  "owner": "",
  "owner_email": "",
  "disabled": false,
  "tags": {},
  "retries": 0,
  "processors": null,
  "concurrency": "allow",
  "executor": "shell",
  "executor_config": {
    "command": "echo 123"
  }
}
```

When it's execute it seem running twice !

![screenshot_2018-11-08 dkron](https://user-images.githubusercontent.com/1762691/48182884-80f8fe00-e35f-11e8-941a-704741ec4777.png)

Could you explain it, It's should be running one time in leader and client dkron

**Comment by victorcoder** [comment]
This is how it should be @duythien, you have two nodes running and no defined tags for the job, so it will run in all nodes of the cluster.

Let me know if that doesn't make sense.

**Comment by duythien** [comment]
@victorcoder That's ok, but I also have a question to for example if I have define a tag "--tag node=node1" on node1 but for node2 I do not defined a tag, so that when we running a job with tag node1. It will work ok but I assume the node1 die so that is the job will die, right?
If yes how do running  high availability?

**Comment by victorcoder** [comment]
You could use target nodes count to solve your problem https://dkron.io/usage/target-nodes-spec/

For example, if you tag your nodes as `node=runner` and set the job tags to `node=runner:1` it will run in one of any available nodes in the cluster, this is how you achieve HA.

**Comment by luizpaisMD** [comment]
> You could use target nodes count to solve your problem https://dkron.io/usage/target-nodes-spec/
> 
> For example, if you tag your nodes as `node=runner` and set the job tags to `node=runner:1` it will run in one of any available nodes in the cluster, this is how you achieve HA.

"Page not found" -> https://dkron.io/usage/target-nodes-spec/

**Comment by vcastellm** [comment]
Docs updated https://dkron.io/docs/usage/target-nodes-spec
