### ISSUE TITLE
Web UI not working

### ISSUE THREAD

**Issue by swamyjsv** [victorcoder/dkron#459]
**OS:  Ubuntu 18.04
Go: go1.10.4 linux/amd64
Dkron v0.11.0-b2-next
Agent Protocol: 5 (Understands back to: 2)
etcd Version: 3.2.17**

i have installed dkron using sudo apt-get install dkron-unstable ( I tried stable version before and i still go the same issue) the REST API's see to wok fine, x.x.x.x:8080/v1 prints out 

{"agent":{"backend":"etcd","backend_status":"200","name":"x.x.x.x","version":"v0.11.0-b2-next"},"serf":{"encrypted":"false","event_queue":"0","event_time":"1","failed":"0","health_score":"0","intent_queue":"0","left":"0","member_time":"1","members":"1","query_queue":"0","query_time":"1"},"tags":{"dkron_rpc_addr":"x.x.x.x:6868","dkron_server":"true","dkron_version":"v0.11.0-b2-next"}}

**Comment by victorcoder** [comment]
Navigate to /dashboard to access the website.

**Comment by victorcoder** [comment]
@swamyjsv Feel free to reopen in case it doesn't work.

BTW I don't recommend to use `-next` versions from the unstable repo.
