### ISSUE TITLE
Dkron package issue

### ISSUE THREAD

**Issue by SubhransuMI** [victorcoder/dkron#461]
Currently, I have tried to create dkron plugin. I have imported all the dependent packages. So when I tried to run the project, I am getting some errors like below.
```
panic: /debug/requests is already registered. You may have two independent copies of golang.org/x/net/trace in your binary, trying to maintain separate state. This may involve a vendored copy of golang.org/x/net/trace.

goroutine 1 [running]:
go.etcd.io/etcd/vendor/golang.org/x/net/trace.init.0()
        /home/mind/go/src/go.etcd.io/etcd/vendor/golang.org/x/net/trace/trace.go:116 +0x16c
exit status 2
```
Is there any solution for this issue?

**Comment by victorcoder** [comment]
Are you using go modules to manage the dependencies of your plugin?

**Comment by SubhransuMI** [comment]
No, I am not using go modules, in stead I am using separate packages for it.

**Comment by victorcoder** [comment]
Go 1.11 implement go modules, Dkron is using to manage dependencies, if you use go modules to handle dependencies for your plugin this will probably fix your problem with vendoring.

Feel free to reopen in case it doesn't work

**Comment by SubhransuMI** [comment]
Thanks victor
