### ISSUE TITLE
Cron  executing successfully but not running at given interval 

### ISSUE THREAD

**Issue by SubhransuMI** [victorcoder/dkron#464]

**Comment by SubhransuMI** [comment]
I have used the apis https://dkron.io/api/ for executing jobs. The job is executing successfully and log is shown in log files, but it is not running again in background at given interval.
Do you have any solution for this issue?

**Comment by SubhransuMI** [comment]
Hi @victorcoder Does it need to restart the server every time I create/update jobs or is there any way of keep running the server in background? Because I am unable to run jobs in given interval without restarting the server.

**Comment by victorcoder** [comment]
Could you post your job, backend store and version here?

**Comment by SubhransuMI** [comment]
My job is like this
```
{
  "name": "job1",
  "timezone": "",
  "schedule": "@every 10s",
  "shell": false,
  "command": "",
  "environment_variables": null,
  "owner": "",
  "owner_email": "",
  "success_count": 8,
  "error_count": 0,
  "last_success": "2018-12-03T07:07:14.002354235Z",
  "last_error": "0001-01-01T00:00:00Z",
  "disabled": false,
  "tags": null,
  "retries": 0,
  "dependent_jobs": null,
  "parent_job": "",
  "processors": null,
  "concurrency": "forbid",
  "executor": "shell",
  "executor_config": {
    "command": "echo \"Hello from parent\""
  },
  "status": "success"
}
```

-Dashboard showing storage backend as boltdb
-In dkron.yml file it is showing as etcd
-backend-machine: 127.0.0.1:2379
-Dkron version - 0.11.3

**Comment by victorcoder** [comment]
Could you paste the log when setting `--log-level=debug`?
