### ISSUE TITLE
Job not executing at scheduled intervals

### ISSUE THREAD

**Issue by AshwinJd** [victorcoder/dkron#469]
Use this template if you are reporting a bug. Don't use this template of you are proposing a feature.

## Expected Behavior
It is not executing the Job every 10 secs though I mentioned the schedule. The Job executes only once. Every time I ve to manually click on play in dashboard Web UI to start the execution process

## Actual Behavior
{
  "name": "job1",
  "timezone": "",
  "schedule": "@every 10s",
  "shell": false,
  "command": "",
  "environment_variables": null,
  "owner": "",
  "owner_email": "",
  "success_count": 1,
  "error_count": 0,
  "last_success": "2018-12-05T11:30:38.317568475Z",
  "last_error": "0001-01-01T00:00:00Z",
  "disabled": false,
  "tags": {},
  "retries": 0,
  "dependent_jobs": null,
  "parent_job": "",
  "processors": null,
  "concurrency": "allow",
  "executor": "shell",
  "executor_config": {
    "command": "echo Hello Ashwin Hi from Job1!!"
  },
  "status": "success"
}

This is how im running the dkron
- docker run -d -p 8080:8080 --name dkron dkron/dkron agent --server

**Comment by victorcoder** [comment]
Related to https://github.com/victorcoder/dkron/issues/464
