### ISSUE TITLE
"404 page not found" on 127.0.0.1:8080

### ISSUE THREAD

**Issue by nicholasamorim** [victorcoder/dkron#475]
## Expected Behavior

To run DKron and see the dashboard on localhost:8080

## Actual Behavior

Happens both using image from dockerhub and by downloading .tar.gz (Mac) 

After I DKron is running, navigating to localhost:8080 shows a string "404 page not found"

## Steps to Reproduce the Problem

  1. Be on a Mac - maybe?
  1. Either run Docker with official README instructions or run the packaged download with `./dkron agent --server`
  1. Navigate to localhost:8080

## Specifications

  - Version: 1.0.0-rc2
  - Platform: Mac
  - Backend store: default

**Comment by victorcoder** [comment]
@nicholasamorim you should navigate to http://localhost:8080/dashboard it's probably a bit confusing, I'll try to improve this.

**Comment by victorcoder** [comment]
See https://github.com/victorcoder/dkron/pull/477

**Comment by nicholasamorim** [comment]
Thanks!

Yeah, documentation just stated to go to "localhost:8080"

Now it works!
