### ISSUE TITLE
dependent package checksum mismatch: etcd and go-rootcerts 

### ISSUE THREAD

**Issue by cobolbaby** [victorcoder/dkron#500]
## Expected Behavior

when switch to master branch, `go mod vendor` command could be successful

## Actual Behavior

An execption thrown with `go mod vendor` command execution

```
$ go mod vendor
go: downloading google.golang.org/genproto v0.0.0-20181202183823-bd91e49a0898
verifying github.com/coreos/etcd@v3.3.11+incompatible: checksum mismatch
        downloaded: h1:U0wJghY374q+UrjOM2mfROHSwEspsQVkCACB1PGka1g=
        go.sum:     h1:0gCnqKsq7XxMi69JsnbmMc1o+RJH3XH64sV9aiTTYko=
$ go mod vendor
go: downloading google.golang.org/genproto v0.0.0-20181202183823-bd91e49a0898
verifying go.etcd.io/etcd@v3.3.11+incompatible: checksum mismatch
        downloaded: h1:prXKQo4xKEXyroJpnfcYIf7j/3j3cSs0A3USXVeFU0I=
        go.sum:     h1:AVwRXu9VIzZcvVe1nSirTVkNv7WT3/hwdMRrDVFsf3A=
$ go mod vendor
go: downloading google.golang.org/genproto v0.0.0-20181202183823-bd91e49a0898
verifying github.com/hashicorp/go-rootcerts@v1.0.0: checksum mismatch
        downloaded: h1:ueI78wUjYExhCvMLow4icJnayNNFRgy0d9EGs/a1T44=
        go.sum:     h1:Rqb66Oo1X/eSV1x66xbDccZjhJigjg0+e82kpwzSwCI=
```

## Steps to Reproduce the Problem

  1. When execute `go mod vendor`, an exception is thrown

## Specifications

  - Version: Go1.11, Go1.12
  - Platform: Ubuntu
  - Backend store:

**Comment by victorcoder** [comment]
No problems on my side with the checksum, tested in macos and linux using docker, could you run `go clean -modcache` and try it again?

**Comment by cobolbaby** [comment]
Thanks. 

`go clean -modcache` works, although I need to download again.

**Comment by andy9775** [comment]
I'm also getting this error except for:
```
verifying github.com/hashicorp/go-rootcerts@v1.0.0: checksum mismatch
	downloaded: h1:ueI78wUjYExhCvMLow4icJnayNNFRgy0d9EGs/a1T44=
	go.sum:     h1:Rqb66Oo1X/eSV1x66xbDccZjhJigjg0+e82kpwzSwCI=
```

`go clean -modcache` returns:
```
verifying go.etcd.io/etcd@v3.3.11+incompatible: checksum mismatch
	downloaded: h1:prXKQo4xKEXyroJpnfcYIf7j/3j3cSs0A3USXVeFU0I=
	go.sum:     h1:AVwRXu9VIzZcvVe1nSirTVkNv7WT3/hwdMRrDVFsf3A=
```

**Comment by victorcoder** [comment]
Also using 1.12 on darwin, but `go clean -modcache` doesn't return anything. I can not reproduce it.

Could you try to remove all etcd entries in go.sum and try it again?

**Comment by andy9775** [comment]
Hmm. Got another issue but deleted the offending entries, rebuilt the go.sum (nothing changed) and it looks to be working now.

Thanks!
