### ISSUE TITLE
How to create an instant job?

### ISSUE THREAD

**Issue by talexu** [victorcoder/dkron#509]
## Expected Behavior
Create a job, the job will run once immediately.

## Actual Behavior
Create a disabled job, then invoke API  to run the job, which means that I have to invoke two APIs (POST /jobs, POST /jobs/{job_name}) for instant job.

## Specifications

  - Version: 1.2.0
  - Platform: Mac
  - Backend store: Redis

**Comment by victorcoder** [comment]
@talexu I don't know if dkron will be the best tool for that use case but you can submit a job to be run in the next few seconds:

```
run_next=`date '+%FT%T:Z' --date='5 seconds'`

curl localhost:8080/v1/jobs -d "{
  "name": "job1",
  "schedule": "@at $run_next",
  "disabled": true,
  "executor": "shell",
  "executor_config": {
    "command": "echo 'Hello from Dkron'"
  }
}"
```

**Comment by talexu** [comment]
> @talexu I don't know if dkron will be the best tool for that use case but you can submit a job to be run in the next few seconds:
> 
> ```
> run_next=`date '+%FT%T:Z' --date='5 seconds'`
> 
> curl localhost:8080/v1/jobs -d "{
>   "name": "job1",
>   "schedule": "@at $run_next",
>   "disabled": true,
>   "executor": "shell",
>   "executor_config": {
>     "command": "echo 'Hello from Dkron'"
>   }
> }"
> ```

@victorcoder Thank you for your reply. What I am going to develop is a cross-region job schedule system. Each job in a job chain may be run in different data center.
Could you please give me some advices about how to design and implement such kind of system (e.g. framework, storage, infrastructure)

**Comment by victorcoder** [comment]
@talexu For an implementation cross-region I would recommend using DynamoDB global table for the backend on AWS and configure 2 dkron clusters in an active-passive fashion, you can work something like that using tags and the proper configuration.
