### ISSUE TITLE
Question about owner fields

### ISSUE THREAD

**Issue by viperfx** [victorcoder/dkron#517]
What is the `owner_email` and `owner` field for? Can I set them to anything for task readability purposes?

Or should I assume these users will be emailed by dkron at some point? (I do not want this to happen).

**Comment by victorcoder** [comment]
@viperfx `owner_email` is the email account where the result email will be sent if email notifications are configured.

The `owner` field is just a id field if you want/need to assign an owner to a job for reporting or auditing purposes.

Just ignore them if you don't need it.
