### ISSUE TITLE
Cannot use uppercase letters or symbols in job names

### ISSUE THREAD

**Issue by thavlik** [victorcoder/dkron#519]
## Expected Behavior
I should be able to use any utf-8 characters in a job name, and encodeURIComponent/decodeURIComponent are used when interfacing with the API.

## Actual Behavior
A name like `#HeLLo@@WorLd$` becomes `helloworld`, and you will not be able to delete the job using the same name passed into the DELETE endpoint. If dkron insists on doing things this way, expected behavior entail DELETE transforming the job name just as when it is posted.

The following jest test code passes, demonstrating the error:

```

describe("dkron", () => {
    it("does not work with characters or uppercase", async done => {
        const dkron = Axios.create({
            baseURL: "http://localhost:8080/v1/jobs",
            method: "POST",
        });

        const name = "#HeLLo@@WorLd$"

        console.log(`name = ${name}`);

        // Create a job with that name
        const res = await dkron.post("/", {
            name,
            schedule: `@every 10s`,
            owner: "myself",
            disable: false,
            tags: {
                role: "web:1"
            },
            executor: "http",
            retries: 5,
            executor_config: {
                method: "GET",
                url: `http://localhost:4040/${encodeURIComponent(name)}/`,
                headers: "[]",
                body: "",
                timeout: "30",
                expectCode: "200",
                expectBody: "",
                debug: "true"
            }
        });
        expect(res.status).toBe(201);
        let err: any;
        try {
            await dkron.delete(`/${encodeURIComponent(name)}`);
        } catch (_err) {
            err = _err;
        }
        expect(err).toBeTruthy();
        expect(err.message).toBe("Request failed with status code 404");
        
        done();
    });
});
```

## Steps to Reproduce the Problem

  1. Post a job name with uppercase and/or non-alphanumeric characters
  2. View the name of the job in the web console 
  3. Try and fail to delete the job using the job name you provided dkron with

## Specifications

  - Version: 
```
>  dkron version
Dkron 1.2.2
Agent Protocol: 5 (Understands back to: 2)
```
Platform: Debian 9 (Stretch) AMD64
Backend store: BoltDB

**Comment by thavlik** [comment]
As a workaround, you can sanitize the job name sent to both endpoints using:
```
jobName = jobName.toLowerCase().replace(/\W/g, "");
```

**Comment by victorcoder** [comment]
Hi @thavlik, job names are sanitized before storing it, this means that the original name is changed, and the actual job name won't be the original provided one anymore.

To delete the job you will need to use its actual name.

Won't be difficult to sanitize also the name passed to DELETE, I will accept a PR for that.

**Comment by yvanoers** [comment]
While I definitely agree that the API should be consistent in how it accepts its input values, I think it would be better to reject an incorrect name rather than sanitizing it. That way, the client and server are forcibly aligned on the identifier. It would avoid scenarios where a clients thinks jobs '#hello' and 'hello' are different while they're the same to dkron.

I see two ways of going about this:
Either start rejecting new jobs that have names with unacceptable characters,
or start accepting any and all characters in the name.

Both have the downside of being backward incompatible with the current behavior.

@victorcoder I'm interested to learn if there was any specific reason for sanitizing the job name?

**Comment by thavlik** [comment]
I was using a base64 encoded value as the job name. Base32-encoded job names are a compatible alternative to base64 in my case.

**Comment by yvanoers** [comment]
I am still interested in creating a PR for this.
A way around the backward incompatibility I mentioned would be to add a flag to the server configuration that enables the new behavior if set (and defaulting to current behavior).

Would like to know if @victorcoder thinks this is still worth implementing. And what, exactly.

**Comment by victorcoder** [comment]
@thavlik the specific reason to sanitize the name is to have a valid key/path for KV stores.

encoding would complicate things a lot.

@yvanoers I would accept a PR for either rejecting the job creation or sanitizing the delete operation
