### ISSUE TITLE
Having node acting as failover

### ISSUE THREAD

**Issue by educlos** [victorcoder/dkron#521]
Hi!
Here is the scenario I'd like to do:
Let's say I have 3 nodes, A, B and C, and a job J.
By default I want J to run on A, but if for some reason A cannot run the job / left the cluster, then J can run on B or C. And as soon as A is available again it re-start running on it.
I looked into the code and it doesn't seem like a possibility for the moment.
Do you think adding some optional "failover_tags" on a job or something could be an idea?

**Comment by victorcoder** [comment]
Hi @educlos, what you can do with tags is to run the job in just one of A/B/C and if one fails, it will run on any other available one.

Why do you want to have other nodes without doing no work at all all the time?

**Comment by educlos** [comment]
In our case it's actually to avoid having nodes doing no work most of the time that we'd like to setup some as "failover".
We have a very resource consuming job that runs on a dedicated machine (A). We also have other machines on the side (B and C), doing other jobs. What we'd like is that in case something happen to A, the job starts running on B or C, giving us time to see what's up with A and put it back up. But we don't want the job to run on B or C if A is up, as it's a heavy one and B and C already have some work to do.
And I don't see a way to do it with the current tag system.
I hope it's clear.

**Comment by victorcoder** [comment]
@educlos I understand, and this won't be possible to do that at this point.

Regarding "failover_tags" it will be more like a path to solve your use case, I prefer to implement something more generic that can cover your use case too. I have some ideas but still not implementing it.
