### ISSUE TITLE
cannot unmarshal object into Go struct field Job.executor_config of type string

### ISSUE THREAD

**Issue by Kunze** [victorcoder/dkron#523]
Use this template if you are reporting a bug. Don't use this template of you are proposing a feature.

## Expected Behavior
it should create a job

## Actual Behavior
json: cannot unmarshal object into Go struct field Job.executor_config of type string

## Steps to Reproduce the Problem

curl --request POST \
  --url http://localhost:8080/v1/jobs \
  --header 'content-type: application/json' \
  --data '{
    "name": "job1",
    "schedule": "@every 10s",
    "timezone": "Europe/Berlin",
    "owner": "Platform Team",
    "owner_email": "platform@example.com",
    "disabled": true,
    "tags": {
        "dkron_server": "true"
    },
    "retries": 2,
    "concurrency": "allow",
    "executor": "http",
    "executor_config": {
        "method": "POST",
        "debug": "true",
        "url": "http://xxxxxx",
        "body": {
            "fromAddress": "noreply@xxxxxx.com",
        }
    }
}'

Dkron 1.2.2

**Comment by yvanoers** [comment]
The value of the "body" field in the executor_config in your example is a JSON object. The executor_config can only receive a string.
Does it accept it if you use this:
...
"body": "fromAddress=noreply@xxxxxx.com",
....
You may need to change the formatting of the body depending on what the receiving end expects.

**Comment by victorcoder** [comment]
Could we consider this doubt solved?

**Comment by Kunze** [comment]
@victorcoder yes, thanks guys.
