### ISSUE TITLE
server value from config json is not used

### ISSUE THREAD

**Issue by whizz** [victorcoder/dkron#53]
If you specify a "server" option (set to true) in the configuration json, it is ignored. Only command line option works. Not sure if it is a bug or a feature, but the docs state, that all command line options can be set in the config file.

**Comment by victorcoder** [comment]
This is weird, I'm using the `server` flag in the JSON config in production and it's working well.

Could you show your config here?

**Comment by whizz** [comment]
This was my bad. You are right, it works correctly. Sorry for the noise.
