### ISSUE TITLE
Feature request: delayed execution of scheduled job on specific labelled node when node was down

### ISSUE THREAD

**Issue by fwdIT** [victorcoder/dkron#534]
My situation is as follows, some jobs can only run on nodes with a certain role. These nodes can be down at times.
As far as I read I don't see a feature to run a failed job as soon as the node comes alive. For instance, I want to run a certain job once a day at 10am. If the node only comes up at 11am that day, the job won't run anymore in the current setup.
Would it be possible / interesting to add a flag to try to run the past job as soon as the node comes up ? The retries option just has a count but no delay. I saw another feature request about exponential delays which would be an option to solve my problem but it would be cleaner when the dkron service itself can decide to retry running jobs which were scheduled when the dkron service was down on that node.

**Comment by fwdIT** [comment]
As I see after some testing, that would mean the master node(s) should start queueing jobs for nodes which are down.
The jobs which are targeted on nodes which are down / left the cluster don't seem to get a 'failed' status, they are just ignored.

**Comment by fwdIT** [comment]
I looked through all the Issues before logging this but it seems what I suggest is in one of the pull requests already:
https://github.com/victorcoder/dkron/pull/382
Hope this gets through

**Comment by victorcoder** [comment]
As said in that issue, this is not a trivial change, I bet for going with the exponential retries first.

Thanks @fwdIT

**Comment by fwdIT** [comment]
@victorcoder exponential retries might indeed also work. I'm just afraid that when agents are not up/online that much, the time periods they are actually up and ready the jobs which are in exponential retry attempt status might have such a large exponential retry schedule already that they will fall out of the time period the agents are online making these jobs still not having ran even though the agents were online.
