### ISSUE TITLE
agent nodes don't seem to retry joining the cluster when single master are down while the agent service starts

### ISSUE THREAD

**Issue by fwdIT** [victorcoder/dkron#536]
## Expected Behavior
agent nodes retrying to join the cluster on the specified master (dkron_server) IP address when this was down at initial agent service startup

## Actual Behavior
agent nodes never appear in the cluster again. only when restarting the agent nodes which point to the join IP address which was down before, makes them join the cluster again

however, agents which kept running when the master node was down, rejoin as soon as the master node is up again

## Steps to Reproduce the Problem

  1. shutdown agent node
  2. shutdown master node
  3. restart agent node pointing with a join to (only) this master (dunno if I can give it joins to other agent nodes and if this would give a different result)

## Specifications

  - Version: 1.2.2
  - Platform: macos
  - Backend store: default

**Comment by victorcoder** [comment]
@fwdIT please note that the default store, BoltDB, doesn't allows clustering and leader election. It's for working in a single node setup.

**Comment by fwdIT** [comment]
@victorcoder thanks for the feedback, I missed that part, sorry. I will try to do some more tests with another backend store. Was planning on setting up Consul anyways. When my master node is up in the current setup all agent nodes do connect and tasks are run as scheduled.
