### ISSUE TITLE
@every schedule execution is updated by page refresh

### ISSUE THREAD

**Issue by knightsg** [victorcoder/dkron#546]
## Expected Behavior
Setting an @every (eg. "@every 10m) schedule for a command at a specific time will result in that command executing every 10m from the time it was originally added.

## Actual Behavior
If you have a command schedule using @every, every time you refresh the jobs list page the next execution time for that job will change as though the job had just been added, and the job will actually execute at the new "next execution" time.

For example:

For this schedule -

`
echo-date | @every 10m | 268 | 0 | 2019-06-14 09:20:59 -0700 | 2019-06-14 10:23:41 -0700`

Say you refresh the page at 10:15:37, the next execution time will update from 10:23:41 to 10:25:37. It's not just the display of the execution time either, the job will actually run at the changed execution time.

Note: This only happens with @every - for example @hourly does not show this behaviour. Also, the debug log does not show anything when the page refresh and execution time update happens.

## Steps to Reproduce the Problem

  1. Add a job using the @every schedule definition. Note the time it was added.
  2. Wait a minute or so.
  3. Open the jobs page and confirm the current time. 
  4. Check the "next execution" field for the job, it should be the page open time plus whatever value you set for the "@every" schedule (eg. 10 mins from when the page was opened).
  5. Refresh the page a few more times and note the next execution time has changed each time.

## Specifications

  - Version: 1.2.4
  - Platform: Ubuntu 18.04.02
  - Backend store: BoltDB

**Comment by victorcoder** [comment]
This is weird, I will investigate it, thanks for reporting @knightsg

**Comment by knightsg** [comment]
Quick update, we also noticed this with the @at jobs as well. Same behaviour, refreshing the page will update the next execution status relative to the time the page was refreshed.

However, since @at jobs seem to have their next execution status set to 10 years from when their execution time our assumption is that this may be intended behaviour. Perhaps this is somehow responsible for the same behaviour with the @every schedule type?

**Comment by victorcoder** [comment]
Bug detected, the way next schedules are calculated are not ok. I'll try to fix it.

**Comment by fopina** [comment]
does this affect every `@every` / `@at` job? because I'm using dkron with about 50-100 jobs all in these conditions and never noticed it, though I don't use the web UI very much. any details on the bug conditions?

**Comment by knightsg** [comment]
We've only been working with Dkron for a relatively short time (a few weeks) so I certainly can't say whether it happens in all cases, but we've set up a few @every/@at jobs and all of them seem affected by it.

Initially we only had one node setup using BoltDB so I thought maybe it could be related to that setup specifically, but we've since replaced that with a cluster using etcd and the same behaviour is observed.

**Comment by victorcoder** [comment]
@fopina yes it is affecting all `@every/@at` it is the way the next execution is calculated when reloading the UI or requesting job in the API.

Said that, the bug was introduced in v1.2.0

FYI it is fixed in v2, I need to rollout some fix for v1.

**Comment by victorcoder** [comment]
FTR: From looking gain at the code and from my tests doesn't indicate that the actual run time is affected just the displayed time.
