### ISSUE TITLE
Get jobs is very slow

### ISSUE THREAD

**Issue by oscar123mendoza** [victorcoder/dkron#547]
Hello,

This is more of a simple question and Im just hoping to get pointed in the right direction. Right now I am using `Dkron v0.10.2` and `Consul` as the backend. I only have around 100 jobs and when I try to use the API to get the jobs it takes around 10 seconds and there is almost no load on the node. Im noticing a super high amount of network traffic so I was wondering if anyone has ran into this.

This came to my attention because the web UI pulls in all the jobs every few seconds and the refresh rate is faster than the jobs coming back.

**Comment by victorcoder** [comment]
Hi @oscar123mendoza several fixes related to this has been released in more recent versions. Could you try with latest release?

**Comment by victorcoder** [comment]
Closing in the meantime, feel free to reopen if the issue persist.
