### ISSUE TITLE
dkron error on v2 docker version

### ISSUE THREAD

**Issue by saeedmsdi** [victorcoder/dkron#559]
I have got `422 Unprocessable Entity` status code :

<img width="1419" alt="Screen Shot 1398-04-09 at 17 47 20" src="https://user-images.githubusercontent.com/3229325/60397233-dc326780-9b5f-11e9-97f3-1379e2e1902c.png">

and this is the logs : 

<img width="1438" alt="Screen Shot 1398-04-09 at 17 50 49" src="https://user-images.githubusercontent.com/3229325/60397235-e6ecfc80-9b5f-11e9-9771-a552220e7e11.png">

I used your docker v2 tag

**Comment by yvanoers** [comment]
@saeedmsdi Could you please share the entire body you're POSTing to dkron (in text)? The screenshot is not showing the entire body and the part that is visible is accepted by dkron built from HEAD of the v2.x branch.

Please note that I am assuming you expect a 201 Created response instead of a 422.

**Comment by saeedmsdi** [comment]
```
{
  "name": "c0de",
  "schedule": "@minutely",
  "timezone": "Asia/Tehran",
  "owner": "Invoice",
  "owner_email": "princedotnet@gmail.com",
  "disabled": true,
  "tags": {},
  "retries": 2,
  "parent_job": null,
  "processors": null,
  "concurrency": "allow",
  "executor": "http",
  "executor_config": {
    "body": "",
    "debug": "true",
    "expectBody": "",
    "expectCode": "404",
    "headers": "[]",
    "method": "GET",
    "timeout": "30",
    "url": "https://api.payping.ir"
  }
}
```

it works on v1.x and I get 201

**Comment by yvanoers** [comment]
Creating this job works for me with v2.x HEAD.

@saeedmsdi On which OS are you running v2?
And on which OS are you running v1?

**Comment by victorcoder** [comment]
@saeedmsdi if you navigate to the UI, is there a leader elected?

I guess your setup is not electing a leader because the cluster is not initialized.

Try to run it with `docker run -p "8080:8080" dkron/dkron agent --server --bootstrap-expect=1`, and check it again.

**Comment by saeedmsdi** [comment]
> Try to run it with `docker run -p "8080:8080" dkron/dkron agent --server --bootstrap-expect=1`, and check it again.

thanks it works. but it doesn't need on v1.x.

but another q : on docker version volume not worked.

```
  volume_mounts:
    - mount_path: /dkron.db
      sub_path: dkron
```

this is what I used before and the db file stored on it. but on v2 I think it changed, yes ?

**Comment by victorcoder** [comment]
> thanks it works. but it doesn't need on v1.x.

no, v2 is quite different from v1

this is what I used before and the db file stored on it. but on v2 I think it changed, yes ?

Yes, you can specify the `--data-dir` in v2, by default it's `./dkron.data` directory

**Comment by saeedmsdi** [comment]
> Yes, you can specify the `--data-dir` in v2, by default it's `./dkron.data` directory

@victorcoder db files moved to the directory but by on every redeploy it creates new files :

<img width="1154" alt="Screen Shot 1398-04-10 at 13 01 38" src="https://user-images.githubusercontent.com/3229325/60422354-14d64d80-9c01-11e9-82ed-7e683e72c114.png">

<img width="1153" alt="Screen Shot 1398-04-10 at 13 01 01" src="https://user-images.githubusercontent.com/3229325/60422358-156ee400-9c01-11e9-8f58-4e4b8d1e192c.png">

and I used these commands : 
```
  command:
    - '/opt/local/dkron/dkron'
    - agent
    - '--server'
    - '--bootstrap-expect=1'
    - '--data-dir=/dkron.db'
```

but again there is not any LEADER

<img width="535" alt="Screen Shot 1398-04-10 at 13 08 19" src="https://user-images.githubusercontent.com/3229325/60422482-5ebf3380-9c01-11e9-93d7-bd436794cc51.png">

**Comment by victorcoder** [comment]
@saeedmsdi yes, because it creates a different data directory for each node-name, node-names are uniq in a cluster, by default it is the hostname, but docker assign a new hostname on each restart, if you want to maintain the node-name between restarts you can use `node-name` param in the config:

```
command:
    - '/opt/local/dkron/dkron'
    - agent
    - '--server'
    - '--bootstrap-expect=1'
    - '--data-dir=/dkron.data'
    - '--node-name=node1'
```

Let me know if that works

**Comment by saeedmsdi** [comment]
> Let me know if that works

Works! hanks
