### ISSUE TITLE
V2 database

### ISSUE THREAD

**Issue by fopina** [victorcoder/dkron#562]
Sorry for not following the template but this is more a question than an issue.

Is it still possible to use etcd in v2?

My current setup is that dkron is deployed together with my application, one on each node. Every node is server/agent and using an etcd instance in a separate server.

When deploying, the rolling update doesn’t need to care about cluster management as data is kept outside, so simply creates new cluster and destroys old one (small check script to make sure no jobs are running at the moment in the cluster to-be-removed).

If v2 only supports boltdb+raft that means I’ll have to update that process to carefully add the new nodes to existing cluster, let it sync data and then properly remove old nodes (so quórum doesn’t fail with non-existing nodes).

Is this correct?

**Comment by victorcoder** [comment]
@fopina yes, it is. I understand your concern regarding your current setup, v1 is really a stateless application, but with v2 you need to think in dkron as you think in etcd or consul, it's a stateful service and should be stable enough.

Then probably you won't need to worry about jobs-running checks.

Hope it clarifies the question.

**Comment by fopina** [comment]
It does, I just have to refactor the dkron integration in the app as it uses shell commands of the app code which requires a dkron redeploy when app is updated as well. I’ll try to change the setup to do the same command but over ssh :)

**Comment by victorcoder** [comment]
@fopina What do you think in using dkron clients alongside your app, this is a good use case, those are stateless and can be targeted to run from the servers.

**Comment by fopina** [comment]
So instead of running server/agents I would deploy only servers separate and keep my current setup without the server flag? Would definitely make it simpler yes, though I don’t dislike having them run the commands over ssh. Thanks for the suggestion!
