### ISSUE TITLE
How to configure a cluster

### ISSUE THREAD

**Issue by zieckey** [victorcoder/dkron#59]
I have done it like this:
In one console:
$ ./etcd

And in another console
$ ./dkron agent -server -debug=true -backend-machine=127.0.0.1:2379

That is all ok, I can create jobs and run jobs. But when I try to join anther agent to this server to build a cluster, I don't know where it is wrong. Here is what I do:

I do the following steps on anoter machine:
<pre>
 $ ./dkron agent -backend-machine=10.16.28.17:2379 -debug=true                                              
 Starting Dkron agent...
 INFO[2015-12-18T19:27:09+08:00] agent: Dkron agent starting                  
 INFO[2015-12-18T19:27:09+08:00] agent: joining: [127.0.0.1:5001 127.0.0.1:5002] replay: true 
 WARN[2015-12-18T19:27:09+08:00] agent: error joining: dial tcp 127.0.0.1:5002: getsockopt: connection refused 
 INFO[2015-12-18T19:27:09+08:00] agent: Listen for events                     
 DEBU[2015-12-18T19:27:10+08:00] agent: Received event                         event=member-join
</pre>

It don't work. I try to set the 'join' parameter as following:
<pre>
$ ./dkron agent -backend-machine=10.16.28.17:2379 -debug=true -join="10.16.28.17:5001"
Starting Dkron agent...
INFO[2015-12-18T19:29:33+08:00] agent: Dkron agent starting                  
INFO[2015-12-18T19:29:33+08:00] agent: joining: [127.0.0.1:5001 127.0.0.1:5002] replay: true 
WARN[2015-12-18T19:29:33+08:00] agent: error joining: dial tcp 127.0.0.1:5002: getsockopt: connection refused 
INFO[2015-12-18T19:29:33+08:00] agent: Listen for events                     
DEBU[2015-12-18T19:29:34+08:00] agent: Received event                         event=member-join
</pre>
It don't work either.

Thanks a lot.

**Comment by victorcoder** [comment]
As specified in docs, dkron binds by default in port `:8946` and in the second machine you're specifying `:5001`, just put the other machine IP without port to use the default.

Feel free to reopen if doesn't work

**Comment by zieckey** [comment]
Thanks.

I tried it but it did not work.
I think the problem is that the 'join' parameter does not work. 
You can see above that I set '-join="10.16.28.17:5001"', but the debug log showing as "INFO[2015-12-18T19:29:33+08:00] agent: joining: [127.0.0.1:5001 127.0.0.1:5002] replay: true ". The ip is 127.0.0.1 but not 10.16.28.17 which I set it.

Thanks again.

PS: Can you give more example on your documents (http://dkron.io/docs/getting-started/) ?

**Comment by zieckey** [comment]
I find that the configure item in the config file has a higher priority than command line flag. So when I changed the join parameter from "127.0.0.1:5001" to "10.16.28.17:8946" in the config file, that works.

Thanks a lot.

**Comment by sydcanem** [comment]
I find it hard to clusterize dkron when it is in a docker container. Adding `-join` option will make it easy configuring the cluster when running dkron with docker.
