### ISSUE TITLE
Cluster missing executions

### ISSUE THREAD

**Issue by Luzifer** [victorcoder/dkron#71]
> As an administrator of a dkron cluster I want my users to have a reliable cron system which guarantees "at least once" execution of their cron tasks.

## My setup:

3 AWS EC2s running CoreOS stable, all three machines being part of an etcd cluster, all three machines running dkron 0.6.3 as a cluster. All machines does have `role: executor` tag and the following cron:

```json
{
	"name": "date",
	"schedule": "0 */5 * * * *",
	"command": "/usr/bin/date",
	"owner": "Knut Ahlers",
	"owner_email": "knut****.com",
	"run_as_user": "core",
	"success_count": 58,
	"error_count": 0,
	"last_success": "2016-02-05T10:45:00.00621402Z",
	"last_error": "0001-01-01T00:00:00Z",
	"disabled": false,
	"tags": {
		"role": "executor:1"
	}
}
```

## Expected result:

The cron is executed every 5 minutes and will succeed every single time as it just calls `/usr/bin/date` (which is the location of the `date` utility on CoreOS).

## Observed result:

The task is sent to one of the machines every 5 minutes and gets eventually executed. The cron is missing several executions having no end date, no running `date` utility on the machine and a `failed` state.

![screen shot 2016-02-05 at 11 43 02](https://cloud.githubusercontent.com/assets/20142/12844321/e8ecdfb6-cbfe-11e5-97f1-5d18b5388a49.png)

## Question

Can you help me with this / tell me what I'm doing wrong? Is there anything I can do to prevent this?

**Comment by victorcoder** [comment]
Weir one, could you plese enable the debug flag and send me the log of the three nodes? Thanks!

**Comment by Luzifer** [comment]
Found an interesting part in the logs: I did not have a rule in the firewall configuration for that cluster to allow connections on port 6868 (RPC). After opening that port I get reports for all runs until now. Though there are jobs assigned to a machine which left the cluster after it left. In that case the job just vanishes and is not recorded in the interface…

**Comment by victorcoder** [comment]
@Luzifer both things makes sense

> allow connections on port 6868 (RPC)

This is necessary for the clients to send back execution reports with a tolerable size as serf doesn't support large messages (yet) I'll make a statement in the docs.

Regarding the vanished executions due to autoscaling, this is a good catch! indeed a bug, I missed the status when getting the cluster members.

Expect a hotfix release the following days.
