### ISSUE TITLE
scheduling mismatch tags with same prefix

### ISSUE THREAD

**Issue by schemacs** [victorcoder/dkron#77]
I have two servers, one has role of **vpnserver** and another **vpnserver2**, after posting a job targeting tags **vpnserver**, both servers got scheduled.

> curl 127.0.0.1:8080/v1/members | python -m json.tool
> [
>     {
>         "Addr": "10.0.0.9",
>         "DelegateCur": 4,
>         "DelegateMax": 4,
>         "DelegateMin": 2,
>         "Name": "h1",
>         "Port": 8946,
>         "ProtocolCur": 2,
>         "ProtocolMax": 2,
>         "ProtocolMin": 1,
>         "Status": 1,
>         "Tags": {
>             "key": "xxx1",
>             "role": "vpnserver2",
>             "server": "true"
>         }
>     },
>     {
>         "Addr": "10.0.0.1",
>         "DelegateCur": 4,
>         "DelegateMax": 4,
>         "DelegateMin": 2,
>         "Name": "h2",
>         "Port": 8946,
>         "ProtocolCur": 2,
>         "ProtocolMax": 2,
>         "ProtocolMin": 1,
>         "Status": 1,
>         "Tags": {
>             "key": "xxx2",
>             "role": "vpnserver",
>             "server": "true"
>         }
>     }
> ]
> 
> curl -n -X POST 127.0.0.1:8080/v1/jobs \
>   -H "Content-Type: application/json" \
>  \
>   -d '{
>   "name": "uptime",
>   "schedule": "0 30 \* \* \* *",
>   "command": "uptime",
>   "tags": {
>     "role": "vpnserver"
>   }
> }'

**Comment by victorcoder** [comment]
@schemacs note that you can use curl `127.0.0.1:8080/v1/members?pretty`

Could you post an extract of the execution results? `127.0.0.1:8080/v1/executions/uptime?pretty`

**Comment by schemacs** [comment]
Thanks, below is what I got after calling the api: 

> [
>         {
>                 "job_name": "uptime",
>                 "started_at": "2016-02-26T09:30:00.293483665+08:00",
>                 "finished_at": "2016-02-26T09:30:00.318768786+08:00",
>                 "success": true,
>                 "node_name": "h1",
>                 "group": 1456450200000444958,
>                 "job": {
>                         "name": "uptime",
>                         "schedule": "0 30 * * * *",
>                         "command": "uptime",
>                         "owner": "",
>                         "owner_email": "",
>                         "run_as_user": "",
>                         "success_count": 61,
>                         "error_count": 2,
>                         "last_success": "2016-02-26T03:30:00.162201195+08:00",
>                         "last_error": "2016-02-24T11:30:00.054647671+08:00",
>                         "disabled": false,
>                         "tags": {
>                                 "role": "vpnserver"
>                         }
>                 }
>         },
>         {
>                 "job_name": "uptime",
>                 "started_at": "2016-02-26T09:30:00.29503619+08:00",
>                 "finished_at": "2016-02-26T09:30:00.802353918+08:00",
>                 "success": true,
>                 "node_name": "h2",
>                 "group": 1456450200000444958,
>                 "job": {
>                         "name": "uptime",
>                         "schedule": "0 30 * * * *",
>                         "command": "uptime",
>                         "owner": "",
>                         "owner_email": "",
>                         "run_as_user": "",
>                         "success_count": 61,
>                         "error_count": 2,
>                         "last_success": "2016-02-26T03:30:00.162201195+08:00",
>                         "last_error": "2016-02-24T11:30:00.054647671+08:00",
>                         "disabled": false,
>                         "tags": {
>                                 "role": "vpnserver"
>                         }
>                 }
>         },
> ...
> ]

**Comment by victorcoder** [comment]
This looks weird, I'm also fixing another issue that can be related but I'm not sure, I need to do some tests. I'll keep you updated.

**Comment by victorcoder** [comment]
Fixed in https://github.com/victorcoder/dkron/pull/322
