### ISSUE TITLE
Plugable job types

### ISSUE THREAD

**Issue by victorcoder** [victorcoder/dkron#78]
This is an open discussion on how to implement different job types.

Some use cases won't need or don't benefit from shell execution and specially with lots of jobs.

**Comment by whizz** [comment]
I could imagine use cases for HTTP jobs, which would just send a HTTP request of given type (POST/GET/...) to given URL with optional payload. Though this can be pretty easily be done with current shell jobs + curl. 

The question is, whether dkron is a system that has ambition to handle job volume on the order of hundreds per second or more, where the added overhead of executing curl would be of concern.

**Comment by victorcoder** [comment]
I could imagine another one to run docker containers. But again I'm with you @whizz it's very easy to do it using the command line.

> The question is, whether dkron is a system that has ambition to handle job volume on the order of hundreds per second or more, where the added overhead of executing curl would be of concern.

Good question, I would say no, at this point it's not ready to handle this volume. The main bottleneck would be the storage backend.

**Comment by seiffert** [comment]
We would definitely be interested in this feature! Right now, we are using dkron behind our own API (of an internal PaaS for our developers), and use the dkron jobs only to schedule executions of our own command line tool which runs Docker containers on our clusters. 
With the ability to implement our own job types, we could teach dkron to talk to our PaaS' API directly (I guess). :+1:

**Comment by sercand** [comment]
What about adding gRPC job executors, service definition would be something like below
```
message Execution {
	// JobName to execute
    string job_name = 1;
    // Payload is data for the job, Dkron currently does not support this
    bytes payload = 2;
}
message ExecutionResult{
    // Partial output of the execution
    bytes output = 1;
}
service DkronExecutor {
    rpc Invoke(Execution) returns (ExecutionResult);
}
```
running this type of jobs won't be difficult than running shell commands
```
conn, err := grpc.Dial(job.GrpcURL) //new extra field for the Job
executor = pb.NewDkronExecutorClient(conn)
result, err := executor.Invoke(context.Background(), &pb.Execution{JobName:job.Name})
```

**Comment by redben** [comment]
One way that works without additional features from dkron right now is wrapping the specific job type "executor" in a cli command. Works nice. No coupling.

**Comment by caiovmv** [comment]
I have tried running jobs every 30 seconds, but found that the scheduler minimum time is 1 minute, this behavior is true, if so how can I change that in the source code ?

The second ask is about a way to remove jobs by rest api or somehow. I guess a list job_names passed as json or even based on a filter like "error_counts < 10". I as asked because I'm talking about a lot of jobs to be remove like 1.000 jobs. Even a clean reset is a good thing.

**Comment by victorcoder** [comment]
Done in v0.10.0
