### ISSUE TITLE
One-off jobs

### ISSUE THREAD

**Issue by whizz** [victorcoder/dkron#79]
Feature idea: I have a use case, where I need to execute something sometime later, but just once and then the job should be deleted or archived. I would specify a date and time, when I want the job to run, with optional time window and dkron would make sure, the job will be run on the specified servers or just one of them within the given window. If the job succeeds, it would be deleted. If not, it will be retried n times in the given window, with exponential backoff, maybe. If at the end of the window it still did not run successfully, it would be deleted also, possibly triggering an alert.

**Comment by victorcoder** [comment]
I like the idea, but :-1:  to delete the job on completion, if you don't have notifications enabled you won't be able to see the execution result.

**Comment by whizz** [comment]
Sure. By delete I meant basically "do not run again and move somewhere out of sight". But obviously it would be valuable to have access to it if I wanted to.

**Comment by digitalcrab** [comment]
Hello @victorcoder 

In my current company, we decided to try you Dkron. And one of the required features for us is an ability to have "one-time" cron's, so I have time to work on this issue.

Do you have requirements or understanding from your point of view how it should be done? Or I can create something by myself and then open pull request? 

Thank you for you time

**Comment by victorcoder** [comment]
@digitalcrab Any help is welcome!

> Do you have requirements or understanding from your point of view how it should be done? Or I can create something by myself and then open pull request?

I've been thinking in this issue for some time and I have a roadmap for it, let's follow the conversation by email. Ping me "victor at victorcastell.com"?

**Comment by digitalcrab** [comment]
Check an email. Thank you

**Comment by victorcoder** [comment]
@digitalcrab I did a PR with the feature, it actually took just a couple of hours
