### ISSUE TITLE
Executing deleted and changed jobs

### ISSUE THREAD

**Issue by jgranstrom** [victorcoder/dkron#85]
Dkron keeps executing deleted jobs for some reason. I have started two jobs with a simple curl command and then deleted both jobs, but they still keep executing. I'm not getting the jobs if I list all jobs in dkron. I get these logs in dkron:

```
INFO[2016-03-02T11:12:00+01:00] agent: Starting job                           job=job1
INFO[2016-03-02T11:09:00+01:00] agent: Starting job                           job=job2
WARN[2016-03-02T11:09:03+01:00] rpc: Received execution done for a deleted job.
WARN[2016-03-02T11:09:03+01:00] rpc: Error calling ExecutionDone              error=rpc: Received execution done for a deleted job.
WARN[2016-03-02T11:09:03+01:00] rpc: Received execution done for a deleted job.
WARN[2016-03-02T11:09:03+01:00] rpc: Error calling ExecutionDone              error=rpc: Received execution done for a deleted job.
```

If I query the consul key value at `/v1/kv/dcron/jobs/?recurse=` it's also empty.

If I restart dkron it stops executing the deleted jobs, but it seems to keep the schedule in memory after deletion.

After some digging I realised this seems to be an general issues when you make changes to a job, so for example if a disable a job it does not disable the in memory schedule and keeps going. Even worse if I make multiple changes to a job it creates new schedules for each change but does not stop the old one, so you will have multiple parallel executions for a single schedule. If I update a job that runs every second 5 times it then runs 5 times a second.

I'm using a local consul version `0.6.3` with a single node, and dkron version `0.6.4`. Both are running locally on OSX `10.10.2`.

Is this a known issue, or am I missing something in the documentation?

**Comment by victorcoder** [comment]
@jgranstrom when a job is created or updated the scheduler is restarted to pick up job changes https://github.com/victorcoder/dkron/blob/master/dkron/api.go#L169 this shouldn't cause problems with disabling jobs.

Nevertheless there's a bug in the delete job function as it needs to restart the scheduler too.

Said that, I'will fix this issues and make some tests for the create/update job case.

Notice that I'm currently making a major refactor in the leader election routine and I'll take a look after that.

**Comment by jgranstrom** [comment]
Alright, yes I saw the restart was missing in deletion of jobs. 

It's weird with the updating of jobs as it obviously calls the restart procedure, and still I experience the executions are being multiplied on update. When you have time to check this out please also try to do a few updates to an existing job and see if you get the same behavior as me with them being run once for each update you made.

Is there any point in me digging in this any further at this time, or will the refactor affect these areas?

Thanks!

**Comment by victorcoder** [comment]
> Is there any point in me digging in this any further at this time, or will the refactor affect these areas?

No, the ball is in my court

**Comment by jaymecd** [comment]
+1 faced same problem

**Comment by victorcoder** [comment]
@jgranstrom After my tests updating a job causes a scheduler restart and works as expected when disabling jobs.

Effectively, deleting a job didn't caused a scheduler restart and the job was still scheduled. I added the scheduler restart on job deletion and works as expected.

The leader election refactor is ready so, please could you to repeat some tests with the next release `0.7` or use the master branch?

If you still experience the error, feel free to reopen the issue.

**Comment by tejasmanohar** [comment]
@victorcoder We're still getting 
```
time="2017-04-18T21:37:48Z" level=error msg="agent: Error invoking job command" error="rpc: Received execution done for a deleted job." node=3ecc35ae7657
```
on v0.9.3 when changing / deleting jobs. Is this problematic?

**Comment by victorcoder** [comment]
@tejasmanohar This should happen only if the job was running while you deleted it. Write me an email to victor at victorcastell.com with more details if you want to discuss this further.
