### ISSUE TITLE
A few questions regarding the inner working of dkron

### ISSUE THREAD

**Issue by yellow1912** [victorcoder/dkron#88]
I could not find the answer anywhere, so I hope this is the right place to ask:

1. Does Dkron waits for a job to end to get the result and total run time? How does Dkron know if a job is "failed" or "succeed"?

2. If any job runs longer than expected, does DKron starts the job again? For example if the previous batch is still running then does Dkron know it should wait?

**Comment by victorcoder** [comment]
@yellow1912 

> Does Dkron waits for a job to end to get the result and total run time?

No it's an async system, fire the job, then the server will get notified when the work is done.

> How does Dkron know if a job is "failed" or "succeed"?

Command execution exit status. It's failed if different of 0. Much like a testing system.

> If any job runs longer than expected, does DKron starts the job again?

There's no concept of "longer that expected" currently in Dkron. Job can last arbitrary long times.

> For example if the previous batch is still running then does Dkron know it should wait?

No, like in traditional cron, a new job is executed.
