### ISSUE TITLE
No Slack notification at the end of a long job ?

### ISSUE THREAD

**Issue by castevinz** [victorcoder/dkron#99]
Hi,

I've noticed there's no Slack notification at the end of a long job. No problem for mail notification.
Is there a solution or a reason ?

Thx!

![capture d ecran 2016-04-01 10 07 46](https://cloud.githubusercontent.com/assets/1838350/14201378/cda52b18-f7f1-11e5-872b-6d781137498d.png)

**Comment by victorcoder** [comment]
@castevinz sorry for the delay. Something in the log? So many factors to consider here, even slack hicup...

**Comment by victorcoder** [comment]
Waiting for reproduction, closing this meanwhile
